### ISSUE TITLE
Workaround for post__in

### ISSUE THREAD

**Issue by kwafoawua** [10up/ElasticPress#1081]
Elasticpress Version: 2.3.2.
Wordpress Version: 4.7.3
Elasticsearch Version: 5.4.0

Hello everyone.
I'm having some issues with the "post__in" mapping.
I know post__in is supported in version 2.1 but I get this error everytime I run a query with orderby post__in.
I'm using FacetWP plugin and this happens with the search facet.

    "error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "No mapping found for [post__in] in order to sort on",
                "index_uuid": "YBTHkRmLSemBi2zptmNw3A",
                "index": "clasificadosc3devsimtlixcom-1"
            }
        ],

What can I do to fix this issue.
Thank you

**Comment by pierrebuet** [comment]
@kwafoawua : Your error text says it all already. Without knowing more of your code and your environment, I suppose strongly that the issue is not coming from the post__in argument itself which elasticpress handles well, but from the order by post__in. The issue is not "post__in" but "sort by post__in".

Elasticsearch is not built to sort results in an given order passed by an array of arguments (like the ID's in post__in) but calculates  a matching score calculated against a single argument for all the results possible. To get around this, you will have to pass an inline script in the request to elasticsearch.

**Comment by kwafoawua** [comment]
Thanks! I'm going to close the question!
