### ISSUE TITLE
Using autosuggest with WooCommerce?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [10up/ElasticPress#1099]
Have you searched for similar issues before submitting this one? Yes.

Is this a bug, question or feature request? Feature request.

Current WordPress version: 4.9.6

Current ElasticPress version: 2.5

Current Elasticsearch version: 6.3.0

Where do you host your Elasticsearch server: Self-hosted.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): WooCommerce

Do you have any plans to make the autosuggest feature work with WooCommerce, specifically product searches?

**Comment by brandwaffle** [comment]
We can do this one of two ways: either check the input in JS to see if it's a product search (has class of 'woocommerce-product-search') or we can check if both autosuggest and WooCommerce modules are active and inject the 'product' post type into the epas.postType object.

For simplicity's sake (and because it seems like the expected behavior) I'm leaning towards the second option of extending the epas.postType object.

@tlovett1 @allan23 any opinions?
