### ISSUE TITLE
results getting from default search instead of elasticpress

### ISSUE THREAD

**Issue by neymer1234** [10up/ElasticPress#1100]
Have you searched for similar issues before submitting this one?
its not a issue . a question only... i did search....

Is this a bug, question or feature request?
question

Describe the issue you encountered:
i have installed the plugin but i dont think its working .

Current WordPress version:
WordPress 4.9.6

Current ElasticPress version:
Version 2.5.2 

Current Elasticsearch version:
6.x

Where do you host your Elasticsearch server:
self

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
wpsolr .. 

Steps to reproduce:

https://goo.gl/sSajxS
elasticpress index is orthopediaco-1

search url - 
eg. 1 https://goo.gl/6zGfeo
eg2. https://goo.gl/73wM16

but results i a getting from default search

i also tried changing the theme. but same .

i looked everywhere , didnt find expected result

i know this a basic question but its not mentioned anywhere... 

so my question is 
1.how get search results? 
if its default search url why i am not getting results from elasticpress

2. do i need to change or add anything to wordpress php files to make it work?

ps. - i am not a developer ;(

**Comment by allan23** [comment]
@neymer1234, why do you have the wpsolr plugin activated?

**Comment by neymer1234** [comment]
@allan23 thanks for replying. I have been using it and i tried ElasticPress inorder to replace it.

So i tried disabling wpsolr, when i activated ElasticPress. But i couldn't get it working. So i have activated wpsolr in order continue my search function in website. I am ready to disable the same if i find a solution to get ElasticPress press replace default search

**Comment by brandwaffle** [comment]
@neymer1234 not sure if this is the answer, but did you have to customize your search input at all in order to get the wpsolr plugin to work? This could be either markup itself or the 's' query that fires on the backend. If either of these are customized, it could interfere with ElasticPress properly taking over the query.

Could you try installing the Debug Bar and Debug Bar ElasticPress plugins and pasting the results of a search query in this ticket?
