### ISSUE TITLE
ElasticPress from cPanel Cronjob

### ISSUE THREAD

**Issue by iexpertini** [10up/ElasticPress#1106]
Hi there,

I need the help to run the indexer from cronjob.  I am running this command from cron

A) curl -s wp elasticpress index -- setup

And got this error:

"curl: option --setup: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

B) I tried running without --setup but still it seems it won't run and neither send any error.

So I appreciated what command line I should run from cronjob

Thanks,
Ahsan

**Comment by oscarssanchez** [comment]
HI @iexpertini ,

Have you tried something like this ? https://stackoverflow.com/questions/38766046/run-wp-cli-commands-with-cron-job

**Comment by allan23** [comment]
Hi @iexpertini,
To further clarify, `curl` creates an external HTTP request (like a headless web browser). Since you'll want to use WP-CLI for ElasticPress indexing, you don't want to make an HTTP request, but instead run the command with your local PHP CLI. To accomplish this, you can use the StackOverflow answer above, or create a custom bash script that runs it for you.

For example, this script could look like:

```
#!/usr/bin/env bash

cd PATH_TO_WORDPRESS_INSTALL_HERE
wp elasticpress index --setup
```

Then in `crontab`, it could look like this:

```
*/10 * * * * myscript.sh >> /dev/null 2>&1
```

**Comment by iexpertini** [comment]
Thanks for thr information it helps
