### ISSUE TITLE
Repeated non-stop syncing

### ISSUE THREAD

**Issue by eraserx99** [10up/ElasticPress#1144]
Currently, we have the current setup,

WordPress 4.9.6
ElasticPress 2.6.1
ElasticSearch 6.3.2

  When we press the Sync button on the backend, we can see that an index is created and grows in ElasticSearch. However, when it finishes the indexing (based on the counter value on the ElasticPress dashboard), it starts from the beginning automatically (the index gets dropped and re-created again).

  Needs some help!

**Comment by brandwaffle** [comment]
@eraserx99 the Deleting index part happens first in the re-index process when you include the 'setup' flag--ElasticPress first deletes the index, then pushes mapping and then the actual posts.

Are you seeing any issues in the server logs when the dashboard sync loops? Given the number of posts you've got, I would recommend using the wp-cli version for any full syncs anyway, but it would be great to figure out why the dashboard option isn't working.

**Comment by oscarssanchez** [comment]
Hi @eraserx99 ,

Hope you are having a good day, Is this still an issue? 

As pointed out, "Deleting index" means deleting the index that matches your site. Each time you index a site that is not in a multisite network into elasticsearch via elasticpress, an index is created to store that data. A unique name is assigned to that index, and that's why we have to delete it each time you run a re-index, it is a requirement when you run one, to prevent index duplicates and your elasticsearch server to have a lot of duplicated data.

You can check this by pinging your elasticsearch server and checking how many indexes it has:

e.g `elasticsearch:9200/_cat/indices?v`

I hope this clarifies better. 
Have a nice day!

**Comment by oscarssanchez** [comment]
Closing this one out @eraserx99 . Feel free to reach out if this was not answered for you.

**Comment by PayteR** [comment]
Hi, @oscarssanchez i experience same issue as @eraserx99 

WordPress 5.2.0
ElasticPress 3.0.3
ElasticSearch 6.3.1

I'm on a multisite installation. When i set to initially sync posts into ES on one site in this multisite. Everything's fine, i see adding documents in `elasticsearch:9200/_cat/indices?v`, but when it reaches end, then it drops index, creates it again and then starts again from 0. It never ends and it stuck in infinite loop.

**Comment by PayteR** [comment]
When i tried to run  `wp elasticpress index --setup` then this error happened at the end
```
Processed 295400/350014...
Error: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received
```

**Comment by PayteR** [comment]
but tIt finished fine on the second run...
```
Processed 349300/350014...
Processed 349650/350014...
Processed 350000/350014...
Processed 350014/350014...
Number of posts indexed: 350014
Total time elapsed: 2&nbsp;955,253
Success: Done!
```
