### ISSUE TITLE
ElasticPress should not index non-Public or Deleted sites

### ISSUE THREAD

**Issue by mallorydxw** [10up/ElasticPress#1157]
Have you searched for similar issues before submitting this one? Yes.

Is this a bug, question or feature request? Bug.

Describe the issue you encountered:

In a multisite installation, each site has a set of attributes:  Public, Archived, Spam, Deleted, Mature.

No matter the state of these checkboxes, ElasticPress will index the contents of the site.

When Public is false or when Deleted is true, ElasticPress should skip indexing that site so that results from those sites don't show up in search results.

Current WordPress version: 4.9.8

Current ElasticPress version: 2.6.1

Current Elasticsearch version: 5.6.5

Where do you host your Elasticsearch server: Not relevant to this issue.

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..): None.

Steps to reproduce:

1. Network-activate ElasticPress
1. Edit a site on the network, setting Public to false or Deleted to true
1. Create a post on that site
1. Perform a sync with ElasticPress
1. ElasticPress will show the message "Syncing 2/2 (localhost/test-deleted)" or similar indicating it's indexing a private or deleted site
1. Searching for the post will find the post

Thanks!

**Comment by allan23** [comment]
Hi @mallorydxw, thank you for submitting this issue.
We will review and get back to you.

**Comment by TheLastCicada** [comment]
I think that considering public/private/deleted is important, but I believe this suggestion goes overboard and is not the solution we actually want.  By preventing "private" sites (aka not-public) from indexing, we are preventing elasticsearch from being used on private social networks, or private intranet sites, both of which are valid use cases for Elasticpress.  There's no reason that a private site shouldn't be able to index it's own content and use it within that site - and https://github.com/10up/ElasticPress/commit/6723c2d63cd06548932d9d50693e537f01f290c8 prevents Elasticpress from being used for those kinds of sites.  

Now, cross-site search is a big issue here and private sites should _not_ be included in cross site search by default (an override would be nice though).  For example, take this WordPress multisite install:

site1:  public:  cross-site search for all sites on multisite
site2:  public:  search for only site2
site3:  public   search for only site3
site4:  private  search for only site4

By default, site1 should only get results from sites 1, 2, and 3 and not from the private site4.  However, each site should be able to have it's own index that includes results from only that site, regardless if the site is public or private.  Additionally, site1 should be able to index site4 if specifically overriding the private limitation via code or an option.  I could see this being used on sites that have a paywall or require login, but want to show a preview of content on their main site.  

This issue is actively causing problems for at least a handful of sites using the Elasticpress plugin at 10up, so I believe it needs more attention.

**Comment by turtlepod** [comment]
I wonder if this need to be integrated to "Protected Content" section in the settings.
