### ISSUE TITLE
Your Elasticsearch version 6.5.0 is above the maximum required Elasticsearch version 6.2.

### ISSUE THREAD

**Issue by jeffceriello** [10up/ElasticPress#1170]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Question

Describe the issue you encountered:
I have installed the latest ElasticSearch (6.5.0) on the server via SSH. Then I have installed ElasticPress on my website and I when I connect to ElasticSearch I get the message:
`Your Elasticsearch version 6.5.0 is above the maximum required Elasticsearch version 6.2. ElasticPress may or may not work properly.`

Current WordPress version:
4.9.8

Current ElasticPress version:
2.6.1

Current Elasticsearch version:
6.5.0

Where do you host your Elasticsearch server:
On a cloud host (same place where the website is)

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WooCommerce, ACF, Ambrosite Next/Prev page, (many more)

Steps to reproduce:

1. Install ElasticSearch on server, run it
2. Installe ElasticPress

Screenshots, if needed:

**Comment by oscarssanchez** [comment]
Hi  @jeffceriello , 

We are working to officially support more recent ElasticSearch versions, but we currently only support officially until 6.2

See https://github.com/10up/ElasticPress/issues/1105 

You can still use 6.5 if you want to, but we are not sure everything still works, which I think it's not the case here, as ElasticPress related posts feature is not working since 6.3

Thanks gor raising your concern, and have a nice day

**Comment by oscarssanchez** [comment]
Closing this one out, feel free to reopen if the question was not answered @jeffceriello .

**Comment by simplenotezy** [comment]
Curious whether 6.5 is supported now? @oscarssanchez
