### ISSUE TITLE
Complete noob got some questions about partial matching, custom fields and compatibility with custom taxonomy filter plugin

### ISSUE THREAD

**Issue by Salamander3** [10up/ElasticPress#1220]
Have you searched for similar issues before submitting this one?
Yes.
Is this a bug, question or feature request?
Question
Describe the issue you encountered:
1) How can i make partial matches work? If i search for "eur" i need it to return "europe" as result too. I should mention i am using this code for AND logic already:
```
 function set_to_exact( $formatted_args, $args ) {
    if ( ! empty( $formatted_args['query']['bool']['should'] ) ) {
        $formatted_args['query']['bool']['must'] = $formatted_args['query']['bool']['should'];
        $formatted_args['query']['bool']['must'][0]['multi_match']['operator'] = 'AND';
        unset( $formatted_args['query']['bool']['should'] );
        unset( $formatted_args["query"]["bool"]["must"][0]["multi_match"]["type"] );
    }
    return $formatted_args;
}
add_filter( 'ep_formatted_args', 'set_to_exact', 10, 2 );
```
2) I have many custom fields (i use ACF plugin), but elasticpress doesn't search on any of them. How can i add at least 1 or 2 custom fields to the search results? Would it have a huge impact on speed? Should i forget about it?

3) I use [beautiful taxonomy filter](https://wordpress.org/plugins/beautiful-taxonomy-filters/) plugin. It can filter post by taxonomies you can narrow down things nicely. If facets is enabled it causes BTF to return wrong results. I understand facets could potentially replace BTF but, the widget only allow to choose 1 taxonomy. I'd need 3 in drodown menus not checkboxes. What can i do about this? So far i disabled facets.

4) I've successfully added `$query->set('ep_integrate', true);` to is_author() and is_tag(). But if i add it to is_tax() results are wrong (i think it just returns all posts) probably related to having BTF installed.

5) I'd love to have auto suggest enabled but i'm scare of exposing the elasticsearch server ip. How can i secure the server to enable autosuggest without risking a hack.

6) The related posts widget doesn't find anything, doesn't even show it's title.

Current WordPress version: 5.0.3

Current ElasticPress version: 2.7.0

Current Elasticsearch version: 6.3.0

Where do you host your Elasticsearch server: on it's own VPS. It's idle mostly load average 0.01

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

- Advanced Custom Fields PRO
- Beautiful taxonomy filter
- Classic Editor
- Custom Post Type UI
- GD Rating System
- Google XML Sitemaps
- Query Monitor
- Related Posts By Taxonomy
- W3 Total Cache
- WP Mail SMTP
- WP User Avatar
- Yoast SEO

Steps to reproduce: Please ask me if needed.

Screenshots, if needed: Please ask me if needed.

**Comment by oscarssanchez** [comment]
Hi @Salamander3 ,

Answering questions:

1.- Maybe this can help: https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-matching.html I'm not that familiar with what you try to accomplish here, if you can find the correct query to get the result you want in JSON, we can definitely help you formulate it in PHP so ElasticPress can convert it. 

2.- You have to set search fields, please refer to: https://github.com/10up/ElasticPress/blob/develop/README.md#L376

3.- Please refer to https://github.com/10up/ElasticPress/blob/develop/features/facets/class-ep-facet-widget.php#L236 to customize facet html. How about placing the widget three times and selecting a different taxonomy for each ?  Though i don't think a dropdown would work with this.

4.- Can you confirm this happens without the taxonomy plugin?

5.- This is not something that ElasticPress can do since this has to be done via ElasticSearch, Please check: https://www.elastic.co/products/stack/security We also have a solution that could save you these and other headaches called https://elasticpress.io already configured to work and 100% secure with ElasticPress, if you wish to try it. 

6.- It looks like this feature is not working, thanks for spotting it!

**Comment by oscarssanchez** [comment]
Just updating, a colleague and I went through the issue with related posts and likely the problem is the post you are looking does not have anything related to other posts. I could reproduce this issue but found i had content that was not related to other posts, hence the widget was returning and not displaying.

**Comment by seyntjim** [comment]
Hello, 

I have the same question as number 2. I'm so noob at this so pardon me for asking. I wanted to index titles and some meta keys only. Is it the right code?

```
new WP_Query( array(
    's'             => 'meta search phrase',
    'search_fields' => array(
        'post_title',
        'meta' => array( 'meta_key_1', 'meta_key_2' ),
    ),
) );
```

And where do I put this code? Thank you.

**Comment by Salamander3** [comment]
@oscarssanchez Thanks i'll dig into all your answers thanks so much for replying.
@seyntjim That's correct you can do this on functions.php or your own plugin:
```
// Add custom fields to search
add_action( 'pre_get_posts', 'add_cpt_to search' );

function add_cpt_to search( $query ) {

	if (($query->is_search && !is_admin()) && $query->is_main_query()) {

		$query->set('search_fields', array(
        'post_title',
        'meta' => array( 'acf_id1', 'acf_id2' )
	));
	}
}
```

**Comment by lolafrerot** [comment]
Hello, 

@MediaMaquina i tried your solution but it dosen't seems to work.. I tried to use some functions of the documentation : https://10up.github.io/ElasticPress/ but there is no example, and i am not familiar with "apply_filter" function. Any suggestion or mistakes i might have made ?

an example of my code i put in functions.php : 

`
add_action( 'pre_get_posts', 'my_search_filter' );
function my_search_filter($query)  {
    if (($query->is_search && !is_admin()) && $query->is_main_query()) {
        $query->set('search_fields', array(
            'post_title','post_excerpt', 'post_content', 'post_thumbnail',
            'meta' => array( 'bloc_libre', 'bloc_liens_utiles', 'bloc_documents_a_telecharger_copie', 'accordeon')
        ));
    }
}
`

Thanks a lot, 

Lola

**Comment by MediaMaquina** [comment]
Hey did you rebuilt the index after adding that?
