### ISSUE TITLE
Indexing incomplete

### ISSUE THREAD

**Issue by ga-studio29** [10up/ElasticPress#1267]
Have you searched for similar issues before submitting this one?

- Yes

Is this a bug, question or feature request?

- Question

Describe the issue you encountered:

- When syncing only some contents are Indexed. Sometimes not even regular posts are indexed and for custom post types only a few are indexed (for example, we've a custom post with 300 entries and only 10 are indexed in elasticsearch)

Current WordPress version:

- 5.1

Current ElasticPress version:

- 2.8.1

Current Elasticsearch version:

- 6.3.2

Where do you host your Elasticsearch server:

- Web host

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

- ACF Pro, Category order and taxonomu terms Order, Post types order, Rest Api cache, tag groups

Thanks for your help.

**Comment by oscarssanchez** [comment]
Hi @ga-studio29 ,

Can you please check if there's any errors by indexing with less posts per page with this wp-cli command:

wp elasticpress index --setup --post-per-page=100 --show-bulk-errors 

We have had a lot of issues like this when posts have a lot of meta data due to poor coded plugin / management. Usually lowering the posts indexed or deleting unrelevant meta fixes this. It would be good to start there.

Kind regards,

**Comment by agenceR2** [comment]
Hi @oscarssanchez ,

thanks for your answer.

I've run the command and for a custom post type on last entries I've got the following errors :

- type: illegal_argument_exception
reason: Limit of total fields [5000] in index [indexname] has been exceeded

How can I resolve that ?

Thanks and regards

**Comment by ga-studio29** [comment]
Hi @oscarssanchez ,

thanks for your answer.

I've run the command and for a custom post type on last entries I've got the following errors :

type: illegal_argument_exception
reason: Limit of total fields [5000] in index [indexname] has been exceeded
How can I resolve that ?

Thanks and regards

**Comment by oscarssanchez** [comment]
Hi @ga-studio29 ,

Per the errors you are getting (too many fields created by too many meta). I think you have problems with your current  post meta data. Could you please look out for duplicated or similar meta in the post_meta table of your site? Usually, cleaning it up solves this problem.

**Comment by cbratschi** [comment]
We've had the same issue. We are using ACF and some fields contain several hundred items. In order to reduce the mappings we had to exclude most of our fields which are not required for searches.

It would be very useful if wildcards could be used by the mapping. For instance we have fields named:

updates_*_content

All those fields contain HTML markup and a single mapping would be sufficient.

Another solution would be to combine all fields and create a single one.

Both would require some deep changes in ElasticPress.

Last but not least: the CLI tool shows such errors but the WordPress indexing page doesn't. I would like to see such errors listed there too.

**Comment by oscarssanchez** [comment]
Closing as i thinkg this is solved now. Thanks for the suggestions @cbratschi , i think we will have to think something as this is indeed a somewhat recurring issue.
