### ISSUE TITLE
Documents content are not properly searched

### ISSUE THREAD

**Issue by iDuuck** [10up/ElasticPress#1305]
**Have you searched for similar issues before submitting this one?** Yes

**Is this a bug, question or feature request?** Bug

**Describe the issue you encountered:**

ElasticSearch **or** ElasticPress isn't searching in documents (pdfs) even though the `ingest-attachment` plugin is installed.

**Current WordPress version:** 4.9.10

**Current ElasticPress version:** 2.8.1

**Current Elasticsearch version:** 6.4.0

**Where do you host your Elasticsearch server:** Self-hosted (same server as WP)

**Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):** WooCommerce, Enhanced Media Library, some self-written ones.

Steps to reproduce:

1. I have [a document](https://portal.ovb.de/wp-content/uploads/2018/08/TEST-PDF.pdf) with "Ysdfghjikdfghjkl" as content.
2. Go to [the search](https://portal.ovb.de/wp-json/eps/v2/search?s=Ysdfghjikdfghjkl&post_type=attachment) and try to find the document.
3. There is nothing shown.

Screenshots, if needed:

`ingest-attachment` is installed
![image](https://user-images.githubusercontent.com/325241/55495734-d8b14200-563d-11e9-9ab6-4daaa318c4b0.png)

`documents` feature is enabled.
![image](https://user-images.githubusercontent.com/325241/55495775-f4b4e380-563d-11e9-9ba8-363f647fb99c.png)

---

Guys, please help me.. this is my third bug ticket :(

**Comment by oscarssanchez** [comment]
This is working correctly for me @iDuuck ,

Could you please try:

1.- Update elasticpress to 2.8.2
2.- Use this sample pdf: http://www.africau.edu/images/default/sample.pdf
3.- Index
4.- Search for "This is a small demonstration"

You should get the PDF. 

If this is not happening, I'm afraid this might be something with how you installed the attachment plugin rather than a problem with elasticpress.

Kind regards,

**Comment by oscarssanchez** [comment]
Closing due to inactiveness, please feel free to open a new issue if this is still not addressed @iDuuck
