### ISSUE TITLE
Hitting error when saving changes through dashboard

### ISSUE THREAD

**Issue by mnazwan** [10up/ElasticPress#1370]
__Is this a bug, question or feature request?__
Bug

__Describe the issue you encountered:__
Hitting javascript error in console whenever I try to change and save settings through the dashboard. Chrome 74.0.3729.169.

__Current WordPress version?__
v4.8.3

__Current ElasticPress version?__
v3.0.3

__Current Elasticsearch version?__
v6.5.4

__Where do you host your Elasticsearch server?__
bonsai.io

__What ElasticPress features do you have currently active?__
Default installation

__Steps to reproduce:__

1. Install the plugin through Wordpress Plugins. Update settings to include Elasticsearch server. Start indexing. All fine up to this step.
2. Go to Elasticsearch dashboard. Turn off Post Search, click Save, and it won't save successfully. The error is available in Javascript console.

__Screenshots, if needed:__
https://ibb.co/zRXsWVy
https://ibb.co/rwsBrwT

**Comment by andersrehn** [comment]
Was also struggling with this issue. As it turns out there are more features not working. Once you get the save to not give console errors the dashboard does not actually save any values.

Here is a quick fix that will work using a filter until the PR is solved.


```
add_filter('wp_kses_allowed_html',
function ($allowedtags, $context) {
    if ('ep-html' === $context) {
         $allowedtags['a']['data-feature'] = true;
         $allowedtags['input']['data-field-name'] = true;
    }
    return $allowedtags;
}, 99, 2);
```

`$allowedtags['a']['data-feature'] = true;` is from your PR #1372

`$allowedtags['input']['data-field-name'] = true;` makes it possible to save the values
