### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by ServeMe** [10up/ElasticPress#1375]
this seems like a bug but I am not sure
When my website have a 50 request concurrently Elasticsearch goes creasy and consumed a lot of CPU this is wired because I don't have that huge index 500MB only

Elastic search version
6.8.1
Wordpress Version
4.9.6
ElasticPress Version
3.0.3
I use only the search feature from ElasticPress and I have elasticsearch on my server
to repreduce, the problem use ab tool
ab -n 5000 -c 50 https://www.mywebsite.com/

**Comment by mustafauysal** [comment]
Hi @ServeMe,

As a quick reminder: ElasticPress officially supports max version 6.3 for now. 
Also, it can't help your homepage unless you didn't integrate WP_Query with `ep_integrate` parameter. 

If you are running `ab` on the search page, make sure those queries hitting the Elasticsearch server. You can check `X-ElasticPress-Search` header.  Nevertheless, CPU usage depends on the server configuration/hardware, and you might consider to set-up cluster instead of a single server to handling 50 req/sec.

**Comment by ServeMe** [comment]
here is a wired situation
I had a plugin deactivated and integrate the `ep_integrate` parameter that was the reason for this problem. and also to notice the response does not have X-ElasticPress-Search header
On the other hand, I think it is wired that 50 requests/second is a huge number to handle on a server given that my server has 64 GB Ram and a good CPU, does I miss something?

**Comment by mustafauysal** [comment]
I'm not sure how did you integrate with `ep_integrate ` parameter but usually those requests hit the MySQL instead of Elastic when you can't see the `X-ElasticPress..` header. 

Which service consume the max server resources when you running `ab` test?
 
If the only bottleneck is Elasticsearch and you are sure about that; you may consider increasing [heap size](https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html) and tweaking the configuration
