### ISSUE TITLE
Custom Indexable documentation

### ISSUE THREAD

**Issue by traed** [10up/ElasticPress#1481]
I would love some documentation and/or examples of how to create custom Indexables, specifically for WP terms. Using ES to query stuff like categories would be great.

**Comment by Christophvh** [comment]
Same, since the introduction of indexable, search on custom post types is broken. So i need to create my own, but can't find any documentation

**Comment by felipeelia** [comment]
Since the creation of this issue we've already created a new Indexable for terms and CPT indexing is also working as expected. As for documentation, we have this page here that may help future readers of the issue: https://10up.github.io/ElasticPress/tutorial-indexables.html
With that said, I'm now closing it. Thanks!

**Comment by kmcaloon** [comment]
I know this is a little old, but the OP was asking for tutorials on custom indexables. The tutorial linked to above goes over built in indexables but only mentions custom in passing. Are they just not really used all that much? I can't really find much info on them.

**Comment by felipeelia** [comment]
They aren't used that much indeed, @kmcaloon. And when they are needed, the use cases vary so much that it is hard to write documentation that would cover it all. Also, generally, Indexables are tied to a WP_*_Query class and we have those already covered by the plugin.

Anyway, if you really need an indexable, these would be the general things you need to create:

1. A new mapping to tell Elasticsearch how your info's structure looks like. You can follow the existent ones in the plugin as examples.
2. A new class that extends our Indexable, and implement at least the put_mapping() (and point it to the item above), prepare_document(), and query_db() methods. That would cover the part of *how* you _send_ info to Elasticsearch.
2. A new class that extends SyncManager to manage *when* this info is sent (when a post is saved? A comment is deleted? etc.).
3. A new class to manage how the info is *retrieved* from Elasticsearch. As an example, for posts, QueryIntegration is responsible to intercept WP_Query calls and call Elasticsearch instead of MySQL. Comment's QueryIntegration does the same for WP_Comment_Query.
4. A new Feature, to enable and disable your new Indexable. It extends the Feature class and Feature\Comments can serve as a good example.

**Comment by kmcaloon** [comment]
Thanks @felipeelia. Yup I stared digging around in the plugin after posting things. Those steps you provided help better conceptualize and point me in the right direction. Will keep playing with it thanks.
