### ISSUE TITLE
ep_retrieve_aggregations not working 

### ISSUE THREAD

**Issue by coenve** [10up/ElasticPress#1493]
I'm using ElasticPress for more than a year with a version prior to 3.0. I now tried installing ElasticPress on a new website with the newest version of the plugin but I ran into the problem that the actoin ep_retrieve_aggregations is dead. 

I tried different ElasticSearch installations, tried debugging. In the end I installed ElasticPress 2.82 and it worked like a charm. I have build my own Facet plugin on top of ElasticPress and it uses the add_action ep_retrieve_aggregations. After 3.0 it looks to no longer work. 

1. Install the latest version, config any ElasticSearch installation.
2. Do a mapping, do an install.
3. Do a search action and add add_action( 'ep_retrieve_aggregations', 'callback_ep_retrieve_aggregations', 10, 1 );
4. Create function callback_ep_retrieve_aggregations, put an echo command in and you will see it's dead. 

I also tried looking into your Facet script, it does show categories for example, but they are all locked out. Seems like the aggregations are killed.  

Maybe it's a mapping problem???? Or did you remove it on purpose?

Any more questions, please let me know!

**Comment by mikelking** [comment]
Out of curiosity what version of ElasticSearch are your servers running?

**Comment by nirgal** [comment]
I add a similar issue, due to the fact I was running a WP_Search from within search.php that is supposed to only present an existing search, not to run - kind of recursively - a new search.

Fixed by tuning the existing query before it runs, from an ``add_action( 'pre_get_posts', ``...

Also the results are only available in ``$GLOBALS['ep_facet_aggs']``, which was hard to find.

**Comment by martian77** [comment]
I've had the same issue having hooked into ep_retrieve_aggregations. In version 2.8.2 it was found in EP_API, which has obviously been removed in version 3. 

You can achieve almost the same thing by hooking into 'ep_valid_response' in post 3.0 version of ElasticPress - almost the same because it returns the full response rather than just the aggregations. They are on $response['aggregations'] though, so it's pretty easy to work with. It's now in the file includes/classes/Elasticsearch.php.

**Comment by tlovett1** [comment]
Hey all, we will readd the hook in 3.4. Use the develop branch if you want the fix now.
