### ISSUE TITLE
Index health dashboard shows all indexes

### ISSUE THREAD

**Issue by tott** [10up/ElasticPress#1502]
**Describe the bug**
When running a multisite or multiple indexes within the same ElasticSearch instance the new index health point will show all indexes and not just the relevant indexes.

**Steps to Reproduce**
- Install in a multisite from develop branch. 
- Activate plugin with same credentials/endpoint on at least two sites
- Go to index-health on either site and you will see both indexes listed in index list/documents

**Expected behavior**
Unless network activated (and in network admin) the index health dashboard should limit the results to the current site/index.

**Screenshots**
https://i.imgur.com/qdZTtwF.png

**Comment by Stretch96** [comment]
We are experiencing this issue in v3.2.1

@tott Could we get this added to a future milestone (3.2.0 appears to have been closed)?

**Comment by morganestes** [comment]
After enabling X-Pack Security on an Elasticsearch 6.8 cluster, the `.security-6` index appears in the list, also. Not sure if it's because I'm using a custom role with excessive privileges, or if it's part of the same multi-index issue (previously I saw indexes for development and production sites that are connected to the same instance).

**Comment by ayebare** [comment]
Looking into this issue.

**Comment by tlovett1** [comment]
@tott was this fixed already?

**Comment by tott** [comment]
I don't think so

**Comment by moraleida** [comment]
Looking into this.

**Comment by ayebare** [comment]
looks like we both worked this https://github.com/10up/ElasticPress/pull/1698/files
