### ISSUE TITLE
Pre-PR: Passing index name in autosuggest endpoint

### ISSUE THREAD

**Issue by kwatson** [10up/ElasticPress#1514]
Hi,

I'm currently trying to automate the provisioning of wordpress + elasticsearch and i've hit a roadblock with the autosuggest endpoint setting.

In looking at the `Autosuggest.php` file, i see that you're [passing the index name](https://github.com/10up/ElasticPress/blob/237f4cbd5caa8f2f8fee2e3efde70fda3d10411e/includes/classes/Feature/Autosuggest/Autosuggest.php#L218) to your commercial offering's endpoint, and i'm trying to brainstorm how i can easily achieve this with the standard `endpoint_url` plugin setting.

As a proof of concept, i was successfully able to [modify line 230](https://github.com/10up/ElasticPress/blob/237f4cbd5caa8f2f8fee2e3efde70fda3d10411e/includes/classes/Feature/Autosuggest/Autosuggest.php#L230) to: `$endpoint_url = trailingslashit( $settings['endpoint_url'] ) . Indexables::factory()->get( 'post' )->get_index_name();`

Obviously, that would break any existing installations, so I'm not proposing that solution. However, how would you feel about another global configuration variable that could append the index name to the URL? (e.g. `EP_AUTOSUGGEST_INCLUDE_INDEX`) 

I'm happy to create a pull request for that, but i wanted to get your (the maintainers) thoughts on this first. I would also be happy to share my working nginx configuration as a more complete example for the wiki, as it also includes CORS and basic auth for R+W access to elasticsearch. 

I should also add that I'm aware the most obvious solution is to have the user append the index name directly when adding the autosuggest endpoint to the settings page. However, I don't think this is a great solution: 1) That index name is dynamically generated from the site url, so if that changes they need to also update this setting, and; 2) The index name is not displayed in the plugin, so they would need to query elasticsearch directly to discover that on their own.

Thanks!

**Comment by brandwaffle** [comment]
@kwatson I'd love to take a look at the nginx configs you have to see how that's approached.

I'm not opposed to taking a "guess" approach to the autosuggest endpoint URLs, but we do have a significant group of folks who self-host and elect to pass their results through a PHP endpoint for security since they're not familiar with nginx configuration, so I'd want to make sure we address them both functionally and also from a knowledge/security perspective with any proposed solution.

Our intention with the `EP_AUTOSUGGEST_ENDPOINT` constant and Dashboard setting was to provide an easy way to specify whatever endpoint you want, whether it's your Elasticsearch machine or a custom endpoint. While it's fine if you have something running in nginx, as you do, to open up your Elasticsearch endpoints directly, we normally don't recommend folks do this (as you'll see in the warning messages on the Feature), and this is another reason we don't default to filling in the field with the ES URL--as that allows for immediate functionality (but perhaps with a dangerous lack of security).

As a side note for anyone else reading this, the EP endpoints are most easily obtained by installing the Debug Bar ElasticPress plugin which provides the URLs in any debugged requests.
