### ISSUE TITLE
How to make the search / indexer ignore certain common stop words?

### ISSUE THREAD

**Issue by pratham2003** [10up/ElasticPress#1528]
This is  the prevent the search from returning irrelevant results for a search query like "How to make an apple pie" which results almost all articles in the search results.

If I exclude "How" "to" "an"  from the search I guess I would be able to get close to what I want to achieve.

Is there a way to limit results by a certain relevance threshold? i.e. I only want highly relevant results.

**Comment by brandwaffle** [comment]
@pratham2003 by default ElasticPress does include the typical English stop words as part of its analyzer. You can also customize this or the underlying analyzer by filtering the mapping.

You might be running into an issue because by default the search finds results that match some of the words in the search once it exhausts all matches that match all words in the search. You can customize this behavior to only match when all words are present in a field--this article explains how: https://www.elasticpress.io/blog/2019/02/custom-search-with-elasticpress-how-to-limit-results-to-full-text-matches/
