### ISSUE TITLE
missing token ‘ep-search-term’ in CORS header

### ISSUE THREAD

**Issue by jt-alex** [10up/ElasticPress#1553]
Hi, Sorry a bit of a newbie here. I'm getting this CORS error when trying to use the autosuggest feature of elasticpress

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at <EP> (Reason: missing token ‘ep-search-term’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

Is this something I need to configure on my site or in the AWS Elasticsearch?

Hope you can help me with this. 

Thanks!

**Comment by tott** [comment]
This is usually caused by an underlying issue with the request itself. Can you look in the web inspector for the request/response that is sent to the ElasticSearch endpoint when you use autosuggest. If you look at the response you get from the server you might be able to see a more detailed message. You can also install the debug-bar-elasticpress plugin to get some more insights into the queries/responses which can help debug the underlying issue. 
It would be also helpful to ensure you're running the most recent version of ElasticPress and that you're not seeing any javascript errors in your Browser console as you're sending the autosuggest requests.

**Comment by brandwaffle** [comment]
@jt-alex we have identified some JavaScript in the plugin that is causing this header to be emitted incorrectly. We're working on a fix.
