### ISSUE TITLE
Normalization Token Filter

### ISSUE THREAD

**Issue by ognjanovic** [10up/ElasticPress#1559]
Hi,

Is there an easy way to define some normalization token filter (serbian_normalization to be precise) described here https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-normalization-tokenfilter.html

I'm not sure is the ep_formatted_args the right filter to use?

Thanks.

**Comment by tott** [comment]
We're using the Snowball analyzer by default https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-snowball-tokenfilter.html/ 
and while it support a multitude of languages it seems that Serbian is not one of them so you would need to change this out for something else, otherwise you could use the filters ep_analyzer_language for setting the language in the mappings directly ie https://github.com/10up/ElasticPress/blob/develop/includes/mappings/post/5-2.php#L61

In your case it seems you will need to change the mapping and queries completely to match your tokenizer/filter.

You can do this through either the ep_post_mapping_file filter in https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L186
or the ep_post_mapping filter here https://github.com/10up/ElasticPress/blob/develop/includes/classes/Indexable/Post/Post.php#L195
I would likely advise creating a custom mapping file and using the first filter.
If you use autosuggest, - you will also need to use the ep_post_mapping filter to ensure the standard tokenizer gets replaced.

Once this is done you will need to reindex your site to apply the changes.
