### ISSUE TITLE
Ability to pass Query DSL

### ISSUE THREAD

**Issue by colegeissinger** [10up/ElasticPress#158]
A while back @mattonomics, @AaronHolbrook and I discussed briefly about being able to pass a raw Query DSL via ElasticPress. Utilizing WP_Query to interface with Elasticsearch is great, but there may be moments that constructing a raw ES query would be more appropriate.

Documenting that previous discussion here so we can discuss/strategize on this going forward.

**Comment by kara-todd** [comment]
@AaronHolbrook related to this, would it be possible to get the original function arguments passed in as well as the formatted arguments?

In other words to have: 
`return apply_filters( 'ep_formatted_args', $formatted_args, $args );`

This would make it much easier to pass in additional values over the API and override the final set of formatted arguments before going out to Elasticsearch. I needed to add some additional filters (ranges, custom field term matches) and to be able to sort by post date. It goes from being quite a pain to really easy just by allowing access to the original arguments.

Unless there's something I missed. :)

I can submit a pull-request if desired.

**Comment by mikaelmattsson** [comment]
Kara, are you also created a layered navigation for woocommerce perhaps?
That would indeed be a nice addition. In my case i have my only plugin, ElasticPressExtended, that doesn't use a lot of the original hooks from ElasticPress, but instead created its own hooks and filters and  calls the original filters from ElasticPress rather than add to them. In my case I have a filter that does exactly what you are describing because I needed that too.

    apply_filters( 'epe_format_args', $formatted_args, $query );

So you are not alone in thinking that there is a second argument missing on the ep_formatted_args

**Comment by kara-todd** [comment]
In my case, I'm just applying a slew of secondary filters to a set of search results. However, most of the data I'm using is coming directly from post meta. So I need to be able to sort and filter by various criteria base around custom fields (and often more criteria than one)

So for example, I have a situation where I need: posts related to another custom post type AND that have a date field (post meta) that fall between a range AND tagged by a taxonomy term AND sorted by that custom date field. So, this is probably pretty similar what you're running into trying to sort/filter/etc. in woo commerce.

**Comment by mikaelmattsson** [comment]
Yeah. Sounds similiar. What i did was I hooked into the ep_post_sync_args so that aditional data was added to the ES database, like some protected meta_data, in my case price (that also had to be saved as ints to perform range queries). Then I hooked ep_format_args to add the ES filters like range. In that case I don't really need the wordpress original query arguments. I just add my custom filter to the ElasticPress formated args.

It should be noted that i'm not using ElasticPressExtended on just wordpress search queries but almost all queries for posts that is normally done using MySQL. The range filter I describe above is however only used on WooCommerce pages where is_main_query is true.

Back to the original topic, I'm not 100% sure what you mean, but if you are trying to create and abstraction layer or ORM that would be nice. Building the ES query using an array is kind of annoying and there is a lot of the following:

    $args['and'][] = [
        'terms' => [
            "terms.{$key}.slug" => array_values($values)
        ]
    ];

the prefered way would be:

    $epQuery->addFilter("terms.{$key}.slug", $values);

**Comment by kara-todd** [comment]
Are you still allowing users to select the range on the front end? I guess I'm a little confused on how you're passing the value to the query.

If I want to have the user input a start and end date, and then select all posts where `post_meta.custom_date` falls between that range. How would I go about it using your proposed method?

I've been making calls over ajax and using the backbone client.js to send parameters to the search and then load the results back.

**Comment by mikaelmattsson** [comment]
Yes, the ranges are set in front end.
To perform a range query i think the values in the database cant be strings and values in post_meta are allways saved as strings.
So you probably, like i said in my previous post, have to hook ep_post_sync_args and add the custom date. To make sure that it will be saved as a date and not a string you will also have to add a mapping for the new proptery using ep_config_mapping. Look at the mapping for post_date and you will get a clue.
Use the chrome plugin Sence to check your data. Remember to run ”wp elasticpress --setup” after changing the mapping.

once the new properties has been added you can perform range queries on them. 
now hook into the ep_format_args and dump the arguments as JSON using json_encode($data, JSON_PRETTY_PRINT). Play around with the JSON string in Sence to figure out what you have to add the the filter to make your range query work.

Off topic: Have you considered using AngularJS instead of backbone?

**Comment by tlovett1** [comment]
@kara-todd filter added :) Right now it is just in the develop branch. It will be merged into master/.org with version 1.3

**Comment by kara-todd** [comment]
@tlovett1 awesome! Thanks very much.

**Comment by mikaelmattsson** [comment]
@tlovett1 
> Interesting idea. Perhaps a flexible wrapper class similar to WP_Query that hits ES.

I just created this https://github.com/10up/ElasticPress/pull/200
It's doesn't add a lot flexebility atm, but its a start, and it allows one to fetch an array of posts without using WP_Query.
