### ISSUE TITLE
Secure ES after 6.2?

### ISSUE THREAD

**Issue by jonathan-dejong** [10up/ElasticPress#1591]
**Describe your question**
Hi! 
I'm just wondering how one should go about securing the ES installation on a server now with ES 6.4 (and later 7.n)? 
From what I can tell ES shield is no longer supported by ES (after 5.n). 
I'm guessing one should use X-pack with later versions and that basic security does not require a paid service from ES.. But how will that work with EP?

**Comment by jonathan-dejong** [comment]
No one sitting with an answer? Did I stumble upon something forgotten or …?

**Comment by brandwaffle** [comment]
Hi @jonathan-dejong from a quick look at the ES documentation, they still support username/password basic auth. In other words, this should still work the same as it did pre-6.2 (though obviously the process to set up ES with this method of authentication may have changed). Are you seeing something different?

**Comment by jonathan-dejong** [comment]
Hi @brandwaffle 
Thank you for the answer :) 
Hmm well I don't see *how* to set it up at all tbh.

**Comment by brandwaffle** [comment]
Hi @jonathan-dejong I think this section of the ES documentation covers authentication: https://www.elastic.co/guide/en/elasticsearch/reference/current/secure-cluster.html

It seems perhaps the simplest way to get up and running would be to follow this approach: https://www.elastic.co/guide/en/elasticsearch/reference/current/file-realm.html

That said, ElasticPress.io employs a separate, custom authentication layer because we also found the built-in tools that ship with Elasticsearch to be frustrating and cumbersome. I think there might be some other alternatives to X-Pack that work similarly that you could look into as well.
