### ISSUE TITLE
Autosuggest - no results, loading indicator

### ISSUE THREAD

**Issue by MichaelSchober** [10up/ElasticPress#1610]
**Describe your question**
I couldn't find anything in the docs or in the issues, so I am asking here. I hope thats alright.

1. Is there a way to add a Custom text which will be displayed in the results if autosuggest requests returns 0 results being found?
2. Is there a way for Autosuggest to show that currently new results are being loaded? 

If the answer in both cases is no, can I add enhancement issues? 
I hope its okay that i created a question and not enhancements right away.
Thank you for you help and for this awesome plugin!

**Comment by brandwaffle** [comment]
Hi @MichaelSchober thanks for submitting this ticket!

For #1, I think that's a great idea. You could likely pull this off with some filters and a bit of clever JS at this point, but I certainly feel it's a worthy feature and we should add it to the plugin. Can you create a new ticket for the enhancement and please drop in any mockups or even just sketched out layouts for how you would see the UX working?

For #2, I think the idea is a great one, but I'm having a tough time thinking through how we'd indicate something like that given that each time a character is typed a new search occurs. We intentionally stay away from the visual side of things a lot with Autosuggest so that the site's theme will dictate the look and feel of how those elements appear. Is there a site that already does this that you like and could share as an example? Again, I think it's a worthwhile addition but I wouldn';t want things to get in the "way" of someone continuing to type.

**Comment by rhedman** [comment]
@brandwaffle

I'm also looking to solve the #2 issue. Couldn't the plugin offer either a "loading" event that can be used to do hook some JS magic to or simple just add a CSS-class to the search input e.g "is-loading" when a new result is being fetched (and then remove the class again). This way it would be easy in visually indicate the search is loading.

**Comment by felipeelia** [comment]
Hey @MichaelSchober and @rhedman ,

Can you both please check if #2070 works as you'd expect? Thanks!

**Comment by felipeelia** [comment]
Closing this one. For future reference, this is the page in the docs explaining the new feature: http://10up.github.io/ElasticPress/tutorial-theme-integration.html
