### ISSUE TITLE
Migrate autosuggest from JS to PHP?

### ISSUE THREAD

**Issue by fabianmarz** [10up/ElasticPress#1620]
**Is your enhancement related to a problem? Please describe.**
- It's currently not possible to adjust autosuggest search results

**Describe the solution you'd like**
- I requested comments on a suggested JS change which introduces hookability via JS using jQuery `triggerHandler` in https://github.com/10up/ElasticPress/issues/1251#issuecomment-572552684
- While this might not be the best solution, I started to think why the functionality is written solely in JS rather than AJAX and PHP using the `wp_ajax` hooks. This would allow more flexibility in styling the results.
- I don't know how performance is affected when using WP to query ES instead of query ES directly

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by brandwaffle** [comment]
@fabianmarz have you looked at Autosuggest.php in the last couple weeks? We have made a bunch of changes to move a lot of the logic into PHP (to maintain parity between results from autosuggest and standard searches when people customize the Weighting Engine).

As to why we don't run through WP, that is certainly possible (you can create a simple PHP file now and specify its URL as your Autosuggest endpoint). We don't do this because the delay goes from around 50ms to query ES directly to a very unpredictable amount, anywhere between 250ms and over a second or more, depending on how efficiently the plugins and themes on the site make use of WP AJAX hooks 😞 

If I'm understanding #1251 correctly, the good news is since most of our logic to generate the query is in PHP, it would be a smaller effort to also enable customization of the results. Can you provide some more details about how you'd be editing the results to match Search WP functionality? Just a screenshot with desired result view would be sufficient. Depending on the approach, we can reopen #1251 or use this ticket to catalog the effort.

**Comment by fabianmarz** [comment]
@brandwaffle, thanks for the clarification. Not in detail just had a look if it's possible to customize the search results in the meanwhile. 

I totally get the point of querying the endpoint directly as the mentioned performance WP bottleneck. That's also why I suggested some JS logic in #1251. Maybe there's a PHP solution using a custom controller and making use of the `WP_USE_THEMES` constant to minimise the bootstrap?

I'll add the related comments and screenshots to #1251.

**Comment by oscarssanchez** [comment]
Seems conversation went on #1251. I'll be closing this one.
