### ISSUE TITLE
Problems using EP with woocommerce

### ISSUE THREAD

**Issue by Tii** [10up/ElasticPress#1630]
I was trying out elasticpress and I found 3 bugs that keeps me from using it in production.
I am using Woocommerce with Wordpress and all plugins to the latest version. 
My Website has more than 200000 orders in the database.

When elasticpress is activate and index is created:

1. In the user's account "my orders" shows orders from .everyone (does not filter on the current user)
2. The Order list in the admin shows only 10000 results in pagination
3. I was not able to add a meta to the index, I tried to use the ep_prepare_meta_whitelist_key and the ep_prepare_meta_allowed_protected_keys hooks to add the meta to the index but it does not seem to do so and I cannot search by the added meta.

I have tried to find more example/documentation without success.

**Comment by brandwaffle** [comment]
@Tii can you do the following to help troubleshoot each issue:
1. Please show output from Debug Bar ElasticPress plugin that shows the query running on the orders page. Please share both the WP_Query array and the JSON Elasticsearch query.
2. Are you referring to the per-page limit or the total number of results it shows? Can you share some screenshots? This issue seems like it might be a bug we can address.
3. These are the correct filters to use--can you share the code you created so we can take a look?

Thanks in advance!

**Comment by tlovett1** [comment]
@Tii anyway we could get a DB dump to test/fix? I'm not able to reproduce 1 or 2.
