### ISSUE TITLE
AutoSuggest should warn about full index before activation

### ISSUE THREAD

**Issue by jeffpaul** [10up/ElasticPress#1645]
**Is your enhancement related to a problem? Please describe.**
The autosuggest feature should definitely warn before activation that it will trigger a full reindex which will render EP essentially “offline” while it runs. That likely needs at least a basic JS prompt, but if we can get some UX input on this that would be great.

**Describe the solution you'd like**

Feedback from @surrealwebs:
> We upgraded from 2.4 to 3.3. I re-indexed via CLI, looked at the dashboard for EP and it was saying we needed to re-sync even though the job had finished successfully via CLI. The button on the EP admin page wasn’t clear (I’m still new to EP) so I didn’t know what that button did. I thought it would refresh and the plugin would check the status of the index and remove the messages. I clicked it and it started indexing. There’s not messaging on the button, no warnings or anything so I was a bit surprised it just started going

> Same with the message about auto-complete being automatically activated and having the re-sync link there as well. I clicked it because I was curious and because I already messed up the index. It starts right away also.

> Ultimately, I ended up doing the index with CLI anyway because it’s faster, even then the message about needed to re-sync didn’t go away.

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by tlovett1** [comment]
@surrealwebs can you post the exact dashboard notice you saw after indexing via CLI?

**Comment by fagiani** [comment]
@tlovett1 

This has happened to me too. It was unfortunate as I had just spent hours indexing thousands of posts and had to do it all over again without any warning as the sync just started from nothing within the `wp-admin` interface.

I would be willing to contribute to document or a way to warn users or otherwise instruct users on the initial steps wizard to enable the features prior to the setup index via WP-CLI.

Thanks for creating this plugin!

**Comment by brandwaffle** [comment]
Closed as this is a subset of #1932 .
