### ISSUE TITLE
WP_Query integration?

### ISSUE THREAD

**Issue by simplenotezy** [10up/ElasticPress#1660]
Does it integrate with the native WP_Query or do I have to implement some custom code?

I am building custom REST endpoints for a WooCommerce shop to filter products based on filters such as categories And attributes.

I'm wondering if Elastic press could help speed up the response times - which is currently around 1 second.

**Comment by brandwaffle** [comment]
@simplenotezy yup, you just pass in `'ep_integrate' => true` as a WP_Query parameter and ElasticPress will route that query through Elasticsearch instead of WordPress. That said, it may or may not help your REST endpoint response times, as that could also be a result of other WordPress code running during the REST response.

**Comment by brandwaffle** [comment]
@simplenotezy I'd also recommend installing the Debug Bar ElasticPress plugin while doing your testing, as this will enable you to see if the queries might already be running through ElasticPress. Since the plugin integrates directly with WooCommerce, depending on how you build your endpoints, the queries might already be automatically integrated with ElasticPress.

**Comment by simplenotezy** [comment]
hey @brandwaffle. Thanks a lot for your time. I will check this out.
