### ISSUE TITLE
Cannot use date_query for a custom column by date part (year, month, day, etc)

### ISSUE THREAD

**Issue by sebumd** [10up/ElasticPress#1746]
As a developer, I should be able search by custom field and date part, like

$args['date_query'][] = array(
    'column' => 'meta.birthdate.date',
    'year' => '1947',
);

**Comment by Rahmon** [comment]
Hi @sebumd 

Looks like you're trying to filter posts by post meta conditions, right? If so, I think you need to use the `meta_query` parameter:

```php
new WP_Query( array(
    's'          => 'search phrase',
    'meta_query' => array(
        array(
            'key'   => 'key_name',
            'value' => 'meta value',
            'compare' => '=',
        ),
    ),
) );
```

Can you please test that and let us know your findings? If you found another approach, share it with us as well. Thanks.

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
