### ISSUE TITLE
Exclude custom fields from indexing

### ISSUE THREAD

**Issue by Fuzzzzy** [10up/ElasticPress#1759]
Hello,

Thanks for the awesome plugin.

1. Is there any way to exclude some custom fields from being indexed?
2. I can see that under each custom field there is some confusing data being sent to index. Why is that and why is it needed? I can also see that a simple text field has multiple types in the elastic index. Please see screenshot. 
![image_53](https://user-images.githubusercontent.com/15350181/80775856-83f63880-8b69-11ea-8177-e029c29eff6b.png)

Thanks!
Istvan

**Comment by felipeelia** [comment]
Hi @Fuzzzzy ,

To exclude custom fields from being indexed, you can use the [ep_prepare_meta_excluded_public_keys](http://10up.github.io/ElasticPress/ep_prepare_meta_excluded_public_keys.html) filter. Your code will look like this:
```
add_filter(
	'ep_prepare_meta_excluded_public_keys',
	function ( $excluded_keys ) {
		$excluded_keys[] = 'your_meta_field_id';
		return $excluded_keys;
	}
);
```

Regarding multiple types being saved, that happens because ElasticPress tries to save the field in all possible ways. So, if the field is a string it will try to pass it through the `strtotime()` and save the result. You can give a look at the [\ElasticPress\Indexable::prepare_meta_value_types()](https://github.com/10up/ElasticPress/blob/bcfb1ab0ce6649124bc401cee0ff877835a24787/includes/classes/Indexable.php#L391) method to see how it works.

Please let us know if you have any further questions, okay? Thanks!

**Comment by Fuzzzzy** [comment]
Thanks for that, I'll try it out!
