### ISSUE TITLE
Why i can't delete plugin?

### ISSUE THREAD

**Issue by bilalmalkoc** [10up/ElasticPress#1778]
I can't delete plugin. Can you explain me why?

**Comment by felipeelia** [comment]
Hi @bilalmalkoc, thanks for opening this issue. This problem was discussed in #1760 and fixed in #1767. The new version will already have this fixed.
If you don't want to wait, you can either manually delete it or apply [this change](https://github.com/10up/ElasticPress/pull/1767/commits/d9cb5df91784236e8f0dc23d7ea9c4ae4766b85f).

**Comment by tlovett1** [comment]
Please confirm this is fixed.
