### ISSUE TITLE
Indexing is very slow

### ISSUE THREAD

**Issue by pulkit8** [10up/ElasticPress#1797]
I am trying to create an index using elasticsearch for a database with around 90,000 Posts. 
The time being taken to create index is way high (like 24 hours+), however, ideally I don't think so it should be this high and hence would need some guidance on it. 

Please find some related information below : 

Elastic Search is setup on Linux Server with following Specs
20 CPU cores 2.5ghz Xeon E7
96GB RAM
100GB SSD
LiteSpeedEnterprise Web Server
MariaDB 10.1

WordPress Website is also hosted on the same above server. Total Database is about 3GB with 80k-90k Posts on website.

ElasticPress is connected with ElasticSearch instance and then indexing has been started. It takes about 15-20 mins to index 1000 posts. [Just in case, this is normal behaviour then you can ignore reading below]

To further investigate, I tried remote elasticsearch server too at AWS ElasticSearch service where it was same slow speed indexing. Tried setting up another VPS for ElasticSearch in same data centre with remote access to ElasticSearch Instance.
But there was no improvement.

**Steps to Reproduce**

1. Setup ElasticPress 7.5.2 from official documentations and keep every configurations to default. For remote access of ElasticSearch, I added the following in config file.
transport.host: localhost
transport.tcp.port: 9300
http.port: 9200
network.host: 0.0.0.0
2. Install ElasticPress Plugin and connect using endpoint
3. Start the wp-cli command to start indexing.
/usr/local/lsws/lsphp73/bin/php /usr/local/bin/wp elasticpress index --setup --debug --allow-root

**Expected behavior**

Indexing to be fast, couldn't find any bottleneck from server side or any specific error logs.

(I kept all plugins off too from my 3rd test onwards. Also, the website is a staging instance and hence no real traffic load)

### wp-core ###
version: 5.4.1
site_language: en_US
user_language: en_US
timezone: Asia/Kolkata
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 193
dotorg_communication: true
### wp-paths-sizes ###
wordpress_path: /home/hiddendomain.com/public_html
wordpress_size: 213.62 MB (223998817 bytes)
uploads_path: /home/hiddendomain.com/public_html/wp-content/uploads
uploads_size: 16.99 GB (18246370345 bytes)
themes_path: /home/hiddendomain.com/public_html/wp-content/themes
themes_size: 69.11 MB (72465938 bytes)
plugins_path: /home/hiddendomain.com/public_html/wp-content/plugins
plugins_size: 51.01 MB (53486404 bytes)
database_size: 2.70 GB (2896429056 bytes)
total_size: 20.02 GB (21492750560 bytes)
### wp-active-theme ###
name: Custom-theme
parent_theme: none
theme_features: title-tag, html5, post-thumbnails, menus, widgets
theme_path: /home/hiddendomain.com/public_html/wp-content/themes/custom-theme
### wp-themes-inactive (1) ###
Twenty Twenty: version: 1.3, author: the WordPress team
### wp-plugins-active (1) ###
ElasticPress: version: 3.4.1, author: 10up
### wp-plugins-inactive (14) ###
AMP: version: 1.5.3, author: AMP Project Contributors
Apester Interactive Content: version: 2.1.3, author: Apester (latest version: 2.1.4)
Arena.IM - Live Blogging for real-time events: version: 0.2.4, author: Arena.im
Classic Editor: version: 1.5, author: WordPress Contributors
Debug Bar ElasticPress: version: 1.4, author: 10up
Instant Articles for WP: version: 4.2.0, author: Automattic, Dekode, Facebook
LiteSpeed Cache: version: 3.2.1, author: LiteSpeed Technologies
Mashshare - Google Analytics Integration: version: 1.0.9, author: René Hermenau
Mashshare - Responsive Add-On: version: 2.0.7, author: René Hermenau
Sunny: version: 2.5.0, author: Typist Tech
Yoast SEO: News: version: 12.4.1, author: Team Yoast
Yoast SEO Premium: version: 14.3, author: Team Yoast
### wp-media ###
image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available
### wp-server ###
server_architecture: Linux 3.10.0 x86_64
httpd_software: LiteSpeed
php_version: 7.3.17 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 90
memory_limit: 1024M
max_input_time: 60
upload_max_size: 256M
php_post_max_size: 512M
curl_version: 7.29.0 NSS/3.44
suhosin: false
imagick_availability: false
htaccess_extra_rules: true
### wp-database ###
extension: mysqli
server_version: 10.1.45-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
### wp-constants ###
WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/hiddendomain.com/public_html/wp-content
WP_PLUGIN_DIR: /home/hiddendomain.com/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined
### wp-filesystem ###
wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable
`
   </details>

**Comment by pulkit8** [comment]
`Processed 80042/80042...
Number of posts indexed: 80042
Total time elapsed: 61,686.840
Success: Done!`

**Comment by pulkit8** [comment]
@oscarssanchez Hi,  do you have any insights on this ?

**Comment by oscarssanchez** [comment]
Hi @pulkit8 ,

Thanks for reaching out, I think there could be many reasons! Although disabling all plugins but elasticpress and keep seeing issues takes one of the most tedious parts! 

With that said, before arguing it could be your elastic instance, can you let us know more about the data you are trying to index? Are there any custom fields in there? Do you have a lot of big media files?

**Comment by pulkit8** [comment]
Hi @oscarssanchez  thank you for looking into the query. Yes, there can be multiple reason, I tried debugging and doing many P&C before ending up asking help here :)) 


Are there any custom fields in there? : Yes, there are some custom fields here. eg. post-featured ( meta key ) and value set to 1 and few more exists.

Do you have a lot of big media files? : Big media files , no but large number of media files , definitely yes.

**Comment by brandwaffle** [comment]
@pulkit8 can you share which ElasticPress features you currently have active (e.g. Autosuggest)? If you have Documents or Protected Content turned on, start by trying to reindex without those. Beyond that, you can try reducing the number of items to index per cycle in the ElasticPress settings menu. If your issue is the WP code trying to prep a lot of posts, you'll see faster turnarounds per request. If your issue is your ES server, you would still see slow response times.

For comparison, 90,000 posts should take about 15-30 minutes total unless they're really large items like Documents that are actually being OCR'd.

**Comment by pulkit8** [comment]
@brandwaffle  

I have all the features off and only few necessary ones ON. (autosuggest is off, protected content is also off). Tried reducing the number of items to index already. Did many different settings but no luck. 
For server part, as I shared the details, I had a full dedicated 4xE7 processor server with pretty much RAM and NVME disk too (top notch server). I have verified all settings for any bottleneck. There is rare chance to be any fault from server side (since have been managing server from quite a time and checked all logs + needed things)

Attached screenshot of settings, in case I am missing something or doing anything wrong. The website has no documents and for media, there are only images. (regular news portal type images)

![Screenshot_1992](https://user-images.githubusercontent.com/5451769/86509416-65304e80-be05-11ea-861b-16146f4651df.png)
![Screenshot_1993](https://user-images.githubusercontent.com/5451769/86509419-682b3f00-be05-11ea-9d4b-fe1abcb60d5b.png)

**Comment by tamara-m** [comment]
@brandwaffle @pulkit8 Leaving this comment here in case it helps.

We started indexing a pretty large bbpress data set of ~1,700,000 posts and the associated postmeta from bbpress that adds several post meta records per post.

Running `wp elasticpress index --setup` with its default at 350 per cycle was taking between 3 and 4 minutes per cycle. 

The process run like this for ~28 hours and then we got a server connection killed.

We thought what if we resume using `--per-page=750` instead of 350. And surprise, it's taking now taking between 30-60 seconds per batch.

750 / 30-60 seconds down from 350 / 3-4 minutes.

**Comment by pulkit8** [comment]
@tamara-m  I tried this P&C already, however, no luck.
New index command runs fast for existing index batch and then drops the speed. 

Takes forever to create index. 

Didn't receive any in-depth detail to debug or fix this.

**Comment by oscarssanchez** [comment]
Hi @pulkit8 ,

Could you provide some sample data we can try this on?

**Comment by oscarssanchez** [comment]
Hi @pulkit8 , I'm closing this one out but if you still need help please feel free to open a new ticket.

**Comment by fagiani** [comment]
@oscarssanchez sorry to post on a closed issue. I am also experiencing slow indexing but I understand that is a relative perception depending on the singular data structure one is handling.

I'd like to understand if there is any place where we can find some guidance about an optimal spec to the initial setup index with a large dataset in order to expedite it given after this moment you could potentially dispose of less resources only to search and keep indexes up to date.

Is there any baseline config or ratio for the MySQL, Worker (WP CLI) and ES cluster in terms of resources like multiple nodes vs a single big node?

I am asking specially because when running the WP CLI index command I wasn't capable of determining if it would leverage of multiple threads or cpus if available to parallelize the process or also if setting up multiple workers and using the offset parameter would be beneficial to it at all.

I apologize if this is something already public available and I was not capable of find it.
