### ISSUE TITLE
Related Posts not working as expected

### ISSUE THREAD

**Issue by DenisFlorin** [10up/ElasticPress#1841]
Hello,

I need help configuring elastic press to show related posts. For example, on this link https://www.addictivetips.com/internet-tips/whats-this-song/, the section "Related Reading" doesn't display correctly the related posts. Here is an image:
![image](https://user-images.githubusercontent.com/38504865/88061106-bfecd880-cb6f-11ea-8030-cb491175b26a.png)

Let me know if you need anything else from my side.

Thank you,

**Comment by brandwaffle** [comment]
@DenisFlorin you'll want to install the Debug Bar and Debug Bar ElasticPress plugins on your staging site. Then you can load that page in staging to see if ElasticPress is properly handling the query (if so, you'll see a 'more_like_this' in the query body). If the query itself is working, then you might want to consider additional customization of the query (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html). If you get an error that indicates the query is failing, please paste that here. Also, please add the bug reporting info if you do run into an error:


**Describe the bug**


**Steps to Reproduce**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**


**Screenshots**


**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by DenisFlorin** [comment]
Hello, 

I attached my query bodies here. I don't understand from here https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html how I can configure them. 

`{
    "from": 0,
    "size": 2,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "more_like_this": {
            "like": {
                "_id": 381565
            },
            "fields": [
                "post_title",
                "post_content",
                "terms.post_tag.name"
            ],
            "min_term_freq": 1,
            "max_query_terms": 12,
            "min_doc_freq": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "post_type.raw": [
                            "post"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish"
                        ]
                    }
                }
            ]
        }
    }
}`

`{
    "from": 0,
    "size": 8,
    "sort": [
        {
            "post_date": {
                "order": "desc"
            }
        }
    ],
    "query": {
        "more_like_this": {
            "like": {
                "_id": 381565
            },
            "fields": [
                "post_title",
                "post_content",
                "terms.post_tag.name"
            ],
            "min_term_freq": 1,
            "max_query_terms": 12,
            "min_doc_freq": 1
        }
    },
    "post_filter": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "post_type.raw": [
                            "post"
                        ]
                    }
                },
                {
                    "terms": {
                        "post_status": [
                            "publish"
                        ]
                    }
                }
            ]
        }
    }
}`

**Comment by DenisFlorin** [comment]
Hello @brandwaffle 

Can you help me?

First of all, I would like to know if the query is fine.

Thank you,

**Comment by salvoaranzulla** [comment]
@brandwaffle  The problem is "sort": [ { "post_date": { "order": "desc" } } ] as I have written on https://github.com/10up/ElasticPress/issues/1865

**Comment by DenisFlorin** [comment]
Thank you for your comment @salvoaranzulla.

@brandwaffle can you take a look, please?

Thank you,

**Comment by mckdemps** [comment]
The issue is that the posts are being sorted prior to returning the top five results. We need to apply date decay using the same algorithm as for the main search query (aka use the search features setting for whether to weight by date to determine whether to add this to the query).

**Comment by Rahmon** [comment]
@oscarssanchez Maybe #2042 (and the PR associated) can help you giving some direction.

**Comment by oscarssanchez** [comment]
@DenisFlorin @salvoaranzulla can you please test with this branch ? https://github.com/10up/ElasticPress/tree/fix/related-posts-order 

Thanks!
