### ISSUE TITLE
400 Bad Request! Really need help to fix it.

### ISSUE THREAD

**Issue by alexminh-its** [10up/ElasticPress#1859]
I active ElasticPress Query Log and here is result I have for this problem. Do anyone has fixed this? Really need help to fix it.
{
    "error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "No mapping found for [meta._priority.raw] in order to sort on",
                "index_uuid": "FA56AG4wSFKGDYOBi5sstg",
                "index": "post-1"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "-post-1",
                "node": "qcP-MsLQTEmPwPxTQd7MQw",
                "reason": {
                    "type": "query_shard_exception",
                    "reason": "No mapping found for [meta._priority.raw] in order to sort on",
                    "index_uuid": "FA56AG4wSFKGDYOBi5sstg",
                    "index": "post-1"
                }
            }
        ]
    },
    "status": 400
}

**Comment by brandwaffle** [comment]
Hi @alexminh-its,

The issue you're seeing is likely because that field is private meta which is not automatically indexed by ElasticPress. The solution is to add this filter:

`function whitelist_meta_keys( $meta, $post ) {
    return array_unique(
        array_merge(
            $meta,
            array(
                '_priority'
            )
        )
    );
}
add_filter( 'ep_prepare_meta_allowed_protected_keys', 'whitelist_meta_keys', 10, 2 );`

This will add the `_priority` field to the list of keys indexed by ElasticPress. You'll then need to reindex to ensure the fields are properly synced.
