### ISSUE TITLE
Facets cannot be added to pages containing custom post queries

### ISSUE THREAD

**Issue by shaneonabike** [10up/ElasticPress#1861]
**Describe the bug**
I'm creating a custom page (like a search) which includes the Posts widget. I have successfully modified the WP_Query so that it requests the data from Elastic. Hooray!

The bigger issues is when I include the Facets they don't appear. I'm assuming there is some logic that is preventing Facets from appearing on certain pages. Maybe this is somewhat related to #1304 

**Steps to Reproduce**
1. Create a custom page
2. Drop in a Posts Widget that includes a custom post type (I use Elementor for this)
3. Add a Facet Widget
4. See the page and there is no facet

**Expected behavior**
I was assuming that like ApacheSolr the facets would just appear and then append the selections to the URL (so that ElasticSearch can do it's thing). Or we can put it into the $POST as well.

**Comment by brandwaffle** [comment]
@shaneonabike my guess is you're running into the is_main_query() check here https://github.com/10up/ElasticPress/blob/84ba959f31944ece2fd507c4fff679daa71cd024/includes/classes/Feature/Facets/Facets.php#L195

The Facets are designed not to appear on single pages, since there's no way to facet in that context. I'm guessing since Elementor is adding this list of posts to a single page, the main query is returning that page, and therefore the secondary query is not being faceted.

I think adding a filter into the is_facetable check that will let you conditionally override the logic and perform the faceting query should handle this. I'll be checking with the team and will update the ticket. In the meantime, for testing, you can add some code into that function to detect if you're looking at the particular Elementor query that's loading the posts list, and then return true in that case. This should help you work around the problem short-term.

If you'd like to just test the widget functionality, you can do so on any archive page (post, page, or CPT is fine).

**Comment by shaneonabike** [comment]
Ok so from what I can see the first block is definitely the is_main_query();

The second block I found was here
`                if ( ! ( ( function_exists( 'is_product_category' ) && is_product_category() )
                        || $query->is_post_type_archive()
                        || $query->is_search()
                        || ( is_home() && empty( $query->get( 'page_id' ) ) ) )
                ) {
                        return false;
                }
`

When commenting out both checks I end up with no results, and the facets stop appearing.

I want to backtrack a bit though. Facets won't work properly on pages normally? So if I can get it to show it won't work? Is there ways to make multiple search pages instead? Basically, I want to build a page that lists a custom CPT. I think I realized that the best way is for me to setup an archive page, and then I can use the facets.

**UPDATE:** I tried the archive and this works better. The other solution even when disabled really breaks things. Perhaps a suggestion is just to update the docs to include the limitation that this works only with Archives, Search, and Woocommerce. (Maybe it's there and I missed it)

**Comment by brandwaffle** [comment]
@shaneonabike thanks for the update! 

I do think if we apply some additional logic in the plugin we can get facets to apply to post archive lists that are nested inside single pages without the breakage you saw, but if the workaround is easy enough, I'd love to avoid that effort. Does the approach of using the archive page work well in your case, or are there tradeoffs vs the approach you wanted to take? We can definitely update the docs to reflect the limitations (it's not there right now), but I want to make sure we shouldn't try and solve the underlying problem if there is one.

**Comment by shaneonabike** [comment]
It works great actually.!

I mean the only hangups that I am presently struggling with is how to get a search box that just searches the archive, and another strange issue where the results are appearing twice when filtered (this is true to the main search as well).
