### ISSUE TITLE
Provide filters for post statuses in sync manager class

### ISSUE THREAD

**Issue by jonathanbardo** [10up/ElasticPress#190]
Right now the function ```action_sync_on_transition``` of the ```EP_Sync_Manager``` class contains a couple of hard coded post status (publish). One of the problem I've been facing with creating the plugin that would provide search in the admin is that we need to index all potential post status. 

@AaronHolbrook I wanted your input before creating a pull request. I think some filters to let the elasticpress admin plugin override some post status would be interesting but completely overriding the function could also be another solution to this problem.

**Comment by AaronHolbrook** [comment]
Hey @jonathanbardo, so this presents an interesting dilemma. If we go down the path of allowing unpublished posts to be indexed, we'll need to be sure that the default search includes a filter that searches for only published posts (otherwise people might shoot themselves in the foot by allowing drafts to be searchable from the frontend).

@tlovett1 this is to allow for a better admin search - do you have any other thoughts on this?

**Comment by jonathanbardo** [comment]
@AaronHolbrook Of course if we decide to go that path we have to tell people that the elasticsearch server need to only respond to request from specific host only and not from the client has it would give people an api to get all posts, even private ones.

**Comment by tlovett1** [comment]
+1 on a filter for post status.

@AaronHolbrook we will then need to support the post_status param in WP_Query.

**Comment by jonathanbardo** [comment]
I'll try my hand on this in the coming days and do a pull-request. I think I'm very close to something that works!

**Comment by AaronHolbrook** [comment]
Closed by #192
