### ISSUE TITLE
Don't load the searchterm-highlighting css if that feature is disabled

### ISSUE THREAD

**Issue by lakrisgubben** [10up/ElasticPress#1925]
Hi,

i noticed that the call to `wp_enqueue_style` in https://github.com/10up/ElasticPress/blob/master/includes/classes/Feature/Search/Highlighting.php#L58 for enqueing the searchterm-highlighting css does not have a check for if that feature is activated so it's always enqueued. Happy to make a Pr that checks if `$settings['highlight_enabled']` is true before enqueing if y'all think it's worthwhile. :)

**Comment by felipeelia** [comment]
Hi @lakrisgubben,

Yes, I'm able to reproduce that. It would be great if you could make that Pull Request!

And perhaps instead of checking just that enqueue call, we should not instantiate (and setup) the class at all if the feature is disabled. You can insert that if here: https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Search.php#L71

Thanks in advance!

**Comment by lakrisgubben** [comment]
Looks like this is already fixed by @tlovett1 in https://github.com/10up/ElasticPress/pull/1928 :) Thanks for that!
