### ISSUE TITLE
ElasticPress interferes with product visibility/ product query plugin, Any idea how to fix it?

### ISSUE THREAD

**Issue by stefanstatescu1** [10up/ElasticPress#1934]
Hi,
I'm the developer of a WooCommerce product visibility plugin. My customer is facing an issue where ElasticPress overrides which products are visible.

My plugin uses "woocommerce_product_query" to control visibility. I tried increasing the priority of the function, that didn't help.

Any idea how we could make them work together?

Thank you,
Stefan

**Comment by brandwaffle** [comment]
@stefanstatescu1 We'd love to work with you on this!

Can you share how your plugin stores the visibility to apply via the filter? ElasticPress should read any meta or tax query values and properly handle them, so it's likely a matter of making sure that gets into the actual query.

**Comment by stefanstatescu1** [comment]
Thank you for the help Vasken,

The plugin stores the post ids (visibility is controlled at the product level so it needs to know exactly which products) as a transient for each user. Then sets the post__in argument:

Looks like this:

```
$idsarray = get_transient('plugin_user_'.get_current_user_id().'_visibility');
$query->set('post__in',$idsarray );
```

**Comment by Rahmon** [comment]
Hi @stefanstatescu1 

Your code is not working because the action `woocommerce_product_query` is not called when ElasticPress is enabled. Instead, ElasticPress uses the filter [posts_pre_query](https://developer.wordpress.org/reference/hooks/posts_pre_query/) to [build the query](https://github.com/10up/ElasticPress/blob/4719c8c0847619f0ac4143ddde1e66325c7215a2/includes/classes/Indexable/Post/QueryIntegration.php#L192) that will be used by Elasticsearch. So I think you could use the filter `posts_pre_query` in your plugin when ElasitcPress is activated.

The code below might help you:

```php
add_filter( 
	'posts_pre_query',  
	function ( $posts, $query ){
		if ( 'product' === $query->query_vars['post_type'] ) {
			$query->set( 'post__in', [23, 15] );
		}
	},
	9,
	2 
);
```

**Comment by Rahmon** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks.
