### ISSUE TITLE
How to Connect to Elastic Managed Cloud

### ISSUE THREAD

**Issue by fxfancher** [10up/ElasticPress#1945]
Hi,

im trying to replace algolia on my site [https://ohmymi.com.my](https://ohmymi.com.my) with elastic cloud.
i deployed elastic cloud on Azure. im able to login to the App search, have the endpoint url, search key and private key.

but when i activate the plugin its only asking for elasticsearch host url. i pasted my endpoint url, but unable to sync. 

is there any proper guide to connect to elastic cloud? 

where do need to define our username/password/api keys? 

thanks

**Comment by oscarssanchez** [comment]
Hi @fxfancher , you can define your authentication keys as described here: http://10up.github.io/ElasticPress/tutorial-security.html

**Comment by 5amclub** [comment]
@oscarssanchez " Your Elasticsearch version is below the minimum required Elasticsearch version 5.0. ElasticPress may or may not work properly. "

my cloud provisioned is v7.9.3, anything wrong?

**Comment by fxfancher** [comment]
@oscarssanchez " Your Elasticsearch version is below the minimum required Elasticsearch version 5.0. ElasticPress may or may not work properly. "

my cloud provisioned is v7.9.3, anything wrong?

**Comment by brandwaffle** [comment]
@fxfancher ElasticPress currently supports up to 7.9 so you're likely seeing this as your version is newer than that. Things may work or there might be compatibility issues.

**Comment by rtwilliams5** [comment]
Is there an update to the link above ( http://10up.github.io/ElasticPress/tutorial-security.html)?  I've added ES_HOST and ES_SHIELD (amongst other listed solutions such as defining ep_request_headers), but I haven't seen any other posts or docs that refer how to add the private key so that the elasticpress can handle document indexing through elastic.co (https://www.elastic.co/guide/en/app-search/7.15/indexing-documents-guide.html)and the link above is 404 (and I don't see an obvious replacement on the docs page http://10up.github.io/ElasticPress/).

**Comment by alesub** [comment]
@brandwaffle the "tutorial-security" doc is nowhere to be found, where has this information been moved? I'm also trying to authenticate to the server we're using (elastic.co). Thanks!

**Comment by rtwilliams5** [comment]
@alesub I was able to Wp to index to elastic.co with ```define( 'EP_HOST', 'https://<<server>>.es.eastus2.azure.elastic-cloud.com:443' );
define( 'ES_SHIELD', 'elastic:<<credentials>>);```

**Comment by alesub** [comment]
amazing, thanks for the details @rtwilliams5 !!
