### ISSUE TITLE
Add commenting or editing documentation

### ISSUE THREAD

**Issue by shaneonabike** [10up/ElasticPress#1986]
Hey there,

I really love ElasticPress and I also really appreciate the support that has been given through Github. I was thinking that perhaps if we were able to add more comments into the API documentation and/or modify it you might have less tickets being opened in Github. I would love to drop a few examples into the actual sections of the API in order to make it clearer for folks, because presently when I read the docs and API it wasn't 100% clear right out of the box.

What do you think?

**Comment by felipeelia** [comment]
Hi @shaneonabike!

First of all, sorry for the late response here.

That would be awesome! Probably you already know but I'll share it here for future reference anyway:

Currently, we keep the plugin docs via GitHub Pages: http://10up.github.io/ElasticPress/. That documentation is maintained in the [docs](https://github.com/10up/ElasticPress/tree/develop/docs) folder of this same repo. Feel free to open a Pull Request adding whatever information you think would be useful :)

Also worth noting we have a [Knowledge base on ElasticPress.io](https://elasticpress.zendesk.com/hc/en-us) and we try to keep things on a "semi-sync": not duplicating content but we can point users from one place to the other.

I'll go ahead and close the issue here but I hope to see a PR from you as soon as possible. Thanks again!
