### ISSUE TITLE
What to do when you have too many posts and the indexing fails

### ISSUE THREAD

**Issue by aaronjpitts** [10up/ElasticPress#1994]
I have 13,762 posts now to index in ES. I am already using `ep_prepare_meta_data` to limit the meta data stored for each record. Now when I index, it is always failing to index and will only index between 300-2000 posts. I believe this is because the data store is too big now. I am running ES on a single node. Could you guys please suggest how to resolve this? Would creating more nodes help resolve this?

**Comment by brandwaffle** [comment]
@aaronjpitts are you getting any error messages from your ES server? One node is not ideal from a reliability standpoint but there's no reason it should fail with that few posts.

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it.

For cases like these, it can be useful to run the following WP-CLI command and check the output:

wp elasticpress index --setup --show-errors

If after a while you get a timeout error, [this article](https://elasticpress.zendesk.com/hc/en-us/articles/360051876131-ElasticPress-hangs-on-indexing-and-or-fails-with-error-Error-cURL-error-28-Operation-timed-out-after-milliseconds-) may help you with it.

If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment.

Thanks!

**Comment by aaronjpitts** [comment]
Sorry for not getting back. It appears the issue came from lack of disk space on the VM.
