### ISSUE TITLE
There is a problem with connecting to your Elasticsearch host. ElasticPress can try your host again, or you may need to change your settings. Response error: cURL error 7: Failed to connect to X.X.X.X port 9200: Connection refused

### ISSUE THREAD

**Issue by vedagames** [10up/ElasticPress#2012]
**Describe the bug**
Hi!
Its giving me error called
There is a problem with connecting to your Elasticsearch host. ElasticPress can try your host again, or you may need to change your settings. Response error: cURL error 7: Failed to connect to X.X.X.X port 9200: Connection refused.

I have checked that elasticsearch working fine when I try to check via browser or via curl in cmd. Its available publically and no connection refused from my server. I do not know why elasticpress say that connection refused.

Thanks!

**Comment by brandwaffle** [comment]
Hi @vedagames,

Thanks for submitting this issue. Since this support forum is focused on the ElasticPress plugin, we're unable to provide additional support for self-hosted Elasticsearch instances beyond confirming that all plugin functionality works properly with a standard Elasticsearch cluster running the latest supported version of Elasticsearch that ElasticPress supports.

If you would like to continue self-supporting and troubleshooting, we recommend installing the [Debug Bar](https://wordpress.org/plugins/debug-bar/) and [Debug Bar ElasticPress](https://wordpress.org/plugins/debug-bar-elasticpress/) plugins. The latter will enable you to view all WP and JSON query bodies, as well as headers and query results. Common issues connecting to self-hosted Elasticsearch clusters include authentication problems as well as firewall problems, and these plugins can help detect and resolve them.

If you would prefer a more immediate solution, we offer the hosted [ElasticPress.io](https://elasticpress.io) service, which is designed to be fully compatible with ElasticPress. This service provides a 30-second setup for your ElasticPress integration, as well as a custom SaaS layer that assists with search features like Autosuggest. We also provide consulting services for both custom ElasticPress code as well as self-hosted Elasticsearch instances. You can learn more about these services on our [Consulting](https://www.elasticpress.io/elasticpress-consulting/) page.

**Comment by felipeelia** [comment]
As we didn't have any movement in the ticket for the last week, I'm going ahead and closing the ticket. Feel free to open a new one if needed :)
