### ISSUE TITLE
Autosuggest not working Chrome Console keeps showing Mixed Content Error.

### ISSUE THREAD

**Issue by Warns** [10up/ElasticPress#2016]
**Describe your question**

I have ES running on an Ubuntu server hosted on Digitalocean. The indexing and search working properly but autosuggest keeps giving the following error.

```sh
Mixed Content: The page at 'https://mywebsite.com/' was loaded over HTTPS, but requested an insecure resource 'http://public-ip:9200/'. This request has been blocked; the content must be served over HTTPS.
```

My configs:
elasticsearch.yml
![image](https://user-images.githubusercontent.com/4021052/103477836-846b6100-4dd3-11eb-8bdc-50d6cd625de6.png)

I can curl from outside of the server using http://public-ip:9200/ 

How do I solve this issue since my website is running on HTTPS. 

Another question; isn't exposing the public IP pretty dangerous and people can probably query anything or delete indexes since the public IP is required in the ElasticPress settings?

**Comment by brandwaffle** [comment]
@Warns since you're running your site via HTTPS you will need to also make your Elasticsearch endpoint connect via HTTPS. This will eliminate the mixed content warning. You are correct that directly exposing your endpoint has significant risks, which is why we offer our ElasticPress.io service that includes a secure autosuggest endpoint. If you are unable to sign up for our service, you can create a custom proxy on your web server and route through that or otherwise secure your Elasticsearch endpoint.
