### ISSUE TITLE
Exclude content from index

### ISSUE THREAD

**Issue by rickwschneider7** [10up/ElasticPress#2017]
Hello,

Is there a way to exclude certain posts from the index based on custom fields or other criteria? This seems like it should be basic functionality, but I don’t see this feature anywhere in the plugin interface.  Strangely, I can't find anything on the forum here, or on the greater www about it, either.  

Thanks in advance,
Rick

**Comment by felipeelia** [comment]
Hey @rickwschneider7 ,

Sorry for the late response here. There is not an easy way to do that because we'll have to take into account the different ways a post can be indexed (on creation, save, or bulk index, for example). I'll try to put a snippet together in the next few days and share it with you here, okay? If you had the chance to achieve that already, please let us know and, if possible, share it here :) 

Thanks!

**Comment by felipeelia** [comment]
Hi @rickwschneider7,

Here is a snippet that will prevent a post with a metafield called `should_skip_index` set to `1` from being indexed:

```
add_filter(
	'ep_post_sync_kill',
	function( $skip, $post_id ) {
		$should_skip_index = get_post_meta( $post_id, 'should_skip_index', true );
		if ( $should_skip_index ) {
			\ElasticPress\Indexables::factory()->get( 'post' )->delete( $post_id, false );
			return true;
		}
		return $skip;
	},
	10,
	2
);

add_filter(
	'ep_post_query_db_args',
	function ( $args ) {
		$meta_query = ( isset( $args['meta_query'] ) ) ? $args['meta_query'] : [];

		$meta_query[] = [
			'relation' => 'OR',
			[
				'key'     => 'should_skip_index',
				'value'   => 1,
				'compare' => '!=',
			],
			[
				'key'     => 'should_skip_index',
				'compare' => 'NOT EXISTS',
			],
		];

		$args['meta_query'] = $meta_query;

		return $args;
	}
);
```

Thanks!
