### ISSUE TITLE
How to make ElasticPress work with Ajax requests

### ISSUE THREAD

**Issue by corentin-branquet** [10up/ElasticPress#2054]
Hi  !

I'm using ElasticPress on one of my project.

I want to speed up my Ajax Requests (I use wp_query)  , but I don't know how to do that even though I read your doc.
I installed the plugin, put my local host and sync my index. Do I missing any steps ?

I also installed debug bar for ElasticPress and when I trigger that WP Query, No query has been fouund in the logs

Thanks for your help !

**Comment by brandwaffle** [comment]
Hi @corentin-branquet you just need to pass an additional WP_Query parameter of **ep_integrate => true** and that will route the query through ElasticPress. Keep in mind Ajax queries won't necessarily show up in the Debug Bar, so you may want to manually debug to ensure the results are hitting Elasticsearch.

**Comment by corentin-branquet** [comment]
Thanks for your reply ! 

Is it working with this kind of query : `get_terms(...);` instead of `WP_query` ?

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
