### ISSUE TITLE
search_fields filter does not work later on due to Weighting

### ISSUE THREAD

**Issue by oscarssanchez** [10up/ElasticPress#2064]
**Describe the bug**

It seems like search_fields does its job but later on when we are formatting the args with weighting:  https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Weighting.php#L26 they are ignored and deleted. 

**Steps to Reproduce**

1. Use filter: 
```
function wpes_search_add_meta($search_fields, $args) {
    $search_fields[] = "meta.test";
    return $search_fields;
}
add_filter( 'ep_search_fields', 'wpes_search_add_meta', 9999, 2 );
```
2.- Do a search
3.- Check es query and see the field is not working
4.- Remove https://github.com/10up/ElasticPress/blob/develop/includes/classes/Feature/Search/Weighting.php#L26 for a moment and reload
5.- Field is appearing in es query

**Expected behavior**

Weighting should not wipe out previously set fields. 

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by felipeelia** [comment]
I guess we had a similar conversation in the past and IIRC we got to the conclusion that if the developer is working with `search_fields`, then probably the weighting engine should really be ignored.

**Comment by felipeelia** [comment]
Line being used by `wp-content/plugins/elasticpress/includes/classes/Indexable/Post/Post.php`:

`$search_fields = apply_filters( 'ep_search_fields', $search_fields, $args );`

And on `wp-content/plugins/elasticpress/includes/classes/Feature/Search/Weighting.php`:

```
public function do_weighting( $formatted_args, $args ) {
	if ( isset( $args['search_fields'] ) && ! empty( $args['search_fields'] ) ) {
		return $formatted_args;
	}
```

The problem seems to be we are checking `$args` but that was not changed by the `ep_search_fields` filter.

**Comment by mckdemps** [comment]
@tott Based on your research yesterday, can you recommend changes to filters here?

**Comment by tott** [comment]
I definitely ran into the same thing and we're currently considering a couple of filters to better help customization and ensuring a clearer workflow.

**Comment by felipeelia** [comment]
Looking deeper into the problem, the solution is not as simple as adding `$args['search_fields'] = $search_fields` because we set a default value to the `$search_fields` variable a couple of lines before.
Probably, we should document that the `ep_search_fields` should be used only when the weighting engine is not used. For people using the weighting engine, the `ep_weighting_configuration_for_search` filter will work as expected.
