### ISSUE TITLE
Empty search string causes tax_query to break

### ISSUE THREAD

**Issue by psorensen** [10up/ElasticPress#209]
I can't seem to find any way around this. I've created a post type specific search by creating `{my-post-type}-archive.php` and removing `search.php`, thus defaulting all general searches to `index.php` (This may be irrelevant)

When I visit `?post_type={my-post-type}&s=&{taxonomy}={term}`, I get all results for that post_type. When I remove the `s=`, the taxonomy rules apply. I've tried using `unset($_GET['s'])` if `empty($_GET['s'])`, and even though `var_dump` shows that `$_GET['s']` is set to `NULL`, it still retrieves all results as though `$_GET['s']` is set to `''`.

**Comment by mikaelmattsson** [comment]
The problem is probably that wordpress has allready looked at the `$_GET['s']` to determine if the main query should be a search or not. So the query object has already been made before you access the get variable. Unseting the the get variable should have no effect.
I'm not sure what you are trying to do here so i can't help you any further.

**Comment by psorensen** [comment]
The problem is, with EP **deactivated**:
`//sitename.com/?post_type={post_type}&s=&{taxonomy-name}={term}`
returns all posts of that post type with the taxonomy term. With EP **active**, it ignores the taxonomy request and returns all posts of that post type. If I remove the `s` query var, it does not ignore the taxonomy parameter.

In other words, using a faceted search form, if the user selects certain taxonomy terms, but leaves the search term blank, they still get all posts, without the results being narrowed down by the selected terms, all because the `s=` is present in the url.

**Comment by psorensen** [comment]
In the meantime, I'm using JS to change the form (sets name of search field to '') on submit if the input is empty.

**Comment by mikaelmattsson** [comment]
Just to clairify, that if you remove `s=` then ElasticPress will ignore the query because of `EP_API::elasticpress_enabled`
This seems to be an unsupported feature then. The plugin support the tax_query query argument but not the taxonomy query argument.
The WP_Query object will sometimes include the query_var `taxonomy` and `term` or `term_id`

I'll share the code i use

    if (!empty($query_vars['taxonomy'])) {
        if (!empty($query_vars['term'])) {
            $es_query->where('terms.' . $query_vars['taxonomy'] . '.slug', $query_vars['term'], 1);
        } elseif ($query_vars['term_id']) {
            $es_query->where('terms.' . $query_vars['taxonomy'] . '.term_id', $query_vars['term_id'], 1);
        }
    }

**Comment by mikaelmattsson** [comment]
The title of this issue is a bit misleading. An empty search string will not cause tax_query to break. It will result in EP not doing anything and the query will run against MySQL like it normally would.

**Comment by AaronHolbrook** [comment]
This is more of a limitation with WordPress's `is_search` - when the `s` parameter is blank or not set, WordPress says that it is not a search - which is what ElasticPress was using to know when and what to override.

Because of that, we've added the parameter of `ep_integrate` to our check - so if `is_search` is not true, then it will check to see if `ep_integrate` was passed in the query arguments, if it was then we continue to  build and override WP_Query by setting the `match_all` DSL of Elasticsearch: 

https://github.com/10up/ElasticPress/blob/master/classes/class-ep-api.php#L993
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-match-all-query.html

**Comment by psorensen** [comment]
Thanks for your input Aaron and Mikael. This was an error on my part. In my project, I'm using `pre_get_posts` to search based on `$_GET` parameters. I was sending slugs to a `tax_query`, but not setting the `field` parameter to `slug`, thus the slugs were not registered as found.

In the end EP is working as described and my problem was due to an error. Regardless, your efforts were helpful in further understanding the way EP works. Thanks!

**Comment by AaronHolbrook** [comment]
Good to hear - thanks for following up @psorensen !

**Comment by janicak** [comment]
I'd like to utilize Elasticpress when certain URL parameters are present, such as `post_type` and `custom_parameter` - with or without `s` also being present.

Per @psorensen and @AaronHolbrook, I tried altering the query via `pre_get_posts`, setting `is_search=true` and `ep_integrate=true`, though it looks like `ep_integrate_search_queries` is being called before `pre_get_posts`, so I wonder if there isn't a better hook for this.

Any insights from your experience would be much appreciated!

**Comment by AaronHolbrook** [comment]
@janicak all you should need during the `pre_get_posts` hook is to append the `ep_integrate = true` paramater, that should do the trick.

**Comment by janicak** [comment]
@AaronHolbrook, thanks for getting back! It looks like this was a problem of my own making, as I had previously used `ep_search_args` to limit the post types for general queries, and adding another term filter for post_type.raw to the ES query was returning an error.

**Comment by AaronHolbrook** [comment]
Cool - glad you got it sorted!
