### ISSUE TITLE
Not all posts are indexed

### ISSUE THREAD

**Issue by AlexInconver** [10up/ElasticPress#2118]
I sync and see the number of posts to sync - 4737
https://monosnap.com/file/iUVxfoeQAFBoFBHoMjL9DX9LjF10oA
I go to look at the index and see this number of posts - 2548
https://monosnap.com/file/036m90bBSbUf38e7SzeYicEZynWER8

f.e. I check the search on the site and see that only one TV is displayed instead of 87

How to fix it? thanks!

**Comment by felipeelia** [comment]
Hi @AlexInconver,

First of all, you'll need to debug why those posts are not being indexed. To help you with that, you can index your content via WP-CLI with the command:

`wp elasticpress index --setup --show-errors`

That can give you a hint about what is going on. Quite often, the error is related to the number of meta fields present on some posts. To know more about that, you can read our [troubleshooting article](https://elasticpress.zendesk.com/hc/en-us/articles/360051401212-I-get-the-error-Limit-of-total-fields-in-index-has-been-exceeded-).

I'll keep the issue open for a while to check if you managed to fix the problem. If you get it fixed and can come back here to share the problem and the solution, that would be great!

Thanks

**Comment by AlexInconver** [comment]
Thank you! You were right, but I could not solve the problem. I added the following code to functions.php of my theme but I still get the error that there are too many meta fields.

https://monosnap.com/file/hOFPELvtBXasn0GcsyGgGpe69Ain37

**Comment by felipeelia** [comment]
Hi @AlexInconver ,

So, basically, we would need to:
1. Make sure your PHP code is being executed. Can you please do that if you didn't before? An error_log() call with WP_DEBUG and WP_DEBUG_LOG enabled, for example.
2. Give a look at your mapping. Are you by any chance using ElasticPress.io? If that is the case, let us know and we can help through our support. Otherwise, you can get it by making a GET request to `<index>/_mapping` or using the `\ElasticPress\Elasticsearch::factory()->get_mapping( <your_index_name> );` method.

Thanks

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
