### ISSUE TITLE
QUESTION: Only index certain pages

### ISSUE THREAD

**Issue by BWBama85** [10up/ElasticPress#2169]
Hi,

I am looking for a way to only index certain pages and all normal posts (post type = post)

For example:

I want to only include the pages that are children of the following ids:

71217,71218,71219,71220,71221

Those are just a few, I have a few more, but you get the idea.

How would I:

1) Only index these when I run the sync command
2) Index these when a new page is created under the parent

**Comment by felipeelia** [comment]
Hi @BWBama85 ,

That is an interesting use case. You'd need something similar to what we've put together for [this other issue](https://github.com/10up/ElasticPress/issues/2017#issuecomment-771849953) but instead of excluding IDs, you'd be using only those few you have. Does that already point you in a good direction or would you need a full snippet?

Thanks

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
