### ISSUE TITLE
QUESTION: Page loading slow when there are a lot of results

### ISSUE THREAD

**Issue by Sinns** [10up/ElasticPress#2175]
**Describe your question**

Hello everyone
I have a webshop with over 100'000 products and I use ElasticPress to speed up my search queries. This works great when the query results in less than 500 products. But when I search for a term where there are a lot of products, ElasticPress will find at most 10000 products and needs ca. 1.3 seconds to do so. What me bothers is, that the website itself needs around 40 seconds to load! 
I really don't know how I should approach the problem or if it is even a ElasticPress problem. 
Maybe there is somebody who can help me. Please see my images for further information. Thanks a lot. I wish you a nice week!

P.S. If somebody from the dev team would like to debug it directly on my site, I would also be willing to pay you to do so. 

![Screenshot from 2021-04-18 18-25-15](https://user-images.githubusercontent.com/10309173/115153449-3d4d6700-a076-11eb-9d72-939c9fe20c64.png)
![Screenshot from 2021-04-18 18-28-42](https://user-images.githubusercontent.com/10309173/115153450-3de5fd80-a076-11eb-97ac-e72a967b88fc.png)
![Screenshot from 2021-04-18 18-52-23](https://user-images.githubusercontent.com/10309173/115153628-560a4c80-a077-11eb-8e7f-a302471a514d.png)

**Comment by oscarssanchez** [comment]
Hi @Sinns , this could probably be because of a limit Elasticsearch has of 10,000 results per page: https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#:~:text=By%20default%2C%20you%20cannot%20use,use%20the%20search_after%20parameter%20instead.

Regarding the slowness you are experiencing, we believe this could not necessarily be the Elastic query and can definitely help out troubleshooting if you would like us to. We could do a call meeting if you want, could you please fill this form? https://www.elasticpress.io/request-a-demo/#contact-form-title and we will get back to you 

Thanks!

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
