### ISSUE TITLE
Versioning built assets

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2182]
Right now, every time a PR touches a JavaScript file, the assets built (transpiled and minified) are being sent with it. That causes a problem if we have 2 different PRs changing JS files: at the moment we merge the first one, the other one will have a conflict and won't be mergeable anymore.

Other big plugins don't version their minified files. Example:
- WooCommerce: [Repo](https://github.com/woocommerce/woocommerce/tree/trunk/assets/css) and [WP.org](https://plugins.trac.wordpress.org/browser/woocommerce/#trunk/assets/css)
- Yoast: Repo: [Repo](https://github.com/Yoast/wordpress-seo/tree/trunk/css) and [WP.org](https://github.com/Yoast/wordpress-seo/tree/trunk/css)

## Things to take into account

* Currently anyone can come to the GH repo and download the code zip and it will work right away. That won't be true if they need to run an npm command to have the minified files in place.
* Same for downloading a release but that could be mitigated with the first solution below.

## Possible solutions

1. We could remove the minified files from the repo and build them during the release process. WooCommerce has an action that builds the zip attached to the release [here](https://github.com/woocommerce/action-build/blob/trunk/entrypoint.sh#L27) as an example.
2. Perhaps we could minify the files after merging a PR, so the PR itself doesn't need to contain the JS files?

**Comment by jeffpaul** [comment]
FYI we handle this by building to `stable` and then releasing targeting that branch for [Distributor](https://github.com/10up/distributor/blob/develop/.github/workflows/build-stable.yml), [ClassifAI](https://github.com/10up/classifai/blob/develop/.github/workflows/release.yml), and [Sophi](https://github.com/globeandmail/sophi-for-wordpress/blob/develop/.github/workflows/release.yml).

**Comment by jeffpaul** [comment]
@tlovett1 are you wildly opinionated on how this could/should be handled?  Perhaps a quick chat in EP meeting next week to get to an optimal approach for the team to take action on?

**Comment by jeffpaul** [comment]
Brainstorming steps should the decision be to shift to building a stable release version:

- [ ] Add note to next release notes, in readme.txt, in README.md, in Changelog section of readme.txt, and in CHANGELOG.md about the pending change to pull from `stable` instead of `master` (probably also worth considering renaming `master` to `trunk` at this point) with the next major release
- [ ] Repeat same notice for additional minor releases leading up to major release that introduces this change
- [ ] Include message in major release with change in stable build branch and subsequent minors until we hit another major release (after this point anyone updating has had sufficient chance to see the notice and update accordingly)
- [ ] If decided to rename `master` to `trunk`, updating references accordingly across the codebase from `master` to `trunk`
- [ ] Add notes to readme.txt and README.md about how to properly build a non-`stable` branch for testing (likely at https://10up.github.io/ElasticPress/tutorial-install.html and/or https://10up.github.io/ElasticPress/tutorial-development.html)
- [ ] Update release process to build into a `stable` branch like [Distributor](https://github.com/10up/distributor/blob/develop/.github/workflows/build-stable.yml) and [ClassifAI](https://github.com/10up/classifai/blob/develop/.github/workflows/release.yml)
- [ ] Update release instructions to tag a release off the `stable` branch and not `master`/`trunk`

I _think_ that would cover it, but worth iterating on that list until folks feel it includes all necessary steps.

**Comment by mckdemps** [comment]
- [ ] Also worth calling out this change in future ElasticPress blog posts.

**Comment by felipeelia** [comment]
Closed by #2486
