### ISSUE TITLE
How to use mappings

### ISSUE THREAD

**Issue by esaheiskanen** [10up/ElasticPress#219]
Hi! 

Could you show simple example how to use mappings on setup? I have Advanced Custom Field that is number type but it's interpreted as string in elastic search.

Thank for great plugin!

**Comment by AaronHolbrook** [comment]
Hi @esaheiskanen,
You will need to filter the initial mapping that happens during setup: https://github.com/10up/ElasticPress/blob/df56933d7a041eb5567a095e46e6909aa2211a1f/classes/class-ep-api.php#L520

You can use the pre-existing mapping as a guide, but you'll need to specify your field directly (instead of allowing the dynamic mapping to map every post meta field). Something like
```
'post_meta.acf-number-field' => array(
  'type' => 'integer',
);```

Reference: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-core-types.html

**Comment by esaheiskanen** [comment]
Thank you for answer. Where i should put this? Cli parameter of modify plugin source?

**Comment by esaheiskanen** [comment]
*or (mobile client doesnt let me edit)

**Comment by AaronHolbrook** [comment]
As I said and linked to - you should filter the `ep_config_mapping` filter.

Use WordPress's Action/Filter API: http://codex.wordpress.org/Function_Reference/add_filter
