### ISSUE TITLE
BUG: Facet Filter

### ISSUE THREAD

**Issue by shmaltz** [10up/ElasticPress#2201]
I set up a few facet filters to filter product attributes, however they seem to be returning the wrong results. I filter for a certain manufacturer, and it displays many different manufacturers, including that filter. This happens when I'm on a Product Category page, and I select one attribute filter.

I have the facets set to "Show all content tagged to **any** selected terms".

If I were to set the facets to "Show all content tagged to **all** selected terms", then the facets will work properly, however I will not be able to "grow" the filtered content by selecting more than one option from a single facet.

One more issue, e.g. If I am on the 50th paginated page of a category, and then filter by an attribute that will only have 5 pages of products, I will get a 404, because the filter doesn't clear the pagination.

Any workarounds to these issues?

Thank you!

**Comment by felipeelia** [comment]
Hi @shmaltz ,

Can you please give us some real examples so we can replicate the issue you are having with the any/all option?

I can replicate the pagination problem, though. It was partially fixed on #1347, but instead of applying it only for `is_post_type_archive()`, we probably should remove [this if](https://github.com/10up/ElasticPress/blob/3.5.6/includes/classes/Feature/Facets/Facets.php#L426) and always use the code inside of it.

**Comment by oscarssanchez** [comment]
I have tested removing the if clause, however it messed the original fix, while fixing the current issue. Definitely a bug but might need a more in depth look

**Comment by felipeelia** [comment]
@oscarssanchez , for a client using custom facets I'm using:

```
public function build_query_url( $filters ) {
	...

	// Remove the pagination.
	$pagination = strpos( $request_uri['path'], '/page' );
	if ( false !== $pagination ) {
		$request_uri['path'] = substr( $request_uri['path'], 0, $pagination );
	}

	return trailingslashit( $request_uri['path'] ) . '?' . http_build_query( $query_params );
}
```

Did you already try something like that?
