### ISSUE TITLE
Elastic Press works with which version of Amazon Elastic Search

### ISSUE THREAD

**Issue by peeyooshk** [10up/ElasticPress#2274]
We tried using the Amazon Elastic search version 7.10 and the moment we sync our products, it tries to sync and then throws error not able to sync.

**Comment by brandwaffle** [comment]
Hi @peeyooshk,

We don't test ElasticPress with distributions of Elasticsearch except those from Elastic and unfortunately we're not able to help troubleshoot connectivity issues or server-side problems in this forum.

You will need to check the error and debug the issue to determine the cause of the problem. If there are changes you can make to improve compatibility with AWS' Elasticsearch distro, we would be happy to review any pull requests.

**Comment by peeyooshk** [comment]
Could you please share as to where i can find the log files for elastic press sync requests?

Sorry i am not a developer so I would not be able to contribute on that front but ofcourse i can help in testing.

**Comment by brandwaffle** [comment]
Hi @peeyooshk you can find documentation about troubleshooting here https://elasticpress.zendesk.com/hc/en-us/sections/360010868652-Troubleshooting

This article in particular explains how to install debugging tools https://elasticpress.zendesk.com/hc/en-us/articles/360050720172-Using-the-Debug-Bar-ElasticPress-Plugin

For bulk indexing requests (aka sync) you will need to use WP-CLI to troubleshoot, as those requests are not visible in the Debug Bar. You can learn more about WP-CLI commands for ElasticPress here http://10up.github.io/ElasticPress/tutorial-wp-cli.html. The `--show-bulk-errors` flag is the one you'll need to pass to the indexing command in order to view those sync errors.
