### ISSUE TITLE
BUG: Heavy CPU Usage.

### ISSUE THREAD

**Issue by rajat315315** [10up/ElasticPress#2307]
**Describe the bug**

It uses lot of CPU even on a 24 CPU machine. (See attached image.)

**Steps to Reproduce**

Normal usage

**Expected behavior**

Consumption should be less.

**Screenshots**

![WhatsApp Image 2021-08-13 at 19 03 13](https://user-images.githubusercontent.com/15379278/129375227-4c44c12b-a122-467c-b8c2-4e5b5bc23c7c.jpeg)

**Environment information**
 - Device: 
 - OS:  Linux
 - Browser and version: 
 - WordPress version:  5.8
 
 - ElasticPress version:  Elasticpress.io (Don't know about the version)
 - Elasticsearch version:  Elasticpress.io (Don't know about the version)
 - Where do you host your Elasticsearch server?  Elasticpress.io (Don't know about the version)
 - What ElasticPress features do you have currently active?  Pls see screenshot.
 - 
![elasticpress_cluster_health](https://user-images.githubusercontent.com/15379278/129375661-05fba05f-aa0b-42a5-baa1-40026bb24765.png)

 - Plugins and version:  latest
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary> 
   
   </details>

**Comment by rajat315315** [comment]
any update?

**Comment by dustinrue** [comment]
What you're seeing here actually looks correct for the number of calls you are making into the service. If you click on the external call item itself you should then see what the average response time is for your search calls. Since you are an elasticpress.io customer I encourage you to open a support request from your account page on https://www.elasticpress.io/ so we can assist further.
