### ISSUE TITLE
Plugin Compatibility: YITH WooCommerce Ajax Product Filters

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2337]
**Is your enhancement related to a problem? Please describe.**

Although ElasticPress works with YITH WooCommerce Ajax Product Filters, it integrates with it in a way that several different requests are fired to ES in each page load.

**Describe the solution you'd like**

These queries should be handled by MySQL, instead of requesting a (possibly) external server.

**Comment by Rahmon** [comment]
The YITH WooCommerce Ajax Product Filters sends additional requests to build the filter and show how many products are in each attribute.

We can prevent half of the requests by adding the snippet below:

```php
/**
 * Preventing ElasticPress to be used
 *
 * @param array $unfiltered_args filters used by YITH WooCommerce Ajax Product Filter plugin
 * @return array
 */
function ep_prevent_using_ep_on_yith_wcan_unfiltered_args( $unfiltered_args ) {
	$unfiltered_args['ep_integrate'] = false;

	return $unfiltered_args;
}

add_filter( 'yith_wcan_unfiltered_args', 'ep_prevent_using_ep_on_yith_wcan_unfiltered_args' );
```
This snippet tells the plugin to not use ElasticPress. Unfortunately, the plugin doesn't provide a filter for another request used to build the filter.

Since this is a workaround, a better approach would be using the main request to retrieve all the data needed by the plugin using aggregations.
