### ISSUE TITLE
Query Response Code: HTTP 400 When searching

### ISSUE THREAD

**Issue by herng77** [10up/ElasticPress#2381]
Tried to search the Woocommerce Search bar and it is returning 400 whenever I tried to search something, here is the JSON request:

`curl -XPOST -H 'Content-Type: application/json' -d '{"from":0,"size":4999995,"sort":[{"_score":{"order":"desc"}}],"query":{"bool":{"should":[{"bool":{"must":[{"bool":{"should":[{"multi_match":{"query":"asdfasdfasdf","type":"phrase","fields":["post_title^1","terms.ep_custom_result.name^9999"],"boost":3}},{"multi_match":{"query":"asdfasdfasdf","fields":["post_title^1","terms.ep_custom_result.name^9999","post_title.suggest^1","term_suggest^9998"],"type":"phrase","slop":5}}]}}],"filter":[{"match":{"post_type.raw":"product"}}]}}]}},"post_filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"terms.product_visibility.term_taxonomy_id":[18]}}]}},{"terms":{"post_type.raw":["product"]}},{"terms":{"post_status":["publish","ywcars-new","ywcars-processing","ywcars-on-hold","ywcars-approved","ywcars-rejected","wc-verifying","wc-iden-verification","wc-incorrect-details","wc-restock","wc-sending"]}}]}}}' 'http://127.0.0.1:9200/asd-post-1/_search'`

![image](https://user-images.githubusercontent.com/33309010/135660943-ce50db83-df7d-40bb-92dc-b314ca3d9446.png)

Tried to use Synonym, autosuggest it doesn't seem to work as well even though my search bar contains:

`<input type="search" id="woocommerce-product-search-field-0" class="search-field" placeholder="Search products…" value="" name="s">`

Any chance on how can I fix this issue? I also see this when I go to the ElasticPress settings:

`It looks like one or more of your indices are running on a single node. While this won't prevent you from using ElasticPress, depending on your site's specific needs this can represent a performance issue. Please check the Index Health page where you can check the health of all of your indices.`

**Comment by mckdemps** [comment]
@herng77 Our ability to provide support in this forum is limited to issues with the ElasticPress plugin. For support with custom Elasticsearch servers, we provide custom consulting: https://www.elasticpress.io/elasticpress-consulting/

If you'd like to debug further on your own, we recommend installing the Debug Bar and Debug Bar ElasticPress plugins on your site, which will give you detailed error messages from your Elasticsearch server. 

In order to prevent the single node warning, you must be running Elasticsearch on more than one node.
