### ISSUE TITLE
Show ElasticPress in Wordpress Admin menu

### ISSUE THREAD

**Issue by zsheaib** [10up/ElasticPress#2396]
I am using altis and have already the the plugin in the vendor directory, but I can't see it in the Wordpress dashboard!

How to enable it in the UI?

**Comment by roborourke** [comment]
Thanks @mckdemps! We are exploring the best way to add ElasticPress admin UI components back in, it’s hidden because the features are a little tied in to the infrastructure. EP has added so many cool new features since we first included it though!

The best repo for issues is https://github.com/humanmade/altis-enhanced-search/issues or you can create a support request @zsheaib
