### ISSUE TITLE
QUESTION: How do I search for term pages within the autosuggest?

### ISSUE THREAD

**Issue by stijlbreuk** [10up/ElasticPress#2415]
Hi,

We are creating a multilingual (WPML) website, where we implemented ElasticSearch. Our hosting provider, has installed a ElasticSearch service for this website on the server and we are now able to easily leverage ElasticPress. The search works with the implementation of the search field. 

The plugin allows us to set the manage the Search field settings:
![Screenshot 2021-10-18 at 16 10 48](https://user-images.githubusercontent.com/43994518/137748376-daeee849-b80e-4f98-8882-5560c16883f1.png)

This works and it if we search for 'Laptops' it will retrieve stores that either have this in their title, or have the 'Store category' term of `Laptops` assigned.

Great! But, what we would like to achieve is to ALSO find all term pages that hit in the word 'Laptops' within this autosuggest.

How would could we achieve this?

**Comment by felipeelia** [comment]
As we didn’t have any movement in this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!

**Comment by felipeelia** [comment]
Reopened this as requested by @stijlbreuk via email.

**Comment by stijlbreuk** [comment]
Thanks for you answer. Due to a short holiday, I wasn't able to reply anytime sooner. 

So what we are trying to achieve is the following. In this website, we have the type `stores` en the taxonomy `store_categories`. Stores can have multiple categories attached to them.

Examples of store categories:
![Screenshot 2021-11-01 at 14 18 12](https://user-images.githubusercontent.com/43994518/139678079-050f8b26-6a76-4974-98fe-403195564c10.png)

When we would search for "radio",  in the ElasticPress autosuggest results I would like to retrieve:
- Stores that match the search term in the title (this is working)
- Stores that have the `radios` term attached (this is working)
- Store categories archive url's, in this case `Radios` (this is **not working**)

See example url: https://payin3.eu/en/webshops-with-in3/electronics/audio/radios/

How could we also retrieve the relevant term archive pages?

**Comment by felipeelia** [comment]
Hi @stijlbreuk! Although that is doable, it will require some custom code. To retrieve archive URLs you'll need to activate the Terms feature index all your terms, and then fire a different request to your terms index, as requesting your posts index won't bring what you need there.

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. Thanks!

**Comment by JiveDig** [comment]
Sorry to resurrect this one, but it's exactly what we're wanting to do as well.

Is it possible to have term archives (category/tag/custom taxo) show up combined within the posts in search results? I understand it may have to merge queries, but seems very relevant. @stijlbreuk's example is a great use-case.  If someone searches **Radios** they should see results for the Radios term archive as well as any posts/products with that keyword.

Can you offer any pointers or headstarts if this is possible? Thanks :)

**Comment by oscarssanchez** [comment]
Hi @JiveDig ,

Yes that's totally doable, you'll need to account for term suggesting in the mapping, indexing term suggestions, formatting the args that are being sent ås the request, and create a new autosuggest JS file that handles all of this. Unfortunately this kind of thing falls out of the normal scope of this plugin since it is a completely different feature than normal autosuggest, but we have worked with clients achieve similar requirements. 

If you are interested we'd be happy to help out with consulting over at https://www.elasticpress.io/elasticpress-consulting/

**Comment by JiveDig** [comment]
Okay cool, thanks for the reply. I don't actually need this via autosuggest though, I forgot that's what the OP was about. I need it for regular search results, as hijacked by EP. Hoping I can keep it all in PHP.
