### ISSUE TITLE
QUESTION: Use elasticpress to improve order admin search in Woocommerce

### ISSUE THREAD

**Issue by bakerGS** [10up/ElasticPress#2428]
Hi,

We are trying to improve just the admin search for orders in Woocommerce, using ElasticSearch and ElasticPress.

We configured the server and it's works well. We indexed the post_type shop_order with the filter ep_indexable_post_types and the status with ep_indexable_post_status. We thinks all is indexed correctly.

Also, we try to add on filter pre_get_posts the ep_integrate = true on query, but the order search, don't use elasticpress to make the search.

Do we need another step?

Thanks for your help.

**Comment by brandwaffle** [comment]
@bakerGS in order to perform admin-side Order searches you need to enable the Protected Content feature. This will enable order search in the WP Dashboard. Please keep in mind this requires you index your order data (which likely contains personal information) into your Elasticsearch endpoint, so please ensure that endpoint is secure.
