### ISSUE TITLE
WordPress regularly disconnects from ElasticSearch, but always reconnects when I click try again

### ISSUE THREAD

**Issue by ckeeney** [10up/ElasticPress#2430]
**Describe the bug**
ElasticPress frequently (several times per day) becomes disconnected from my ElasticSearch instance.  When this happens, requests to `wp-json` that include a `search` query parameter return an empty list.  Also, the `.../related` endpoint I added always returns an empty list.

Each time this happens I can click "Try again" next to the "There is a problem with connecting to your Elasticsearch host" notification in the admin panel, and it always reconnects immediately and works fine until the next disconnect.

**Environment information**
My environment is a bit unique:

- I'm running WordPress in a managed GKE cluster with 5 replicas.
- I'm using WP as a headless CMS, so I only use the admin panel, RSS feeds, and the `wp-json` endpoints.  A separate nodejs project consumes the `wp-json` endpoints to render the frontend.
- My ElasticSearch instance is hosted in cloud.elastic.co via the "Elasticsearch managed service" option within Google Cloud.
- The ES instance has looked healthy the whole time it has been running

Version information
- ElasticPress 3.6.2
- WordPress 5.8.1
- PHP 7.4.25

**Comment by ckeeney** [comment]
@brandwaffle After reading through [`get_elasticsearch_info`](https://github.com/10up/ElasticPress/blob/47670f2e603500c26e866759a63bd5d5b5637870/includes/classes/Elasticsearch.php#L1246) a bit more, it seems that if a check for ES version fails, that failure is cached.

Once there is a failure the version and plugins are being set to false and empty array:

https://github.com/10up/ElasticPress/blob/47670f2e603500c26e866759a63bd5d5b5637870/includes/classes/Elasticsearch.php#L1293-L1297

And then those values are cached:

https://github.com/10up/ElasticPress/blob/47670f2e603500c26e866759a63bd5d5b5637870/includes/classes/Elasticsearch.php#L1330-L1348

I think it would be ideal to not cache the failure, or at least cache it for a shorter time like 5s-10s. I think it's likely that I'm seeing this issue during a 5 minute cached failure, because often times it goes away on its own before i can fix it.

What are your thoughts?

**Comment by brandwaffle** [comment]
@ckeeney you could certainly filter down that value for your setup, which would help the site "heal" faster after a failed Elasticsearch call. In general, we don't recommend setting this too low, since it just means EP will check a lot more to ensure the server is there. You may also consider dropping some logging into your filter so you know how often you're getting failed requests. Since this is related to connectivity and not the plugin, I'm going to close this issue out for now. If you run into a new error or determine this is a false positive, please feel free to open a new ticket!
