### ISSUE TITLE
QUESTION: column data type for meta

### ISSUE THREAD

**Issue by przestrzal** [10up/ElasticPress#2472]
Hi,

i see that EP stores every meta in many columns  depending on data type:

<img width="208" alt="Screenshot 2021-11-20 at 12 36 41" src="https://user-images.githubusercontent.com/17744192/142724946-35e3235d-391b-4c4f-add9-287437ba2e04.png">

Is there any option to tell ES which kind of data store each meta to prevent ES from making so many columns?

**Comment by felipeelia** [comment]
Hi @przestrzal,

It happens inside the [Post::prepare_document()](https://github.com/10up/ElasticPress/blob/1b82019dd2bda448d42cb9acb99efb9c2afa0177/includes/classes/Indexable/Post/Post.php#L361) method, when it calls the [prepare_meta_types()](https://github.com/10up/ElasticPress/blob/1b82019dd2bda448d42cb9acb99efb9c2afa0177/includes/classes/Indexable/Post/Post.php#L453) method. You can change the final result of it using the [`ep_post_sync_args_post_prepare_meta` filter](https://github.com/10up/ElasticPress/blob/1b82019dd2bda448d42cb9acb99efb9c2afa0177/includes/classes/Indexable/Post/Post.php#L480).

It will depend a bit on what you are trying to achieve but you may also consider skipping some meta fields instead of trying to remove some of their types. If that is easier, you can use any of the filters available inside the [Post::prepare_meta()](https://github.com/10up/ElasticPress/blob/1b82019dd2bda448d42cb9acb99efb9c2afa0177/includes/classes/Indexable/Post/Post.php#L683) method.

I'll go ahead and close the issue but let us know if you have any further questions. Thanks!

**Comment by przestrzal** [comment]
Ok, @felipeelia thanks for you answer.

Maybe i will handle it in different way. Is there any possibility, to select which meta will be returned by WP_Query?

I 've got a lot of meta, which i neeed to index in Elasticsearch.

Making raw Elasticserch request there is a option to tell, which fields should be returned, ex.:

```
{
    "query":
    {
        "bool":
        {
            "must": [
            {
                "match":
                {
                    "post_type": "offer
                }
            }]
        }
    },
    "_source": [
        "ID",
        "post_title",
        "meta.offer__id.value",
        "meta.offer__market.value",
        "meta.offer__product.value",
        "meta.offer__set.value",
        "meta.offer__active.value"
    ],
    "from" : 0,
    "size" : 100
}
```

is it possible with `WP_query()` with `'ep_integrate' => true` ?
