### ISSUE TITLE
QUESTION: Self host elastic autosuggest issue

### ISSUE THREAD

**Issue by MatteoArcangeli** [10up/ElasticPress#2518]
Hi,
I have configured a wordpress site and elasticstack in the same server machine.
I'm able to react elastic server using http://127.0.0.1:9200.

The problem in when i try to configure autosuggest indeed I have this error
![image](https://user-images.githubusercontent.com/80588627/145975835-d99e1da0-a5a6-49b5-9926-0b6624bd2ce2.png)

I have configure **Endpoint URL** it this way http://127.0.0.1:9201/searchcronachemaceratesiit-post-1/post/_search

Does someone can help me, I can't find any details on how configure properly autosuggest.
Thanks

**Comment by felipeelia** [comment]
Related to #2513

Hi @MatteoArcangeli, as I said in that other issue you opened, the Endpoint URL _needs to be something accessible by the user, not by your webserver_.

When the user's browser tries to access http://127.0.0.1, it will try to access _their_ own computer and not _your_ server, i.e., you'll have to set it like http://domain.com:9201/searchcronachemaceratesiit-post-1/post/_search, for example. But please don't do simply that, because as I said, it'll be a major security problem for you.

In general lines, you'll have to:

1. Have a public IP (and/or a domain) pointing to your server
2. Allow public access to the 9201 port or have some sort of forwarding rule in place
3. Test access via cURL or postman, making a request to that URL and checking if the result really comes from Elasticsearch

How to set that will completely depend on your setup and as all these steps happen outside of WordPress, setting it up is outside of the scope of this repository.
