### ISSUE TITLE
QUESTION: Add custom taxonomy to Facets query?

### ISSUE THREAD

**Issue by MediaMaquina** [10up/ElasticPress#2532]
On a previous version (3.5.6) i had a modified Facets.php to add some taxonomies to my query. But after updating to Elasticpress 3.6.5 the code is now different and i don't understand how to do it anymore.
The function in question is called build_query_url
This was mas previous code:

```
//add custom queries
$sorted = get_query_var('sorted');
$source = get_query_var('source');
	
		if ( ! empty( $sorted) && empty( $source) ) {
		$query_string .= 'sorted=' . $sorted;
	}elseif ( empty( $sorted) && ! empty( $source)) {
		$query_string .= 'source=' . $source;
	}elseif ( ! empty( $sorted) && ! empty( $source)) {
		$query_string .= 'sorted=' . $sorted.'&source='.$source;
	}
```
I see now there is a filter and maybe my hacky method isn't even necessary any more? Could you show me how can i do what's shown above with the filter? Or how can i make it work in 3.6.5 with any method.

Thank you.

**PS: Also all the checkboxes disappeared from the Facets making it impossible to know what's selected for users.**

**Comment by oscarssanchez** [comment]
Hey @MediaMaquina ,

You would need to append those "sorted" and "source" params to the `$query_string` variable that's being passed, or alternatively use `$query_param` in a similar fashion like https://github.com/10up/ElasticPress/blob/3c3ff85a1a35da78e68d67258897133c22171626/includes/classes/Feature/Facets/Facets.php#L441

and return that value (so that it becomes `$query_string`)

When you say the checkboxes disappeared from the facets, can you confirm that's with your custom code and not with a fresh ElasticPress install?

**Comment by MediaMaquina** [comment]
Success! Added it just under:

https://github.com/10up/ElasticPress/blob/3c3ff85a1a35da78e68d67258897133c22171626/includes/classes/Feature/Facets/Facets.php#L441

But it needed & before each parameter. On the old Facets.php it wasn't needed for some reason.

So
`$query_string .= '&sorted=' . $sorted;`
Instead of
`$query_string .= 'sorted=' . $sorted;`
