### ISSUE TITLE
QUESTION: Some products should only be searchable through a direct match on their SKU

### ISSUE THREAD

**Issue by rommeled** [10up/ElasticPress#2584]
We have a webshop which has 80.000 products which automatically get's synced/imported twice daily from an external ERP system in to WooCommerce and then synced with ElasticPress. These products can be both variable and simple.
The majority of the products (around 55.000) of the products comes with very little information on them and preferably them specific products should only be exposed in searches if the search is a direct match on the product SKU when searching. 
The rest of the products (around 25.000) should be searchable as usual.
Right now we have 2 ways that we know a particular product should only be found by it's SKU.
1) If the catalog_visibiltiy is set to 'search' within WooCommerce.
2) If the product has meta-data '_product_in_progress' => true

Is there a way to make certain products only searchable by direct match to the SKU? Preferably from one of the 2 qualifiers above.

Right now we have a custom ajax query which calls the WP_Query with 'ep_integrate' => 'true' which works very well with Elastic Search and the ElasticPress plugin.

I've also noted that I can change the meta data available for the specific post/product by using the 'ep_prepare_meta_data' filter where I can limit the meta-data searchable by elastic on a specific product.

**Comment by felipeelia** [comment]
Hi @rommeled,

What you are trying to do is possible but will require some heavy changes in the Elasticsearch query, most probably through the `ep_formatted_args` filter.

To use different fields per post type, for example, we use a structure that looks like this:
```
"query": {
	"function_score": {
		"query": {
			"bool": {
				"should": [
					{
						"bool": {
							"must": [
								{
									"bool": {
										"should": [
											// Fields and their weighting
										]
									}
								}
							],
							"filter": [
								{
									"match": {
										"post_type.raw": "post"
									}
								}
							]
						}
					},
					...
```

You would use the same idea but instead of filtering per post_type.raw = post, you would filter by your metadata. If you are not using it yet, Debug Bar and Debug Bar ElasticPress are plugins that may help you figure out the query being fired and how it can be changed to serve your purposes.

If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation. If you are already an ElasticPress.io customer, feel free to open a ticket through your account page.

Thanks!

**Comment by rommeled** [comment]
Thanks for the fast feedback. I will look into it :)
