### ISSUE TITLE
QUESTION: Elastic searching is not working on front-end

### ISSUE THREAD

**Issue by pranavmtn** [10up/ElasticPress#2605]
**Describe your question**
Hi,

I have configured elastic press with our own hosting(in cloudways).But it is not working in the front end.
Done indexing,and changed settings also tested for plugin/theme conflict ,nothing found.

Tested with Debug bar for Elastic Press plugin ,Result:https://prnt.sc/xGF_Fap1E-Q0

Do you have any idea,what i might be missing

Thanks

**Comment by brandwaffle** [comment]
Hi @pranavmtn, ElasticPress works by looking for the `s` parameter in a WP_Query, so if that's missing because of a theme or plugin, ElasticPress won't "see" the search and won't intercept it.

You may want to try using the Debug Bar to see what WP_Query is loaded on the page where you're not seeing any ElasticPress queries, and ensure it has the proper `s` parameter.

When you say you tested for conflicts, is there still no query if you disable all plugins except ElasticPress and use a common theme like twentytwentyone?

**Comment by brandwaffle** [comment]
Hi @pranavmtn unfortunately, connecting to specific sites to provide troubleshooting is beyond the scope of the support we can provide here. There are several reasons this could be happening, including an incomplete index, caching holding onto a transient that makes WP think ElasticPress is still indexing, query issues on the page, etc.

If you add the `ep_integrate => true` parameter to a query, this will force it to run through ElasticPress. If this doesn't work, you likely have one of the config/install issues I mentioned above.

Alternatively, if you would like us to provide hands-on troubleshooting for your specific setup, we do offer consulting on an hourly basis: https://www.elasticpress.io/elasticpress-consulting/

**Comment by pranavmtn** [comment]
Hi, @brandwaffle ,

It seems totally unfair to me.

You have a free plugin which is hosted in the WordPress repository.And you actually not giving support there.

In github, however, we have to pay.

In case the plugin has a bug or something in it, how will you know about it? Do we have to opt for your paid consultation to fix your bugs?

Let me know,if I am wrong
Thanks

**Comment by brandwaffle** [comment]
Hi @pranavmtn I'm sorry you feel this way, but we provide the plugin, as you said, completely for free, so I'm not exactly why you feel we are also required to provide you with free, hands-on support. I also provided you with a path forward to help you debug your configuration, which will enable you to find the issue with your site to get ElasticPress working for you.

To be clear, are not reporting a bug. You have a custom Elasticsearch setup and a custom WordPress site, and somewhere in there there is a conflict or misconfiguration. If ElasticPress was unable to search, there would be hundreds of people here reporting that as an issue. As you also mentioned, ElasticPress is 100% open-source--you can view the source code and debug this issue with your site (or any other) just as simply as we can, should you not want to pay for someone to do this for you.

As I mentioned before, you will need to do the following to troubleshoot your issue:

- Confirm you have a complete index and indexing is not paused and did not fail. ElasticPress will not activate for any searches or queries without a successful, completed index process (you should perform this index via WP-CLI in case you need it for the last step)
- Test a basic search with the `s` parameter using only WordPress, ElasticPress, and a default theme.
- If that query contains the `s` parameter but does not load ElasticPress, then you can share the log output of your successful index as well as the output of the WP_Query in this ticket, and we can provide further steps for you to troubleshoot.

Again, all of the above is provided to you as a courtesy--it is also available in our documentation. The plugin itself also runs automated tests which confirm that the behavior that's not working for you works on a WordPress install with a default theme, which is how I'm able to be confident that the issue is not a bug in the plugin. You may consider following up with Cloudways if the setup continues not to work, as it may be a system configuration issue on the WordPress or Elasticsearch server(s).

**Comment by pranavmtn** [comment]
Hi, @brandwaffle ,

Appreciate the explanation.

I have tried the above method as well.Rexindexed many times,with WP-CLI as well.

Tried to configure for a simple wordpress application(which includes only ElasticPress plugin).

Let me know,how i can share the index logs ,i will share then
Contacted with cloudways team,and confirmed Elastic search is working in server fine.

A week on this implementation and still.

Thanks
