### ISSUE TITLE
QUESTION: It seems weight setting is not work

### ISSUE THREAD

**Issue by kozora** [10up/ElasticPress#2616]
when I set <title> more weight, and content less weight
the search result is still not correct, I want the title keyword result is leaner forward, not mixed with content contained

**Comment by oscarssanchez** [comment]
@kozora  If I understood correctly, you want to only look at the title then? you might want to just toggle the content so that it is not searched at all. If you leave the checkbox, it will always calculate the score of the doc given a search term based on all the fields that are set to be searchable, and then those depend on the weight and the number of times a keyword is found. You can also try setting the title to the max setting. Hope that helps!
