### ISSUE TITLE
ElasticPress 4.0: Adjust resync message to warn about Instant Results

### ISSUE THREAD

**Issue by felipeelia** [10up/ElasticPress#2617]
**Is your enhancement related to a problem? Please describe.**

As ElasticPress 4.0.0 is a version marked as resync-required, users will see this message:

> The new version of ElasticPress requires that you run a sync. Please note that some ElasticPress functionality may be impaired and/or content may not be searchable until the reindex has been performed.

As the new Instant Results feature also requires a reindex, it'd be ideal that people wanting to use that could enable it first and run the resync only once.

**Describe the solution you'd like**

Ideally, we would cover 3 scenarios:
1. Not EP.io client and no proxy available
2. Not EP.io client but proxy available
3. EP.io client

The code that needs to be changed lives in the [AdminNotices::process_upgrade_sync_notice()](https://github.com/10up/ElasticPress/blob/a1fad5709dc3942075196eefdb16e4a7edfab269/includes/classes/AdminNotices.php#L237) method and if possible, would be a message displayed *in addition* to the one being already used, so we could simply add an action to be called there depending on the current and the old version.

**Comment by brandwaffle** [comment]
EP.io: Instant Results is now available in ElasticPress, but requires a re-sync before activation. Click here to activate the Instant Results Feature and start your sync.

Non EP.io/no proxy: Instant Results is now available in ElasticPress, but requires a re-sync before activation. Since you are not using ElasticPress.io, you'll also need to install the PHP proxy plugin before activating Instant Results. Once the plugin has been installed, you can re-sync your content.

Non EP.io w/proxy: Instant Results is now available in ElasticPress, but requires a re-sync before activation. We've detected that you're not running ElasticPress.io but have the PHP proxy plugin successfully installed. Click here to activate the Instant Results Feature and start your sync.

**Comment by felipeelia** [comment]
*EP.io* and *Non EP.io w/proxy*: Instant Results is now available in ElasticPress, but requires a re-sync before activation. If you'd like to use [Instant Results](zendesk-article), click here to activate the feature and start your sync.

*Non EP.io/no proxy*: Instant Results is now available in ElasticPress, but requires a re-sync before activation. If you'd like to use [Instant Results](zendesk-article), since you are not using ElasticPress.io, you'll also need to install and configure a PHP proxy.
