### ISSUE TITLE
QUESTION: Enable ElasticPress only for admin queries + object cache compatibility?

### ISSUE THREAD

**Issue by Dekadinious** [10up/ElasticPress#2627]
Is it possible to enable ElasticPress only for searches in the admin, including WooCommerce searches for products, orders, etc.? Without touching any queries for listing products on the front end? I have seen people having trouble with sorting out of stock products last and things like that. I would rather not touch any queries for the front end, but I want to have fast and reliable searching in the back end.

Also, is this plugin compatible with Redis object cache and the Object Cache Pro plugin? I read somewhere that you need to disable object cache to avoid PHP loops while using this plugin.

**Comment by oscarssanchez** [comment]
Hi @Dekadinious ,

Yes you should be able to only activate it in the admin by setting `ep_integrate` to false, so something like

```
add_action( 'pre_get_posts', function( $query ) {
 if ( ! is_admin() ) {
   $query->set( 'ep_integrate', false );
  } 
} );
```

If I looked correctly, the article you are referring to is this one from 2016 https://guides.wp-bullet.com/install-configure-elasticsearch-to-speed-up-wordpress-search/ 

The plugin has come a long way since, so best chance is give it a try and you can always open an issue if you find an incompatibility with it.
