### ISSUE TITLE
QUESTION: Help troubleshooting ElasticPress errors

### ISSUE THREAD

**Issue by buzzbold-jeremy** [10up/ElasticPress#2707]
Hi,

Our ElasticPress and/or ElasticSearch is not working. I'm using ElasticPress 3.6.6 and Debug Bar for ElasticPress. We are using filters in ElasticSearch to skip indexing certain posts with the "ep_post_sync_kill" filter and it used to work, but those indexes are no longer being skipped. We also use the "ep_post_query_db_args" filter to not return certain posts in query results and that is no longer working as well. When we update to 4.0.0 or later we have the same issues. When I run a search there are a few errors I have seen in Debug Bar with a status of 400:
- [illegal_argument_exception] Limit of total fields [1000] in index [wp-post-1] has been exceeded
- [multi_match] query does not support [fields]
- field [post_date_gmt] is of type [org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType@79acf8d6], but only numeric types are supported.

The most recent one is:
- "error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [terms.category.slug] in order to load field data by uninverting the inverted index. Note that this can use significant memory."}],"type":"search_phase_execution_exception","reason":"all shards failed"

When I run "wp elasticpress index" in the cli this is the response I get:
> Number of posts indexed: 204
> Warning: Number of post index errors: 2806
> Total time elapsed: 30.727
> Success: Done!

Do you have any suggestions on how to troubleshoot what the issue is and how to resolve this?

Thank you

**Comment by oscarssanchez** [comment]
Hi @buzzbold-jeremy ,

It seems you have quite some problems. I'll try my best to isolate them.

> We are using filters in ElasticSearch to skip indexing certain posts with the "ep_post_sync_kill" filter and it used to work, but those indexes are no longer being skipped

Questions for you: 

* Can you provide code examples of how are you doing it?
* When you say "those indexes are no longer being skipped", do you mean posts, not actual indexes? 

>  We also use the "ep_post_query_db_args" filter to not return certain posts in query results and that is no longer working as well

Questions for you: 

* Can you provide code examples?
* Is there a reason not to exclude them via WP_Query param `post__not_in` and let ElasticPress figure out the rest ?

> [illegal_argument_exception] Limit of total fields [1000] in index [wp-post-1] has been exceeded

This usually means you have too much post meta data due to usage of page builders, advanced custom fields or plugins that tend to use some kind of repeater functionality. You can find a troubleshooting guide here for that: https://elasticpress.zendesk.com/hc/en-us/articles/360051401212-I-get-the-error-Limit-of-total-fields-in-index-has-been-exceeded- 


> field [post_date_gmt] is of type [org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType@79acf8d6], but only numeric types are supported.

>"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [terms.category.slug] in order to load field data by uninverting the inverted index. Note that this can use significant

This usually tends to be a problem with mapping, this is a good article to troubleshoot those problems: https://www.elasticpress.io/blog/2017/05/debugging/

Hope it helps!

**Comment by felipeelia** [comment]
For those coming to this issue with similar problems, expanding @oscarssanchez's answer a bit, if you need to send the mapping again, you actually need to run `wp elasticpress index --setup`, so the Elasticsearch index will be deleted and recreated with the correct mapping.
