### ISSUE TITLE
QUESTION: When will the maximum required Elasticsearch version be bumped up? 

### ISSUE THREAD

**Issue by StianHNilsen** [10up/ElasticPress#2713]
**Describe your question**
Hi there! When will the maximum required Elasticsearch version be bumped up? 

I'm getting the following message in the with ElasticPress (4.1.0) in the wp-admin panel: `Your Elasticsearch version 7.17.1 is above the maximum required Elasticsearch version 7.10. ElasticPress may or may not work properly.`

ElasticPress won’t map and index properly with the ElasticSearch right now. Image below shows indexing posts just stops as well. 
<img width="886" alt="image" src="https://user-images.githubusercontent.com/26089853/162818276-55bd1536-f6b9-4f16-b2c3-1f98d3685f99.png">

**Comment by oscarssanchez** [comment]
Need to go through full QA with 7.17.1

**Comment by oscarssanchez** [comment]
Hi @StianHNilsen ,

I couldn't reproduce with the details you have provided

<img width="2026" alt="Screen Shot 2022-04-25 at 20 33 58" src="https://user-images.githubusercontent.com/31049169/165201383-fc991a20-af85-43a8-ae01-87917f0211a9.png">

Could you confirm your problem is because of `7.17.1` ?  You might want to downgrade to a lower version that's supported by ElasticPress to validate this.

**Comment by swiftcommike** [comment]
Same error message in our WP dashboard. I just tried to deploy  Elasticsearch 7.10, but only 3 versions are available in the 
Kibana/AWS management console. They are: 8.4.3, 8.3.3, 7.17.6. So, without spinning up a server manually, it seems impossible to deploy a compatible version on Kibana/AWS.
I'm interested in reverting, because multi-word searches are not producing results. Only single work searches are working. Even with quotes, only single word searches are working.
I deleted and rebuilt mapping/indexing after the Elasticsearch upgrade.
