### ISSUE TITLE
User Indexing BUG

### ISSUE THREAD

**Issue by blenkhn** [10up/ElasticPress#2827]
The big thing for me is how do I exclude the admin users from the index?

**Describe the bug**
472 (User): [illegal_argument_exception] Limit of total fields [5000] in index [keyinnovationsca-user] has been exceeded
454 (User): [illegal_argument_exception] Limit of total fields [5000] in index [keyinnovationsca-user] has been exceeded
393 (User): [illegal_argument_exception] Limit of total fields [5000] in index [keyinnovationsca-user] has been exceeded
1 (User): [illegal_argument_exception] Limit of total fields [5000] in index [keyinnovationsca-user] has been exceeded
Number of users index errors: 4

**Steps to Reproduce**
index the site.  That is from the error log

**Expected behavior**
no errors.  

**Environment information**
 - WordPress version: 6.0
 - ElasticPress version: 4.1
 - Elasticsearch version: 6.8.23
 - Where do you host your Elasticsearch server? local host
 - What ElasticPress features do you have currently active?  Post Search, WooCommerce, Documents, Users, Protected Content, Related Posts, Facets, Terms

**Comment by felipeelia** [comment]
This is not a bug but an Elasticsearch limitation. Although it is much more common on posts, it is possible to work around it for users as well.

We've covered this subject in these two articles:
- https://elasticpress.zendesk.com/hc/en-us/articles/360051401212-I-get-the-error-Limit-of-total-fields-in-index-has-been-exceeded-
- https://elasticpress.zendesk.com/hc/en-us/articles/360052019111

Instead of using `ep_prepare_meta_data` you will want to use the user-related filter: `ep_prepare_user_meta_data`: http://10up.github.io/ElasticPress/ep_prepare_user_meta_data.html
