### ISSUE TITLE
Remove / suppress all query filters during an index operation

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#293]
Discovered a massive issue with the Tribe Events Calendar that occurred during a bulk index operation.

The Events Calendar has a filter on `parse_query` that adds some very heavy `IF` logic to the mysql request. This not only slows down the indexing operation but can potentially fill up the mysqltmp file and crash the db server.

Taking this a step further, I began to wonder - when would we want to allow the queries of the index operations to be filterable at all?

Could/should we remove all filters via the `remove_filter` command from filters? When I did this I noticed the indexing operation for 20k+ posts went _significantly_ faster then I had ever seen it happen.

This warrants some discussion, but I wanted to raise the question to get some input.

cc @tlovett1

**Comment by bordoni** [comment]
On `parse_query` or on `pre_get_posts`? Currently the plugin creates custom SQL on the following methods:
- `Tribe__Events__Query @ multi_type_posts_fields`
- `Tribe__Events__Query @ posts_join`
- `Tribe__Events__Query @ posts_join_orderby`
- `Tribe__Events__Query @ posts_where`
- `Tribe__Events__Query @ posts_distinct`
- `Tribe__Events__Query @ posts_groupby` -- _Deprecated_

The only if that happens is if you want to include the Events CPT on the main Loop right?

At: [_L436_ of `src/Tribe/Query.php`](https://github.com/moderntribe/the-events-calendar/blob/develop/src/Tribe/Query.php#L436)
```
$fields[]       = "IF ({$wpdb->posts}.post_type = 'tribe_events', $postmeta_table.meta_value, {$wpdb->posts}.post_date) AS post_date";
```

**Comment by AaronHolbrook** [comment]
Hi @bordoni,
I was seeing it on `parse_query`.

Since this is an indexing operation performed via a WP_CLI command for the express purpose of sending all data to an Elasticsearch server (so it's the main loop), your injection causes some serious issues simply because the `tribe_events` post type was included in the query.

**Comment by bordoni** [comment]
The only problem I could ever see would be missing the "ordering", which I think on a Indexing action is not _really_ a problem.

**Comment by AaronHolbrook** [comment]
@bordoni I don't think orderby is at all relevant in an indexing operation.

**Comment by bordoni** [comment]
:wink: Agreed!

**Comment by AaronHolbrook** [comment]
Does anyone else have any thoughts as to why suppressing filters during indexing could have negative ramifications?

**Comment by psorensen** [comment]
We filter the_content to show a password prompt for unregistered users.
Unless we add a check to the filter, EP will index the password prompt
instead of the content.

An easy fix on our end, but would definitely lean toward turning off
filters altogether when indexing, as we have no need for them. Regardless,
if possible, it would be most beneficial to make the implementation of this
command filterable. (true/false)

**Comment by joelgarciajr84** [comment]
Just following the conversation :+1:

**Comment by AaronHolbrook** [comment]
@psorensen I can see how that would affect you, but it does make more sense to leave content stored in `post_content` and simply change the template logic to test if a user is logged in/out to show it. That or use something like [Restrict Content Pro](https://pippinsplugins.com/products/restrict-content-pro/).

Irregardless, I do believe we could leave this up to the user and have it be filterable but default to having all filters removed upon index querying.

**Comment by tlovett1** [comment]
@psorensen which filter are you doing that on?

**Comment by psorensen** [comment]
@tlovett1  I'm filtering `the_content`. Is this what you mean?

@AaronHolbrook We do use a membership software, Membermouse. But their content restriction is limited so we take it into our own hands using membership-level checks using their API. We've tried to make the content restriction theme-agnostic by filtering the content, rather than place the logic directly in the theme.

My solution to bypass the filter while indexing was to return if the current template wasn't a single page. Here's my way simplified filter function (Ironic, I thought of doing it this way after watching [Fail Early, Fail Often](http://aaronjholbrook.com/fail-early-fail-often/ Thanks @AaronHolbrook!)
```php
add_filter( 'the_content', 'filter_func' );

function filter_func() {
    if ( ! is_single() ) {
        return $content;
    }
    return  ( ! is_valid_member() ) ? $content_restriction_message : $content;
}
```

**Comment by AaronHolbrook** [comment]
@psorensen yea that looks like it'd work fine - only show the message if a condition is met (i.e. member not valid), instead of storing that message as `post_content`.

@tlovett1 a possible strategy we could employ to not break backward compatibility is to check to see if ElasticPress was already installed and if it was, set the filter removal to false by default. It would be more complex logic, but it could potentially prevent breakage on people if they're already relying on it.

**Comment by allan23** [comment]
I think this a good idea to improve indexing time, but what about shortcodes that provide relevant content to the page/post?

**Comment by AaronHolbrook** [comment]
This was just intended to suppress query filters, not `the_content` type filters, so I believe shortcode filters would be ok.

**Comment by allan23** [comment]
@AaronHolbrook I don't see why this would be an issue then.

**Comment by allan23** [comment]
@AaronHolbrook @tlovett1 Where did we land on this topic?

**Comment by AaronHolbrook** [comment]
I think it looks like it would indeed be safe to proceed. @tlovett1 ?

I vote to make this a part of the next release.

**Comment by ChrisWiegman** [comment]
After review I do think this is the same issue I was experiencing in #467 and results from the fact that the_content is applied before index rather than just after (it is applied again after content retrieval before the content is displayed).

This leaves us a few choices.

1.) Remove the_content filter. The simplest and will bring data store in ES to parity with data stored in MySQL but will of course prevent ES from searching output of items such as shortcodes.

2.) Wrapt the_content filter in something akin to ep_the_content to allow for selective application of individual filters applied during the_content

3.) Store the data twice... Once for parsing in the current format and once for retrieval in the raw format without the_content applied

4.) A hybrid approach that compares the content field both before and after the_content is applied and only stores two data sets if needed.

**Comment by dansmart** [comment]
I've recently encountered this. I'd love to be given the option as a developer - so either (2) which allows me to choose whether I want the filtered or unfiltered version of post_content to be stored, or (3) which gives me the choice after indexing.

**Comment by jb510** [comment]
Has anyone ever gotten ElasticSearch working to return regular The Events Calendar queries? (not search). 

I really think using ElasticSearch could solve our scaling issues, but so far we get garbage back (wrong post order and errors) when trying to use ES for Tribe's The Events Calendar normal queries.  Search works fine.  I did get ES to index all of TECs hidden fields, but still getting errors and garbage back.  Happy to open a new ticket if that makes sense, but this isn't really an EP issue, it's a TEC issue and they don't seem to care.

**Comment by brandwaffle** [comment]
Closing this as Events Calendar has an EP module now and this ticket is quite stale. Other issues raised can be addressed in other tickets.

**Comment by sc0ttkclark** [comment]
@brandwaffle Which EP module are you referring to here?

**Comment by felipeelia** [comment]
I guess it is this one @sc0ttkclark : https://theeventscalendar.com/product/elastic-events/

**Comment by sc0ttkclark** [comment]
Gotcha, yeah I'm the one that built that one :)

Just was confirming there
