### ISSUE TITLE
Why did wp query didn't show up in debug console In elastic press section

### ISSUE THREAD

**Issue by Vaibhav2608** [10up/ElasticPress#3072]
I made some code through which we can filter woocommerce products. Code works purely on ajax and `wp_query` but the problem is my query didn't show up in elastic press debuge console, I even install Query Monitor to view query but it also doesn't contain my query.

Did ajax query didn't show up in debug console? And one more thing why did response takes 2 sec. 

If any one can tell me if these thing are normal for `wp_query` elastic search.

Thank you

**Comment by felipeelia** [comment]
Hi @Vaibhav2608,

AJAX Requests will not be captured by any of these debug plugins, as they can only detect things happening in the request that has "created" the original page (not any subsequent request.)

I'm not sure about what you are trying to achieve but you can debug it using tools like XDebug or error_log calls, so messages are output in log files. To integrate AJAX calls, you might need to add `add_filter( 'ep_ajax_wp_query_integration', '__return_true' )` to your codebase (see the [filter documentation](http://10up.github.io/ElasticPress/ep_ajax_wp_query_integration.html).)

As last, it is impossible to determine the reason why it is taking 2 seconds without knowing more about your setup and how you are measuring that time. It could be because WordPress itself is slow or could be related to the way you are hosting Elasticsearch.

Do you want to expand a bit more on what you are trying to achieve so we can better help you? Thanks

**Comment by Vaibhav2608** [comment]
Hi @felipeelia ,

I added some code which will real time search product on shop page. I am doing that with ajax along with wp-query and that ajax response taking approx 2-3 sec. I my code only show 12 product of search result on page.

I am using cloudways hosting. They provide es integration. But still it gives me result in 2sec. 

I hope now I make myself clear.

**Comment by Vaibhav2608** [comment]
Hi @felipeelia ,
You were right the problem was wordpress itself.

Thank you for you help
