### ISSUE TITLE
The response is not a valid JSON response.QUESTION: 

### ISSUE THREAD

**Issue by mediachip-ux** [10up/ElasticPress#3089]
We are trying to sync Elasticpress but we get the following message:

Elasticpress - Sync Fails - The response is not a valid JSON response.

Is there a way to fix this?

**Comment by oscarssanchez** [comment]
Hi @mediachip-ux ,

This could be for a variety of reasons, most often it could be because of a plugin conflict. I think the first steps is confirming this by disabling all your plugins and only keeping ElasticPress. If indexing proves to be successful, then finding the conflicting plugin would be the second step.
