### ISSUE TITLE
Seeing issue when exclude meta, showing odd results

### ISSUE THREAD

**Issue by bfrye26** [10up/ElasticPress#3120]
We have been using Elasticpress for a while now, and recently noticed there are very strange issues coming up. We had to exclude meta fields to get the index of all posts done correctly , but when we did that and reindexed everything, searches act strangely.

```php
add_filter( 'ep_prepare_meta_data', function( $meta ) {  
    $allowed_meta = array();
    $all_meta = $meta;
    $meta = [];    
    
    foreach( $allowed_meta as $meta_key ) {
	$meta[$meta_key] = $all_meta[$meta_key];
    }
    return $meta; 
} );
```

We have it set to relevence, but when we do, it shows very old posts first. If we set it to date, it shows articles that are not at all related to the search.

Currently a bit stuck on what is the best approach to solve the issue, and have it so the search makes sense and is useful to users, and admins using it for search in the backend.

Here is the code we used to exclude all meta fields:

Thanks for any help!

**Describe your question**

**Comment by bfrye26** [comment]
Just to give a bit more context, when searching, for the term "Star Wars" for example, if it is set to date, the results seem to never mention Star Wars in the content. When set to relevance, it has posts from years ago first, it seems to make no rhyme or reason. I have included screenshots just to give an idea. I also tried the same with the term Samsung, just to give an idea on what sort of issues the search is giving. 

![image](https://user-images.githubusercontent.com/5135055/200591774-dfbd1a74-abaf-4b69-af0a-c7e65eb53654.png)

![image](https://user-images.githubusercontent.com/5135055/200591914-bb99b118-ccf4-427d-a41a-b41da7f08743.png)

![image](https://user-images.githubusercontent.com/5135055/200592242-220343d2-d838-4c79-8f61-f052906f586d.png)

![image](https://user-images.githubusercontent.com/5135055/200592325-abc7a637-59aa-4000-83c4-d75123a1a83c.png)


I welcome your input, since something is acting very strange.

**Comment by bfrye26** [comment]
I should also note, if I brute force it by making the meta limit over 5000, the results are MUCH better, but there is then an issue where the search is incredibly slow, so that method simply did not work.

**Comment by felipeelia** [comment]
Hey @bfrye26, some questions for you:

- When you say "When set to relevance", where are you changing that value?
- In ElasticPress features, do you have "Weight results by date" (inside Post Search) enabled?
- Can you please install [Debug Bar ElasticPress](https://10up.github.io/ElasticPress/tutorial-debugging.html), visit that search results page again, and share with us here the contents of the query args, body, and results? (Pasting that in pastebin.com and sharing the link makes things easier to read)

Thanks!

**Comment by bfrye26** [comment]
Okay, I did that, I am seeing there are three queries when the search happens:

![image](https://user-images.githubusercontent.com/5135055/200654225-689c94ff-7d19-4278-8ff3-446164c9bbd4.png)

But here is the pastebin of all the details, let me know if you need anything else! 

https://pastebin.com/NC65rDQh

Thank you for all your help!

**Comment by bfrye26** [comment]
Also, I noticed I forgot to mention relivence, currently have it set up with this code:

`<?php 

add_filter( 'epwr_boost_mode', function() { return 'multiply'; } );
add_filter( 'epwr_offset', function() { return '15d'; } );
add_filter( 'epwr_scale', function() { return '30d'; } );
add_filter( 'epwr_decay', function() { return 0.5; } );`

with settings like this:

![image](https://user-images.githubusercontent.com/5135055/200689648-cc6cf153-fe6f-4761-9a47-36a670fcc73f.png)

![image](https://user-images.githubusercontent.com/5135055/200689733-33afcd94-568c-40ea-b2cc-60150bdf4321.png)

![image](https://user-images.githubusercontent.com/5135055/200689765-8a5605af-a6a4-4e88-95e1-03989272ba0d.png)

![image](https://user-images.githubusercontent.com/5135055/200689835-79ade8e4-e09d-4b59-b31c-c6aa956eec73.png)

Let me know if you need anything else to help sort out what is going on.

**Comment by oscarssanchez** [comment]
Hi @bfrye26 ,

The reason you get fresh content is because you have the weight results by date option enabled. The parameters you are setting via the filters you shared affect the decaying function used. Please see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-decay

You'll probably first want to define what "odd" means to you. By default ES function score will take into account the fields, weighting, etc and will determine a score relevant to the query you are asking for. Once that score is made, results will be sorted by max score to min score. See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

From what you shared, the posts you get are the most relevant for the query "star wars" when the date weight is not enabled.

So if in your mind that is "odd", you probably want to define "when" does results are not odd to you. Is it after 5 months when posts should not be shown first, even though they have the term star wars appearing more times and in the most relevant fields? From there you should be able to change the decay functions, change your field weighting, etc. It should be a matter of experimenting with what you are asking for to Elasticsearch, but it definitely doesn't seem to be an issue related with post meta.

**Comment by bfrye26** [comment]
The odd thing is that it is finding articles that do not seem to have anything to do with the topic searched. In this search, in the screenshot, I searched Star Wars. There are a few articles on the first page that have nothing to do with that term, and even when I go into the article, there is no mention of Star Wars. I am honestly confused. I even have it set to consider the title above all else (see Screenshot 2). I am open to suggestions. I am stumped about why it is acting this way. 

Here is a link to the search, maybe that can help sort out what is going on [https://www.cgmagonline.com/?s=star+wars](https://www.cgmagonline.com/?s=star+wars)

![image](https://user-images.githubusercontent.com/5135055/202042142-e3fb74d3-7feb-4264-8d93-bfbdff9c9a0a.png)

![image](https://user-images.githubusercontent.com/5135055/202042175-8a5de1a8-593d-4edc-b594-81bcff882966.png)

**Comment by oscarssanchez** [comment]
Hi @bfrye26 ,

In all of those articles there seems to be mentions to the terms `star`, `war` or `stars`, `wars`, or the whole phrase `star wars`. Since you are searching for `Star + Wars` that's the reason all of that comes back as a result. 

There's many ways to improve the search experience. The lowest effort I think is to give it a try at another algorithm and see if it fits better for your needs. You can see the algorithms we have here https://github.com/10up/ElasticPress/tree/develop/includes/classes/SearchAlgorithm

And you can set the algorithm via a filter or with WP CLI command `wp elasticpress set-algorithm --version=<algo>`

If out of the box those don't really work out for you, it will probably need a more thorough review that will require you to modify other parameters from the ES request. That kind of tailored support is outside the scope of this repository, but we do offer  consulting over at https://www.elasticpress.io/elasticpress-consulting/ if you are interested.

**Comment by bfrye26** [comment]
That makes a lot of sense! Is there any documentation about what the different algorithms do? I did a quick search and could not find it, but I could be missing it. Curious to see how they tackle data differently since what you said makes a lot of sense so to why it would show that. 

Thanks for all the help!

**Comment by oscarssanchez** [comment]
@bfrye26 we have some descriptions about them in each class for example https://github.com/10up/ElasticPress/blob/develop/includes/classes/SearchAlgorithm/DefaultAlgorithm.php#L45 , but if you want to understand them deeply, my suggestion is to get familiarized with Elastic query language.
