### ISSUE TITLE
Scheduled posts are not indexed when transitioning to publish status

### ISSUE THREAD

**Issue by FreshFlesh** [10up/ElasticPress#322]
Thanks 10up for this great plugin!

I noticed that my posts scheduled for publishing are not indexed at all.

Looking at the EP_Sync_Manager class, post sync seems only to happen on `wp_insert_post` hook, which is probably too simplistic. For instance my posts with scheduled publishing are not indexed because WP don't run this hook on cron.

Also what happens if a post meta or a term is updated? It looks like these change are not sync to Elastic.

**Comment by tlovett1** [comment]
@FreshFlesh would love to see a unit test that shows the publishing problem.

If post meta/terms are updated. The post is not resynced to ES. This is definitely a bug but one we haven't thought of a good solution for yet. See #82 

Would love to see some code here :)

**Comment by FreshFlesh** [comment]
My bad, WP indeed run the wp_insert_post hook when a scheduled post is published. I must have an issue with another plugin, i will investigate and confirm!

**Comment by sc0ttkclark** [comment]
I'm reopening this issue. When a post is scheduled, it does run `wp_insert_post` hook that EP hooks into, but in `EP_Sync_Manager` we are checking if current user can edit the post or not:

```php
if ( ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) || ! current_user_can( 'edit_post', $post_ID ) || 'revision' === $post_type ) {
	return;
}
```

This does not take into account wp-cron.php running either in the background or manually. There's no way to tell what a post *was* at this point, so the only way to bypass this would be to check if `DOING_CRON` is happening, in my opinion:

```php
if ( ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) || 'revision' === $post_type ) {
	return;
} elseif ( ( ! defined( 'DOING_CRON' ) || ! DOING_CRON ) && ! current_user_can( 'edit_post', $post_ID ) ) {
	return;
}
```

Split up to make the code a little more readable. Will move forward with a PR on this when the direction of the fix is approved.

**Comment by sc0ttkclark** [comment]
@tlovett1 am i on the right track here for the solution?

**Comment by FreshFlesh** [comment]
+1 for this, had no time to look into it so thank you Scott!

**Comment by sc0ttkclark** [comment]
@tlovett1 Do you want a PR for this fix as I outlined in my previous comment?
