### ISSUE TITLE
BUG: Doesn't match any keywords "new york city" in the PDF but the search result display that PDF in the search.

### ISSUE THREAD

**Issue by mahesh-spinx** [10up/ElasticPress#3229]
### Describe the bug

Hi,

I attached one PDF [Plumbers_1949_Jurisdictional_Agreement.pdf](https://github.com/10up/ElasticPress/files/10285255/Plumbers_1949_Jurisdictional_Agreement.pdf), which was indexed by ElasticPress, after that we search keywords "new york city" but doesn't match any keywords in the PDF but the search result display that PDF in the search result. Why is this happening? In PDF not match andy single word from "new york city".

Can you please check and let us know what is the issue? 

### Steps to Reproduce

1. Install fresh WordPress with ElasticPress.
2. Uploaded attached PDF in media.
3. Indexed uploaded PDF.
4. Search with the "new york city" keyword in global search.
5. PDF found in search results.
6. Actually in PDF doesn't match any single word.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscarssanchez** [comment]
@mahesh-spinx do you have the ingest attachment plugin installed in Elastic and the documents feature activated (and synced after)?

**Comment by mahesh-spinx** [comment]
Yes, I installed ingest attachment plugin and synced the PDF attachment. In PDF no single word is available like "new york city" but it shows in search results.  May be it shows the Fuzzy results. Let us know how we control the Fuzzy result.

**Comment by felipeelia** [comment]
That is probably happening because the text has "work", which is just one letter away from "york". You can control fuzziness using the `ep_post_match_fuzziness` (see [here](https://github.com/10up/ElasticPress/blob/develop/includes/classes/SearchAlgorithm/Version_400.php#L87).) I'd also recommend you to install the [ElasticPress Labs plugin](https://github.com/10up/ElasticPressLabs), enable the Search Algorithm Version feature and change the algorithm version to see which one best fits in your use cases.

I'm going ahead and closing the issue now but please feel free to leave a comment with any additional info you want to share. Thanks.
