### ISSUE TITLE
BUG:  Too Many Request Error

### ISSUE THREAD

**Issue by mahesh-spinx** [10up/ElasticPress#3234]
### Describe the bug

Hello,

We have faced Too Many Request Errors while processing 4584 media files. see this screenshot - https://prnt.sc/aYFFTvINp3eh.
Let us know how we will resolve this issue. Is there any system configuration issue?

My system configuration is below.
https://prnt.sc/m6NVaqeRkaMY

We used  AWS t2.xlarge 
vCPUs - 8 
Memory - 32 GB

Thanks
Mahesh

### Steps to Reproduce

1. We have  4584 media files how i will send you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @mahesh-spinx, that indicates you will need to slow things down a bit, in order to send fewer items to your Elasticsearch server. You can try lowering the number in the EP Settings (it is the "Content Items per Index Cycle" field.) You can also use the `ep_after_send_dynamic_bulk_request` action to make the process wait a second between the requests with something like
```php
add_action( 'ep_after_send_dynamic_bulk_request', function() { sleep( 1 ); } );
```

Or you can try to tweak your ES server configurations. As that is outside this repository's scope, I'm closing the issue now. Thanks
