### ISSUE TITLE
WooCommerce SKU search doesn't work when on wp-admin using ajax

### ISSUE THREAD

**Issue by lenineto** [10up/ElasticPress#3393]
### Describe your question

I'm using the "Phone order" WooCommerce plugin which triggers an ajax search for products. Initially I noticed ElasticPress was not being triggered on the search, and I found that returning TRUE to `ep_ajax_wp_query_integration` filter does the trick, however when enabling ElasticSearch for these ajax queries, I get results with the search term everywhere **BUT** in the SKU field.

I've tried many different filters/actions but so far, no luck.

I was expecting this to work, especially after the latest update that includes SKU search on product variations.

Any idea what I could do here? Am I missing anything obvious?

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @lenineto. As AJAX requests run in an "admin" context for WordPress, those do not receive the weighting configuration. In order to apply those configurations to your query, you need to also add `add_filter( 'ep_enable_do_weighting', '__return_true' );` to your code. That way all fields searched in a "public" query will also be used. Thanks!
