### ISSUE TITLE
php 8.1

### ISSUE THREAD

**Issue by ws256** [10up/ElasticPress#3404]
### Describe your question

Hello everyone
Tell me, did someone check the functionality of the plugin in php 8.1.8?
Everything works for me in php 8.0, but when updating to php 8.1, indexing does not start at all.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @ws256,

ElasticPress is compatible with PHP 8.1. Do you mind sharing the error message and also the entire content of the status report?

**Comment by felipeelia** [comment]
As we didn’t have any movement on this issue for a while now, we are now closing it. If you’re still facing the issue, please let us know. Otherwise, if you’ve managed to get an answer to your problem, we’d highly appreciate it if you could get back to us here and leave the solution in a comment. Thanks!
