### ISSUE TITLE
Sort facet terms by menu_order

### ISSUE THREAD

**Issue by nicolas-wl** [10up/ElasticPress#3446]
### Describe your question

Is there a hook to sort the facet terms by their menu_order instead of count/alphabetical?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hey @nicolas-wl, unfortunately, no. Terms are ordered by the [get_term_tree()](https://github.com/10up/ElasticPress/blob/4.5.2/includes/utils.php#L390) function, [called by the Facet Renderer](https://github.com/10up/ElasticPress/blob/4.5.2/includes/classes/Feature/Facets/Types/Taxonomy/Renderer.php#L183) but there is no filter you could use to change that.

The shortest path you could take is:

- Create a new Renderer class, extending the EP one but overwriting the `render()` method
- Use the [ep_facet_renderer_class](https://github.com/10up/ElasticPress/blob/4.5.1/includes/classes/Feature/Facets/Types/Taxonomy/Widget.php#L49) filter, so EP Facets use your class instead of the native one
- Instead of calling `$terms = Utils\get_term_tree( $terms_by_slug, $orderby, $order, true );` you would call `$terms = $this->get_term_tree( $terms_by_slug, $orderby, $order, true );`
- Create a method called `get_term_tree()` in your class, ordering things as you need

This seems to be a good opportunity to create a new filter in the plugin, so if you want to send us a PR, it'll be more than welcome. Thanks!
