### ISSUE TITLE
Pulling post data from current db instead of only from EP

### ISSUE THREAD

**Issue by sc0ttkclark** [10up/ElasticPress#345]
https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-wp-query-integration.php#L277

On this line, we setup a faux post object, but it's not a real `WP_Post` object. I feel like we should either enable or by default use `$post = get_post( $post_array['post_id'] );` and setting `$post->site` and `$post->elasticpress` after that. If `$post` is empty, then continue and skip that post, as EP is returning a post that doesn't exist.

Getting a post from `get_post()` won't work as expected if the scope is a different site than current blog ID, so we could add logic there to use a faux WP_Post object in that case by setting up a `$faux_post` object and using `$post = new WP_Post( $faux_post )` to get a real live WP_Post.

**Comment by tlovett1** [comment]
I see what you are seeing. Two points:

1. The faux post thing is pretty tricky. I'm not sure if using `get_post` would even work right. Have you tried that?
2. The problem you are trying to solve seems super edge case. ES should always be in sync with WP so it should never happen.

**Comment by tlovett1** [comment]
Update here?

**Comment by archon810** [comment]
I'm using Advanced Excerpt (https://wordpress.org/plugins/advanced-excerpt/), and with ElasticPress, the nicely formatted posts (including embeds, images, etc) turns into text-only content that I presume is coming from ElasticPress's index.

How can we make it so that the post data is always loaded from the db, or that Advanced Excerpt plays nicely with ElasticPress?
