### ISSUE TITLE
Use sitemeta for the ep_indexable metadata

### ISSUE THREAD

**Issue by Rahe** [10up/ElasticPress#3457]
### Is your enhancement related to a problem? Please describe.

I have a large network and I want to get all the websites that have the ep_integrate activated.
Since the ep_integrate option is stored on each blog option table, it can be usefull to use the meta site table allowing to use the site meta query.

### Designs

Use get_site_meta and update_site_meta to update the global blog option table.

### Describe alternatives you've considered

Add filters to option updates handle this myself on option update/deletion.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@Rahe, I'm not sure I follow. We do not have an option called `'ep_integrate'` but we use that as a parameter of WP_Query. Do you mind expanding a bit on what you are trying to achieve? Thanks!

**Comment by Rahe** [comment]
Hello,

Sorry I copied the wrong name, this is the `ep_indexable` option, used here : https://github.com/search?q=repo%3A10up%2FElasticPress%20get_blog_option&type=code

Nicolas,

**Comment by felipeelia** [comment]
Awesome, @Rahe, yeah, that would be a good enhancement! Do you want to open a Pull Request with the changes needed? :)

For whoever wants to help with this issue, here is a rough list of the initial steps:
- Migrate the current blog option to site meta (`includes/classes/Upgrades.php` would be the place for this code)
- Change get_blog_options and update_blog_option calls to reflect the change
- Update tests

Eventually, we'll need to:
- Enhance the Utils\get_sites() function, adding a parameter to retrieve only indexable sites
- Make use of that change everywhere we iterate over the return of that function and check if the site is indexable or not
- Remove both blog_option and site_meta during the uninstall process

I'll add this change to the 5.0.0 milestone for now but it could be added in a 4.7.0 release if we want. For now, all `@since` tags could be `x.x.x`.
