### ISSUE TITLE
Web sync is not capturing all the posts that command line does

### ISSUE THREAD

**Issue by ghost** [10up/ElasticPress#3463]
When I run a Delete all Data and Start a Fresh Sync from the plugin, it only grabs a fraction of the posts that running 

_wp elasticpress sync --setup --show-bulk-errors --show-errors_ grabs.

What is different about the plugin version that would cause this?

ElasticPress 4.2 on WordPress 6.1

**Comment by felipeelia** [comment]
@mvelev8 we will need more info to help you:

1. Can you please share the contents of your ElasticPress Status Report
2. How many posts are grabbed in each (UI / Command Line)?
3. Is there a reason why you are not using the latest version of ElasticPress?

And FWIW, ` --show-bulk-errors --show-errors` is redundant, you can use `wp elasticpress sync --setup --show-errors` instead :)

**Comment by ghost** [comment]
Wow, I am feeling pretty silly now.  So, the only issue was the Content Items per Index Cycle setting being 350.  Is there a maximum limit to this number?  Why would we not just index all the posts?

**Comment by felipeelia** [comment]
No reason to feel that way, @mvelev8 :)

The reason why you wouldn't want to use 100,000 in that field, for example, is because ElasticPress would get all those posts, put them in memory, and try to send them in smaller batches to Elasticsearch. As you can imagine, WP would run out of memory at some point.

It is worth saying that even if someone has that as "1" or "2", ElasticPress will still index everything. It is really just the number of posts being prepared and sent to Elasticsearch before a new batch is prepared and sent. I'm going to close the ticket now but feel free to leave another comment if you have any follow-up question. Thanks!
