### ISSUE TITLE
BUG: Instant Results shows 0 results or previous results while loading

### ISSUE THREAD

**Issue by brandwaffle** [10up/ElasticPress#3508]
### Describe the bug

When performing a search with the instant results feature, if the request takes some time to be returned to the client there will be a screen that shows zero results or the previous results set if a search was performed. There is no indication to the user that results are in the process of updating. We should provide some sort of indicator to this effect.

### Steps to Reproduce

1.  input a search term and hit enter to open instant results modal
2.  if there is a lag, "0 results" will appear until the request completes

### WordPress and ElasticPress information

EP 4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aadityajs** [comment]
Hey EP team,

Any update would be much appriciated on this.

**Comment by oscarssanchez** [comment]
The problem seems to be searchTerm comes as undefined so it runs the following code:

						: sprintf(
								/* translators: %d: results count. */
								_n('%d result', '%d results', totalResults, 'elasticpress'),
								totalResults,
						  )}

I think we need to make sure two things happen:

### Fallback when loading results
If totalResults > 0 we should render one of the `X results` strings

### Make sure searchTerm is defined when launching instant results component for the first time. 
It seems to be the case it is not picking up the search term the first time it is being rendered. searchTerm should be allowed to be undefined or empty but only when IR has been launched before.
