### ISSUE TITLE
ElasticPress PHP Proxy Documentation

### ISSUE THREAD

**Issue by MageNext** [10up/ElasticPress#3605]
### Describe your question

Hi, I was not able to find a single clue on the internet about how the ElasticPress PHP Proxy (self-hosted) GitHub plugin to work. 

https://github.com/10up/elasticpress-proxy

Would it be possible for at least some clues to be shared so we might be able to use them? I understand self-hosted is really frowned upon and not supported for business model reasons but hoping to get some help. Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JakePT** [comment]
Hi @MageNext, if you've got your self hosted Elasticsearch working with ElasticPress, then you should only need to install and activate the elasticpress-proxy as a WordPress plugin for Instant Results to work. This plugin uses the hooks available in ElasticPress to redirect API requests sent to ElasticPress.io to the proxy.php file included in the plugin. If your Elasticsearch instance has any special requirements, such as authentication, then you would need to fork the proxy plugin so that you can modify it to support authentication with your instance.

It's hard to provide any more clues than that without knowing exactly what isn't working. Are you seeing any errors anywhere, such as the browser console?

As you've noticed, it's offered as-is without any support or documentation, and may have bugs (you are free to open issues or pull requests if you can find or resolve them). If you need support or are uncomfortable modifying the proxy plugin for your needs then we recommend signing up for ElasticPress.io.
