### ISSUE TITLE
BUG: ep-highlight class being applied to single page titles & inputs

### ISSUE THREAD

**Issue by scooterlord** [10up/ElasticPress#3606]
### Describe the bug

Hello everyone. For some reason, the markup along with the class `<mark class="ep-highlight">` is being applied in various unexpected places where it shouldn't. In my contextam using frontend ACF forms to edit posts, and now the above markup appears inside my edit title field. I would only expect the highlighter to work _only_ in the search results pages. Is there a way to restrict it somehow?

### Steps to Reproduce

1. Initiate a search using a term
2. Term gets highlighted in results posts
3. Click on post
4. Edit post
5. I can see the markup in the input field

I have double-checked to verify the obvious - that it is not stored with the markup (let alone it is sanitized during save anyway)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@scooterlord, please send the Status Report (you can attach the txt file or copy and paste it into pastebin.com) and all the custom code you are using so we can try to reproduce it. Thanks.

**Comment by scooterlord** [comment]
@felipeelia thanks for the reply! Tbh, I wouldn't want to share this pastebin publicly, can I share some other way?

Regarding reproduction, there are literally a ton of functions and plugins involved, but here is a video that showcases the issue (I apologize for the quality)

https://www.youtube.com/watch?v=6znVsV-8uIg

Essentially, what's going on is:
- a post id is searched
- click on the single result and enter the single page
- here is what is curious - although we are out of the results page, you can see that the title and breadcrumb are also highlighted
- then click on edit and being navigated to the front-end ACF edit form and you can see that the title contains the `ep-highlight` markup

Hopefully the above gives some insight or a-ha moment that helps you out in some way.

**Comment by felipeelia** [comment]
@scooterlord you can share it here removing any sensible data it might contain. The one thing that I do not understand is why ElasticPress is integrated into a query that gets a single post. You'd be better served querying the database directly (also, it seems you have some custom code to have that working as well.)

**Comment by scooterlord** [comment]
@felipeelia I am not really sure how I could query the local database on-demand instead of using ES - let alone it wouldn't have the highlighter that I need. Currently what I do is, using `pre_get_posts` if there is a single result it navigates to the category that holds that result.

Unless what you meant was... wth the highligher is doing in the single post.. that's exactly what I am trying to figure out myself! Essentially, ES is only used in searces - so, I don't have any ES related functions in single.php or the custom form templates.

[elasticpress-report.txt](https://github.com/10up/ElasticPress/files/12435309/elasticpress-report.txt)

**Comment by felipeelia** [comment]
@scooterlord you got my point in that second paragraph there. You probably have some code applying `'ep_integrate' => true` in a way that it is affecting more than searches (in this case, the main query of a single post.) Unfortunately, the only thing I can recommend you to do is to install the [debugging plugins](https://elasticpress.zendesk.com/hc/en-us/articles/16670678802189-Debugging) and try to understand why ElasticPress is being integrated into that query inside the post single page.

As this is not the behavior we can see with ElasticPress out-of-the-box I'm going to close the ticket. If you’re interested in further assistance, we would be happy to help you. You can visit https://www.elasticpress.io/elasticpress-consulting/ to schedule an appointment for a consultation.

**Comment by patrickmcelwee** [comment]
I just ran into this problem, where `<mark class="ep-highlight">` was infecting my Woocommerce product titles, descriptions, and short descriptions. The issue was the combinations of Object Cache Pro and ElasticPress search highlighting. A bulk edit in Woocommerce fetches the post from the object cache, to which elasticpress added the `<mark>`s.

1. Search.php:248 builds the tag <mark class='ep-highlight'> and adds a highlight clause to the ES query. It's gated to public (front-end) requests only — is_integrated_request( 'highlighting', ['public'] ).
2. When results come back, QueryIntegration.php:492-506 overwrites the actual WP_Post fields with the highlighted strings: $post->$key = implode( ' ', $val ) for post_title, post_content, and post_excerpt.
3. EP returns those objects from posts_pre_query. WP_Query then runs its normal tail end: the_posts → array_map('get_post', …) → update_post_caches( $this->posts, … ). The highlighted objects go straight into the posts cache group via wp_cache_add_multiple().
4. You're running Object Cache Pro, so that group is persistent in Redis. The mangled post object now outlives the request.
5. Later, in wp-admin, get_post() returns the poisoned object from Redis. A WooCommerce bulk/quick edit hydrates a WC_Product from it and calls $product->save(), which writes post_title, post_content, and post_excerpt in one wp_update_post() — and logs a revision under whoever ran the edit.

My solution was just to turn off search highlighting. But ideally ElasticPress could avoid polluting the cache with the marks.

**Comment by burhandodhy** [comment]
Hi @patrickmcelwee,

This bug was already fixed in ElasticPress 5.3.4. Could you please confirm whether you are using the latest version of ElasticPress?

If you are, it appears that the position value may be stored in the stale object cache. Could you please flush the object cache, enable the **Highlight** feature, and then confirm whether you are still seeing the issue?

Regards,
Burhan

**Comment by patrickmcelwee** [comment]
I was using a previous version, though I now have installed 5.3.4, so it's great to know that it should be fixed. Thanks for letting me know!

**Comment by patrickmcelwee** [comment]
I did test it with 5.3.4 and the bug did not re-emerge. Thanks again
