### ISSUE TITLE
Unable to sync due to "Cannot declare class"

### ISSUE THREAD

**Issue by rorytassell** [10up/ElasticPress#3711]
### Describe your question

I have just setup Elasticsearch on my server and installed Elasticpress on my Wordpress website.

The website is not new, and has 400+ posts currently published.

The site is hosted on Cloudways, Digital Ocean. 

I am using the CLI to setup the Indexes, but when executing "wp elasticpress index --setup", I get this error:

```
PHP Fatal error:  Cannot declare class Jet_Listing_Item_Document, because the name is already in use in /home/397704.cloudwaysa
pps.com/gcttzqyuea/public_html/wp-content/plugins/jet-engine/includes/components/elementor-views/document-types/listing-item.ph
p on line 7                                                                                                                    
Fatal error: Cannot declare class Jet_Listing_Item_Document, because the name is already in use in /home/397704.cloudwaysapps.c
om/gcttzqyuea/public_html/wp-content/plugins/jet-engine/includes/components/elementor-views/document-types/listing-item.php on 
line 7                                                                                                                         
Sync cleared. 
```

From reading the error message, it obviously has something to do with JetEngine. I've checked the file on line 7, but this isn't really telling me anything.

Could someone point me in the right direction, what is going on?

Many Thanks,
Rory

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @rorydesign. Yeah, the problem is related to JetEngine, but you won't see anything wrong on line 7. There are two scenarios where that error can happen:

1. You have two different declarations of the Jet_Listing_Item_Document class in your codebase OR
2. The file that contains the Jet_Listing_Item_Document class is required twice.

Unfortunately, we can't help you further with that, as that is a 3rd party code  I recommend you to get in touch with the JetEngine team, they should be able to help you fix that. If that happens and you can come to this ticket sharing the solution it would be awesome! Thanks
