### ISSUE TITLE
Sync failing

### ISSUE THREAD

**Issue by busa15** [10up/ElasticPress#3714]
### Describe your question

I configured ElasticPress with my WordPress instance and was able to sync successfully on Monday.

Today after adding 20,000 new products I tried to sync and started getting an error for a large number of posts/products:

(Post): [illegal_argument_exception] Limit of total fields [5000] has been exceeded

Get-mapping shows that I have ~550 terms, which are product attributes, that likely were not in the database before adding the new products.

I added a function to my function.php to limit the meta fields, but I do not know how to limit the product attributes.

I am pretty confident that is what is causing the sync to fail.

How can I limit the number of attributes to the handful I need?

I don't think it makes a difference for this issue but I am using OpenSearch and have the version hardcoded to 10.7,
[post-1-get-mappings.zip](https://github.com/10up/ElasticPress/files/13035106/post-1-get-mappings.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @busa15,

You are in the right direction, you'll need to limit the number of meta fields being indexed (we have some code to work around that [here](https://elasticpress.zendesk.com/hc/en-us/articles/360052019111).)

Get-mapping won't help you much in this case, as the problem is what WP is trying to send to ES, not what is in ES already. Instead of trying to block certain meta keys, I recommend you go the other way around: explicitly set what should be indexed, that way you'll have more control over that limit.
