### ISSUE TITLE
With the new version ( EP 5.0.0) the Ep-geo plugin stopped working :((

### ISSUE THREAD

**Issue by IvanPigarev** [10up/ElasticPress#3768]
### Describe your question

With the new version (5.0.0), the Ep-geo plugin (https://github.com/thinkshout/ep-geo) stopped working. Indexing does not pass. Are there no plans to add geo search functions to elasticpress? Or maybe you know how to make ep-geo plugin work with the new version? :(  The plugin support unfortunately doesn't answer anything :(

https://github.com/thinkshout/ep-geo/issues/10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
The plugin relies on a compatibility layer that doesn't work anymore, so they will need to update their code to use the Feature class, available since EP 3.0.

We have a stale PR for ElasticPress Labs (partially) covering that feature: https://github.com/10up/ElasticPressLabs/pull/3

I'll keep this open for now so we can discuss internally the next steps to add a feature like that either in the main plugin or EP Labs.

**Comment by felipeelia** [comment]
Closing this one in favor of https://github.com/10up/ElasticPressLabs/issues/92.
