### ISSUE TITLE
BUG: Cannot Run Sync With Elementor Builder Active

### ISSUE THREAD

**Issue by rblackfox** [10up/ElasticPress#3793]
### Describe the bug

We are unable to run a Sync with Elementor Page Builder & Elementor Pro activated.
We know you primarily focus on compatibility with Blocks, however with the popularity of Elementor today, we wanted to let you know of the issue.
Otherwise great plugin, thank you.

### Steps to Reproduce

1. Install ElasticPress & Elementor
2. Run Sync, Sync will fail
3. Deactivate Elementor & Elementor Pro
4. Run Sync, Sync will finish successfully

### Environment information

32GB 16 Core AWS CO 4XL
Apache /Nginx
MySQL
PHPfpm
Redis
Varnish
Memcached 
ElasticSearch

### WordPress and ElasticPress information

Wordpress 
ElasticPress 5.0.0
Elastic Press Proxy 1.0.0
Elementor 3.17.3
Elementor Pro 3.17.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
Hi @rblackfox, can you please share the error you see when the sync fails? Thanks

**Comment by ChinaMIC** [comment]
I have the same problem, ElasticPress doesn't sync when the elementor plugin is turned on

**Comment by ChinaMIC** [comment]
> Hi @rblackfox, can you please share the error you see when the sync fails? Thanks

I have the same problem, ElasticPress doesn't sync when the elementor plugin is turned on

**Comment by ChinaMIC** [comment]
> Hi @rblackfox, can you please share the error you see when the sync fails? Thanks

I have the same problem, ElasticPress doesn't sync when the elementor plugin is turned on

**Comment by rblackfox** [comment]
My apologies for the late reply. Here is the error messages we get out of ElasticPress Sync:

2024-01-23 11:48:02
Starting sync…
2024-01-23 11:48:04
Indexing posts…
2024-01-23 11:48:05
Mapping sent
2024-01-23 11:49:08
Something went wrong. Find troubleshooting steps at https://elasticpress.zendesk.com/hc/en-us/articles/20857557098125/.
2024-01-23 11:49:08
Sync failed

Not much to go off of. What more can I provide? thx!

**Comment by felipeelia** [comment]
@rblackfox do you see any errors in your logs and or in your Dev Tools console?

**Comment by burhandodhy** [comment]
Hi @rblackfox & @ChinaMIC,

Following up here, can you run this WP CLI command `wp elasticpress sync --setup --yes --show-errors` and share the error logs. 

While debugging the issue, we encountered a problem with the "Custom Add To Cart" widget in Elementor Pro. It throws an error when the "Show Quantity" option is enabled, but no product is selected in the widget. This behavior can be replicated even without ElasticPress. Since it's third-party code and beyond our control, we suggest reaching out to the Elementor team for support.

Regards,
Burhan
