### ISSUE TITLE
BUG: Multiple Facets are not working together if OR relationship is used.

### ISSUE THREAD

**Issue by musharp-arslan** [10up/ElasticPress#3945]
### Describe the bug

I have created 4 Filter Facets on Instant Search and Its relation is OR, If it is AND relationship it eliminates the Filter values of filters.
I want to have OR relationship and want to have multiple selection of Facet filters.

### Steps to Reproduce

Same as Description

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
You'll have to double-check your data @musharp-arslan. Elasticsearch aggregations will only return more filter values when it is possible to use an AND condition. For example, if you have Color as a taxonomy, if you select "Blue" it will never display "Red" as an option, because something can't be blue and red at the same time (only an example, of course.)

I recommend you install our [debugging add-on](https://www.elasticpress.io/documentation/article/using-the-elasticpress-debugging-add-on-plugin/) and understand what is returned in the "aggregations" section of your Query Result.
