### ISSUE TITLE
Assistance Needed: Connecting Elasticsearch to ElasticPress WordPress Plugin

### ISSUE THREAD

**Issue by VikAndTech** [10up/ElasticPress#3948]
### Describe your question

Hi, 

I am currently trying to integrate Elasticsearch with the ElasticPress WordPress plugin on my website, but I am encountering difficulties and the connection is not working as expected. I am building a directory site on Listingpro WP theme. And they say you need to customize for it to work. the Listingpro overrides the Elasticpress integration. I am using Elstic.co and they say I need to ask you if you could help. 

Kind regards, 

Viktor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi [VikAndTech](https://github.com/VikAndTech),

In most cases, ElasticPress automatically leverages WordPress to use the Elasticsearch engine. Additionally, you can instruct the query to use Elasticsearch by passing the `ep_integrate => true` argument.

We have documentation covering topics related to development, which you can find here: https://www.elasticpress.io/documentation/section/developer-documentation/

Since this is not an issue and we do not provide support for customizations, I am closing this issue.

Regards,
Burhan
