### ISSUE TITLE
All sorts of problems suddenly.

### ISSUE THREAD

**Issue by RetroGameTalk** [10up/ElasticPress#3964]
### Describe your question

ver 5.1.3

I noticed some posts were missing from search so i tried resync.
It won't let me:
Problem 1:
```
2024-08-18 19:05:59
Starting sync…
2024-08-18 19:06:00
Cannot read properties of undefined (reading 'method')
2024-08-18 19:06:00
Sync failed
```
If i do it from CLI it does sync fine.

Problem 2: I can't save any settings, it saves and when i refresh the page it goes back to initial state, all settings. I was able to enable them via CLI
```
wp elasticpress activate-feature search
Success: Feature activated
wp elasticpress activate-feature facets
Success: Feature activated
```
I've tried removing the plugin, 
"**wp elasticpress settings-reset**"
reinstalling, to same results.

Problem 3:
I also have this error now on front-end, only if the plugin is activated, on pages with facets:
![Untitled](https://github.com/user-attachments/assets/0de4bbd2-42f0-47e8-b222-fc703bbab59b)

![Untitled3](https://github.com/user-attachments/assets/e3c71af8-9376-4751-99ef-35605cb6f8a5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by burhandodhy** [comment]
Hi @MediaMaquina,

**Issue 1:** It appears that some code is generating a warning message during the sync process, which invalidates the JSON and prevents ElasticPress from completing the sync. What is the output when you run this command `wp elasticpress sync --setup --yes --show-errors --force`?

**Issue 2:** Are you seeing any JavaScript errors in the console? Also, what is the response from the AJAX save request?

**Issue 3:** It seems that you have a cache plugin that minifies and concatenates all the JS files and the problem could be due to that. Could you please check if the issue persists when the files are not concatenated?

Regards,
Burhan
