### ISSUE TITLE
post_title and post__in Arguments filter not working in WP_Query  with ep_integrate  Set to True

### ISSUE THREAD

**Issue by mahesh-spinx** [10up/ElasticPress#4005]
### Describe your question

I am experiencing an issue with the post_title and post__in arguments in a WP_Query when ElasticPress integration is enabled (i.e., with ep_integrate set to true). These arguments do not appear to filter the results as expected when ElasticPress is active, although they function correctly when ep_integrate is disabled.

Could you please provide guidance on how to resolve this issue or offer any recommendations for working with these arguments in conjunction with ElasticPress?

```
$args = array(
	'post_type'      => 'attachment',
	'posts_per_page' => 10,        
	's'               => 'document', 
	'ep_integrate'    => true  ,
        'post_title'     => 'aggreements page',
	'post__in'       => array(20,25,36,66,55),  
	'orderby'        => 'post__in',      		
	);	
	$query = new WP_Query( $args );
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by felipeelia** [comment]
@mahesh-spinx ElasticPress does not support `post__in` as an `orderby` value (see [here](https://github.com/10up/ElasticPress/blob/5.1.3/includes/classes/Feature/Search/Search.php#L823)) and I'm unclear on what you are trying to achieve with that query. WP_Query has a "title" parameter (not `post_title`, as far as I can see [in the docs](https://developer.wordpress.org/reference/classes/wp_query/)) but it seems you reduced so much the number of posts to be returned that it would be actually faster if you query your database directly, rather than calling Elasticsearch.
