### ISSUE TITLE
Indexing thumbnail url

### ISSUE THREAD

**Issue by devlesedi** [10up/ElasticPress#515]
I just want to include the featured image url on the indexed posts. Can someone point me into the right direction?

**Comment by kingkool68** [comment]
ElasticPress integrates tightly with WP_Query so you should have no problem getting the featured image from a search result like a normal search query. You can use the loop and template tags like `the_post_thumbnail` or functions like [`get_post_thumbnail_id()`](https://codex.wordpress.org/Function_Reference/get_post_thumbnail_id) for any post inside or outside of the loop.

**Comment by rveitch** [comment]
@devlesedi It may depend on your use case, but if you just simply want the featured image URL in the post meta so that it is included on index posts, [I have a plugin written for that](https://github.com/rveitch/elasticpress-featured-image-url).  It will automatically add the featured image url to WordPress post meta for easy indexing with Elasticpress when posts are updated or published, have WP-CLI commands for updating already published posts.

![image](https://cloud.githubusercontent.com/assets/12876929/16099801/e5997cec-331f-11e6-975c-904c25543277.png)

**Comment by devlesedi** [comment]
Thanks for the feedback. @rveitch, that's what I needed. Great work.

**Comment by tlovett1** [comment]
@rveitch cool solution.

I see you have `post_views_count` there. Are you using EP to track that?

**Comment by rveitch** [comment]
@tlovett1 Thanks!  We aren't actively using it yet, but it's something I included to build up some historical data to potentially leverage in the future, and I wanted to experiment with using it for some rankings and aggregations.  Use case is a cross-site publishing and distribution system for a 300+ site contributor network.
