### ISSUE TITLE
413 errors when indexing via wp-cli

### ISSUE THREAD

**Issue by buley** [10up/ElasticPress#527]
I was consistently running into `Error: Request Entity Too Large` when trying to index my site. The workaround to get things started was to use `--nobulk`.

I'm thinking there must be a hard limit on object size and my particular bundle of posts was violating that (too much post meta?). Checking that size in PHP before sending may prevent users from postmeta-spamming themselves out of being able to index.

```
$ wp-cli.phar --path='/srv/www' --allow-root elasticpress index --network-wide
Warning: ElasticPress is already deactivated.
Indexing posts network-wide...
Processed 46/46 entries. . .
Number of posts indexed on site 1: 46
Error: Request Entity Too Large
```
---
PHP version:    5.4.16
WP-CLI version: 0.23.1

**Comment by tlovett1** [comment]
Are you using nginx or Apache? You just need to up the POST body size allowed.

**Comment by buley** [comment]
@tlovett1 This is indexing, which is `wp-cli` (PHP on the command line). What's the server interaction here? My assumption was that this was making requests against Amazon. `wp-cli.phar` uses my wp-config to make requests against the database but has no knowledge about my webserver, from what I understand.

**Comment by tlovett1** [comment]
Can you give 2.1 a try (in develop branch)?

**Comment by ethanclevenger91** [comment]
@tlovett1 I see that this is closed, but I assume the problem is pretty much what was described by @buley, a request goes out that is larger than what AWS ElasticSearch (in my case) is willing to accept.

It'd be great to see the documentation include this case and what to do to get around it. I had to dig into source to find the default per-page value for the CLI (350) so I knew what to shoot for (300 made everything enough smaller that I could finish).

**Comment by photocurio** [comment]
I index documents at a per-page setting of 5.  Occasionally I will get "request entity too large".  Then I use `--per-page=1` and it works.
