### ISSUE TITLE
Allow filtering on main bulk index query

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/ElasticPress#543]
Similar to #542:

> There were only 350 items out of the 4,600 published items that needed to be indexed (think events that are published, however only 350 events are in the future or are really 'valid', all other events are published but will never be used/seen).

Allowing specific query filtering would be beneficial, because in some instances people may wish to control what is indexed from a higher level, currently there is no real way to allow them to do that.

**Comment by AaronHolbrook** [comment]
Hah, never mind, I see now that there _is_ a filter `ep_index_post_args` which I clearly missed.

**Comment by rveitch** [comment]
I've had many instances where this would still be quite handy to have a WP-CLI flag. More specifically, flags to specify both specific sites to index/re-index on a multisite install as well as a specific post range.  

Use case example:
I had an instance were it was necessary to migrate a single user's site and posts from their previous single-site install onto an existing multisite contributor network.  The multisite install already had over 300 active sites with 6+ years of material that had already been indexed, and the migrated site had a little over 60,000 posts spanning 12 years. Due to the size of the imported content, the imports had to be broken down into batches, and (for whatever reason) did not trigger any of the indexing hooks at the time. Granted this is probably a pretty edge case,  but it would have been helpful to specify a manual targeted reindexing.
