### ISSUE TITLE
Clarify integration with WP_Query

### ISSUE THREAD

**Issue by nathanielks** [10up/ElasticPress#547]
I'm hoping you'd be able to clarify how this integrates with WP_Query: does EP hook into the query, copy the args, searches in ElasticSearch, then passes the ids back to WP_Query to be retreived from the database, or does EP completely hijack WP_Query and returns its own data?

**Comment by nathanielks** [comment]
I see that it hooks into `the_posts`, but isn't that too late? WP_Query will have already hit the database at that point. I loaded a few pages with Query Monitor on and I see the query count gets reduced, I'm just not sure where, how, or why 😅

**Comment by tlovett1** [comment]
EP passes ALL the post information back from ES. Unforunately, because of the limitations of hooks in WP, EP has to override the query being executed in WP_Query with this: https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-wp-query-integration.php#L307

After that, it substitutes back in the data found in ES.

**Comment by nathanielks** [comment]
You're awesome. Thanks @tlovett1!
