### ISSUE TITLE
Advanced Custom Fields pro Post Object and Relationship fields showing incorrect results when WooCommerce module activated 

### ISSUE THREAD

**Issue by lancevickers** [10up/ElasticPress#591]
Hi I recently upgraded to version 2.1.1 of ElasticPress and have a few ACF Pro post object fields on WooCommerce products. I noticed when I activated the WooCommerce module and reindexed everything, the fields are showing seemingly random results. I can search for the exact title of the product and it will not return it. 

Also I noticed, I have select2 search fields on these products using this plugin https://wordpress.org/plugins/select2-post-selector/  , when attempting to search on these, they return a 500 error in the JS console.

**Comment by Ritesh-patel** [comment]
Hi @lancevickers 

Thanks for reporting this issue. For ACF Pro, is it showing random results in edit product screen or while calling `get_field` function in frontend? I suggest to use https://wordpress.org/plugins/debug-bar-elasticpress/ plugin first in order to debug why you are not getting any result.

I did check **Select 2 Post Selector** plugin and setup it to use with WooCommerce products but I can search products without any error. Can you let us know the exact error you are getting in error logs? I also recommend to check it once by disabling ElasticPress to verify whether it's ElasticPress or some other plugin's conflict.

Regards,
Ritesh

**Comment by tlovett1** [comment]
@lancevickers see this?

**Comment by lancevickers** [comment]
I apologize, I got pulled into another project, but I am back to this. I will run the debug bar and let you know my results. The [Select 2 Post Selector](https://wordpress.org/plugins/select2-post-selector/) works fine without ElasticPress enabled for WooCommerce, but if you aren't getting the same error it could be a combination of things. I will give you a more detailed explanation of everything soon. 

Thanks for the advice!
Lance

**Comment by lancevickers** [comment]
Regarding the **Select 2 Post Selector** , So I am getting an error 500 in JS console from the following GET "**/wp-admin/admin-ajax.php?q=HONDA+LAWN+MO…&post_type=product&s2ps_post_select_field_id=newer_version&_=1478845412496**" and it is coming from **jquery.js:4** . 

Regarding **Advanced custom fields,** I installed the debug bar and tool mention above, but it is not logging the query from the ACF custom field currently. I will attempt to test more.

**Comment by Ritesh-patel** [comment]
Hey @lancevickers 

Regarding 500 server error, can you check error logs that what is the exact error?

Any more detail on ACF issue? As I asked earlier, is it showing random results in edit product screen or while calling `get_field` function in frontend?

Regards,
Ritesh

**Comment by Ritesh-patel** [comment]
Hi @lancevickers 

Due to inactivity we are closing this request.

Should you determine this becomes a priority again for you in the future, please reopen this request.

Regards,
Ritesh
