### ISSUE TITLE
Issue with Polylang plugin and localized home pages showing error 404 when ElasticPress activated

### ISSUE THREAD

**Issue by fidjius** [10up/ElasticPress#663]
This issue is not fixed. Case #640 should not have been closed.
Please check.

**Comment by Ritesh-patel** [comment]
Hi @fidjius 

It has been fixed in develop branch which is not public yet. Please note that code in develop branch is not ready for use in production site but you can check it in your development environment to verify. I am closing this but if you still find issue with Polyland plugin and develop branch code just reopen this issue.

Regards,
Ritesh
