### ISSUE TITLE
Support fields = ids and fields = ids=>parent in WP_Query

### ISSUE THREAD

**Issue by tlovett1** [10up/ElasticPress#724]
In the past we've tabled it since `WP_Query` short circuits when these parameters exist therefore making it theoretically not possible. However, I think we can do this be preemptively stripping the fields parameter, storing it somewhere, then returning the proper data later.

**Comment by rommeled** [comment]
The support for `'fields' => 'ids'` would be awesome. One of our clients running more than 25k products and always receiving objects are a lot more memory demanding on the server.
Do you have any timeline for this issue big return? :)

**Comment by kallehauge** [comment]
I have added a really quick proof of concept for `ids` support (granted it uses it's own `ep_fields` atm to bypass some of the other code.
The code is (sadly) made with based on `2.1.2` but I feel like the concept will do it justice. I made a PR to a fork so I could show it referenced to 2.1.2: https://github.com/kallehauge/ElasticPress/pull/1

To go through what we could do:

1. Bypass `WooCommerce`'s `'fields' => 'default'` check with our custom `ep_fields`. This could obviously be worked into the Woo module.
2. Add a hardcoded check for `ep_fields` in `EP_Api::format_args` (this should be converted into `fields` when the Woo module also supports it).
3. Check for `ep_fields` in the `filter_posts_request` method to work around the hardcoded creation of post objects - but we still fetch the results and save them in the `$posts_by_query` property for later use.
4. We take advantage of the `posts_pre_query` filter in `WP_Query` since `ids` (and also `id=>parent`) checks to see if `$this->posts` is empty _(this method could easily be simplified but I quickly copied `filter_posts_request`)_.

### The essentials

We take advantage of the `posts_pre_query` hook and populate `$this->posts` with an array of `id`'s which have been 

`WP_Query::get_posts`:
```
/**
 * Filters the posts array before the query takes place.
 *
 * Return a non-null value to bypass WordPress's default post queries.
 *
 * Filtering functions that require pagination information are encouraged to set
 * the `found_posts` and `max_num_pages` properties of the WP_Query object,
 * passed to the filter by reference. If WP_Query does not perform a database
 * query, it will not have enough information to generate these values itself.
 *
 * @since 4.6.0
 *
 * @param array|null $posts Return an array of post data to short-circuit WP's query,
 *                          or null to allow WP to run its normal queries.
 * @param WP_Query   $this  The WP_Query instance, passed by reference.
 */
$this->posts = apply_filters_ref_array( 'posts_pre_query', array( null, &$this ) );

if ( 'ids' == $q['fields'] ) {
	if ( null === $this->posts ) {
		$this->posts = $wpdb->get_col( $this->request );
	}

	$this->posts = array_map( 'intval', $this->posts );
	$this->post_count = count( $this->posts );
	$this->set_found_posts( $q, $limits );

	return $this->posts;
}
```

The results of the request when adding the `post_id` to `source` would look something like this:
```
{
    "took": 4,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "failed": 0
    },
    "hits": {
      "total": 102,
      "max_score": 1,
      "hits": [
          {
              "_index": "localdocker-1",
              "_type": "post",
              "_id": "88495",
              "_score": 1,
              "_source": {
                  "post_id": 88495
              }
          }
        ]
        ... repeated
    }
}
```
