### ISSUE TITLE
Woocommerce option ruins sorting

### ISSUE THREAD

**Issue by mikekosulin** [10up/ElasticPress#745]
I use product sort on homepage by popularity (sales)
When I turn on woocommerce option in elasticpress all products sorting by name default.
If I try to go open %SHOPHOMEPAGE%/?orderby=popularity everything's OK.

**Comment by ivankristianto** [comment]
@mikekosulin i'm investigating this issue

**Comment by ivankristianto** [comment]
I spent quite sometime debugging this.
The source of the problem is from the WC_Query:
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-query.php#L453-L483

if there is no querystring `orderby` then it fall back to the default settings.
But it set the `orderby` to `menu_order title` in line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-query.php#L449

Let me dig some more information and will do the PR
