### ISSUE TITLE
Search by phone number in Woocommerce Order Admin

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#802]
the title says it all.
I open this issue for tracking purpose.

**Comment by ivankristianto** [comment]
@fraunholz as discussed at: https://github.com/10up/ElasticPress/issues/775#issuecomment-294759087

I'll take a look at the orders search result sorting.

**Comment by fraunholz** [comment]
when a client is calling it is important to be able to search quickly also for customer number and invoice number.
For this we are using  '_wcpdf_invoice_number' (26060), '_wcpdf_formatted_invoice_number' (e.g. IN-2017-26060), '_customer_number_raw' (16823), '_customer_number' (54316823)

Since these fields contain partially numeric values, a strategy can be to search for order numbers / post id (#55571) only when the first character of the search string is a hash (#).

**Comment by ivankristianto** [comment]
This PR allow you to search by order id, email, customer name and phone number.
Since you are using custom fields (invoice number and customer number), you need to add those fields to the index using filters.

**Comment by fraunholz** [comment]
yes, I had this already working once. So let's concentrate on the other fields:
Searching by customer name looks good, email is returning too many results (because of the @-sign?) and phone number is return no result. I will do a re-index and try again.
Btw. With which version of the plugin should I test? I am using 2.2.1 plus Fix/woocommerce search order #803

**Comment by ivankristianto** [comment]
@fraunholz yeah that plugin version is fine.
searching by email has too many results because it search through ES with fuzzy logic, but it supposed to return the most relevant results first.

**Comment by fraunholz** [comment]
name, phone number, order id and email search is working

**Comment by fraunholz** [comment]
it might happen that one clicks the wrong order because of the fuzzy logic - can this be turned off to have a search that returns only direct hits?

**Comment by ivankristianto** [comment]
Yes, it can be turned off using filter.
We will make an enhancement on this in the future, but not in this PR.

**Comment by fraunholz** [comment]
changing ep_fuzziness_arg filter to 0 is giving the same results

**Comment by ivankristianto** [comment]
you can turn it off using filter:
`remove_filter( 'ep_formatted_args', 'ep_weight_recent' );`

**Comment by tlovett1** [comment]
This should be fixed in develop.
