### ISSUE TITLE
Create settings for Decay value for search feature

### ISSUE THREAD

**Issue by ivankristianto** [10up/ElasticPress#813]
The search feature come with the function_score query: https://www.elastic.co/guide/en/elasticsearch/guide/2.x/function-score-query.html

This is where the code is:
https://github.com/10up/ElasticPress/blob/develop/features/search/search.php#L168-L170

We need to have a settings to set this decay value.
cc: @tlovett1 and @tott

**Comment by lukaspawlik** [comment]
@allan23 @tlovett1 @ivankristianto 

I've built something similar for our customer who needs to play with values to find "the best ones".

Here is the screenshot how configuration looks like. We don't show the offset value as customer is interested only in number of days and "decaying aggression". We also support disabling decaying feature at all.

<img width="1477" alt="screen shot 2017-05-03 at 14 31 41" src="https://cloud.githubusercontent.com/assets/7304218/25660610/55d28c8e-300d-11e7-8781-6af601334704.png">

**Comment by ivankristianto** [comment]
@lukaspawlik it's awesome. yes couple users has been asking about this decay function.
But I wonder why not put that setting into Search module instead? because it is more relevant there.

**Comment by lukaspawlik** [comment]
@ivankristianto An update: I've just added Offset configuration too as customer asked me to do this.  I decided to build a separate new ElasticPress feature for that instead of hooking into `ep_feature_box_settings` action for Search module as JavaScript responsible for sending configuration doesn't pick any non radio field into account when building settings object sent via AJAX (I ported some of this JS into my module logic with the fix to pick all fields instead of radios).

```JavaScript
                var settings = {};

		var $settings = $feature.find('.setting-field');

		$settings.each(function() {
			var type = $( this ).attr( 'type' );
			var name = $( this ).attr( 'data-field-name' );
			var value = $( this ).attr( 'value' );

			if ( 'radio' === type ) {
				if ( $( this ).attr( 'checked' ) ) {
					settings[ name ] = value;
				}
			}
		});
```

used in 

```JavaScript
$.ajax( {
			method: 'post',
			url: ajaxurl,
			data: {
				action: 'ep_save_feature',
				feature: feature,
				nonce: epDash.nonce,
				settings: settings
			}
		} )
```

I am happy to share my code however it won't fit plugin well as I manipulate the entire query structure (depending on the fact if decaying is enabled or not) via `ep_formatted_args` filter. I'll try to prepare PR next week (or in next two weeks) for that when I have a moment.

**Comment by tlovett1** [comment]
Closing as we are just adding the on/off for date weighting.
