### ISSUE TITLE
General: Using ElasticSearch, ElasticCache (AWS) and W3TC on Wordpress

### ISSUE THREAD

**Issue by devenh** [10up/ElasticPress#846]
Hello, I have another general question. My wordpress site is currently deployed on AWS EC2 servers and I'm using the W3 Total Cache plugin along with server side caching using Elasticache (Redis) on AWS.

I am now planning on adding ElasticSearch to my site, but I wanted to make sure there was no major conflict between all the different tools that I'm using. I'm assuming that just like normal SQL queries that get cached on the server, ES queries can now get cached on my ElasticCache instance. Is that correct?

Because ElasticCache and ElasticSearch can potentially take up a lot of memory and CPU power, I am curious if there are any tips/tutorials on how to set this configuration up in the best way. I did some quick Google searches but couldn't find anything relevant.

Thanks in advance for your help!

**Comment by ivankristianto** [comment]
@devenh I'm not sure how you configure your w3tc plugin. But I'll try to answer your question.
1. If you have w3tc database cache active, and the cache query hit ( from ElasticCache/Redis ), then WP_Query won't query to ElasticSearch.
2. If you have w3tc page cache active, then WP_Query won't query to ElasticSearch.

I don't use w3tc, so i cannot recommend what the best config for you. But since we offload the most of the database query to the ES, I would suggest you don't use the database cache on w3tc to get the most from ES.
And for page cache, this is very tricky, it good in someway but not good for some. If you can exclude the page cache for your search and dynamic page, that would be good.
