### ISSUE TITLE
Fuzzy search not working on custom fields

### ISSUE THREAD

**Issue by AustinTBiggs** [10up/ElasticPress#933]
Have you searched for similar issues before submitting this one? Yes

---

When searching with the following arguments, I'm noticing the custom fields aren't fuzzy searching, am I doing something wrong here? For example, if I'm searching "Denv" I expect posts that have "Denver" in the "city" field to be returned, however, they're not being returned.

I've checked to see if my meta query args were affecting the search and the behavior didn't change.

`		$args = array(
			'ep_integrate' => true,
			's' => $query,
			'search_fields' => array(
				'post_title',
				'meta' => array(
					'street_number',
					'street_name',
					'street_address_2',
					'city',
					'state',
					'zip_code'
				),
			),
			'posts_per_page' => 20, 
			'meta_query' => array(
				array(
					'key'     => 'owner',
					'value'   => $contactId,
					'compare' => '=',
				)
			),
		);`

**Comment by lukaspawlik** [comment]
Hi @AustinTBiggs,

I am checking this. I'll get back to you later today.

**Comment by AustinTBiggs** [comment]
Thank you for checking this out - greatly appreciated!

**Comment by lukaspawlik** [comment]
Hi @AustinTBiggs,

I did check and ElasticPress uses fuzzy search for meta fields. You could work around your issue with changing fuzziness value by adding below filter right before your WP_Query

```php
add_filter( 'ep_fuzziness_arg', function () {
	return 2;
}, 10, 0 );
``` 

however it won't work well for `Washington` and `Wash`. 

Just a question: Does search term `Denv` return anything that has `Denver` in content or in title? My tests showed me that it shouldn't and that is correct due to the fuzziness definition. I believe that using wildcard search query here would have more sense than using fuzziness. Have you considered that?

**Comment by lukaspawlik** [comment]
Closing due to lack of response.

**Comment by AustinTBiggs** [comment]
Lukas,

I’ll check out wildcard searches then! Thanks so much!

Thanks,
Austin
