### ISSUE TITLE
Autosuggest not authorized

### ISSUE THREAD

**Issue by terrence-gonsalves** [10up/ElasticPress#955]
Have you searched for similar issues before submitting this one?
Yes.

Is this a bug, question or feature request?
Question.

Describe the issue you encountered:
When activating the Autosuggest feature and trying to test if the feature is working but I receive a 401 (not authorized) error when typing into the search field. Our EP configuration utilizes ES security and implements the ES_SHIELD constant and autosuggest does not seem to be using this. Would we need to define these credentials in the endpoint field in the admin?

Also, may be a stupid question, when enabling/disabling features for EP only Search and Related Posts are green, Documents and Autosuggest are yellow. Does this mean I am missing something for these features to work?

Current WordPress version: 
4.8.2

Current ElasticPress version:
2.4

Current Elasticsearch version: 
5.6

Where do you host your Elasticsearch server: 
Internally

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):
WPML
WPML All Import
WP All Imprt
CMS Tree Page View
Debug Bar
GA for WordPress
SAML Single Sign-On
Types
WP Edit Pro
Yoast SEO

Steps to reproduce:

1. Add endpoint
2. Try using search field

Screenshots, if needed:

**Comment by lukaspawlik** [comment]
@eugene-manuilov Could you please take a look at this?

**Comment by tott** [comment]
Hi Terrence,
in order for Autosuggest to work you need to setup a publicly accessible search endpoint, otherwise, the feature will fail at the authentication request. Given that the query is sent through [javascript](https://github.com/10up/ElasticPress/blob/develop/features/autosuggest/assets/js/src/autosuggest.js#L133) directly to the ElasticSearch endpoint we have no safe way of injecting the credentials into the javascript without exposing them to the public.  You need to also keep in mind that opening such endpoint should be done with caution, ensuring only desired requests will be allowed without authentication.

As for documents - you may miss the [Ingest Attachments Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html) which is needed for this feature.

I hope this helps you to move forward.

**Comment by kallehauge** [comment]
Is it due to the delay introduced by using WP REST API that the search is called directly with JavaScript? 
If yes: would be an option to create a file with the good ol' `SHORTINIT` hack that would reduce the extra delay to ~30ms (depending on the hardware) instead of 200ms+ that scales horribly with plugins?

Source for numbers: https://deliciousbrains.com/wordpress-rest-api-vs-custom-request-handlers/

**Comment by tlovett1** [comment]
@kallehauge correct.

Your solution is certainly viable. Let us know how that works!

**Comment by terrence-gonsalves** [comment]
Hi @tott 

Thanks for the response. I figured this out after reading all the information that was supplied in the plugin but I wanted to leave the question up for the yellow indicators in EP for documents, should this be green if everything is working correctly? We do have the Ingest Attachments plugin setup and when activated I get no search results.

I am just going to test on with a default theme and no plugins to see what happens.

Thanks again.

**Comment by maelsaiedy** [comment]
@terrence-gonsalves is it possible to share your configuration, I'm getting an error when using the service as well:
error
:
{,…}
col
:
9
line
:
1
reason
:
"unexpected token [START_ARRAY] after [sort]"
root_cause
:
[{type: "parsing_exception", reason: "unexpected token [START_ARRAY] after [sort]", line: 1, col: 9}]

**Comment by eugene-manuilov** [comment]
I assume everything goes well now, so closing this thread. If something is still not resolved, feel free to reopen this issue.
