### ISSUE TITLE
Searching for order title will result in post id results instead of order number.

### ISSUE THREAD

**Issue by RonalddeRooij** [10up/ElasticPress#959]
Have you searched for similar issues before submitting this one?
Yes

Is this a bug, question or feature request?
Bug/Question

Describe the issue you encountered:
I'm searching for the order number, however the search result is based on the post id.
Extra info: turning Elasticpress off, the correct result is shown.

Current WordPress version:
4.8.2

Current ElasticPress version:
2.3.2

Current Elasticsearch version:
5.2.2

Where do you host your Elasticsearch server:
Sohosted

Other plugins installed (WooCommerce, Simple Redirect Manager, etc..):

Steps to reproduce:

1. Go to WooCommerce -> Orders, search for example #73426
2. The result is based on the post id, but I think it should be order title?
3. See screenshot for futher extra explanation.

Screenshots, if needed:

![explanation](https://user-images.githubusercontent.com/16287765/32090811-98c7a5d2-baf1-11e7-972b-f8e711a670e4.jpg)

**Comment by eugene-manuilov** [comment]
Hi @RonalddeRooij! Thanks for posting this. I'm looking into it.

**Comment by eugene-manuilov** [comment]
@RonalddeRooij, could you please give me an exact list of plugins you use on your end? Also, did you enable WooCommerce support in the ElasticPress settings? And finally, did you index your site with ElasticPress?

Something weird happens on your end because WooCommerce always uses Order ID (what is actually post id in the db) in the order title (that **#xxxx by xxxx** field) and there is no way to display something wrong there.

I have checked it on my end and it works properly. It displays a proper order if I enter its id in **#xxx** format. If i turn off elasticpress, it stops finding orders because WP can't find a post with **#xxx** title in the db (WooCommerce stores **Order &ndash; October 27, 2017 @ 01:59 PM** in post titles).

**Comment by RonalddeRooij** [comment]
Hi thank you for the reply, after enabling the WooCommerce support + reindex it worked.
