### ISSUE TITLE
Possible bug with post type and "any"

### ISSUE THREAD

**Issue by penguinpower80** [10up/ElasticPress#986]
In the documentation on the front page for this project, it states:

**post_type (string/array)**
Filter posts by post type. any will search all public post types. WP_Query defaults to either post or any if no post_type is provided depending on the context of the query. This is confusing. **ElasticPress will ALWAYS default to any if no post_type is provided.** If you want to search for post posts, you MUST specify post as the post_type.

Looking through the code (specifically line approx. 1461 of class-ep-api.php, the comment states:

If not set default to post.  If search and not set, default to "any"

This seems contradictory, or at least makes the documentation incomplete??

I'm trying to find out if a post id has been indexed, and am using this:

    $q = new WP_Query(array(
        'ep_integrate'=>true,        
        'fields'=>'ids',
        'post_type'=>'any',
        'post__in'=>array(2619),       
    ));

That doesn't work, but this does:

    $post_types = get_post_types(array('public'=>true));
    $q = new WP_Query(array(
        'ep_integrate'=>true,        
        'fields'=>'ids',
        'post_type'=>$post_types,
        'post__in'=>array(2619),
        'posts_per_page'=>1,        
    ));

So, either the documentation should reflect this *or* the class-ep-api.php could be changed (maybe) to something like this (~line 1461 from master):

		if ( ! empty( $args['post_type'] ) ) {

			if ( 'any' == $args['post_type'] )  {
                                $post_types = get_post_types(array('public'=>true));
                                $args['post_type'] = $post_types;
                        }

				$post_types = (array) $args['post_type'];
				$terms_map_name = 'terms';
				if ( count( $post_types ) < 2 ) {
					$terms_map_name = 'term';
					$post_types = $post_types[0];
 				}

				$filter['bool']['must'][] = array(
					$terms_map_name => array(
						'post_type.raw' => $post_types,
					),
				);

				$use_filters = true;
			
		} elseif ( empty( $args['s'] ) ) {

Of course, I may be missing something, but (without testing) this should work to specify "any" and have it default to public post types?

**Comment by eugene-manuilov** [comment]
Thanks, @penguinpower80! I have created a pull request which adds all indexable post types if `any` is used.

**Comment by tlovett1** [comment]
ElasticPress should mimic WP_Query functionality here. Currently, WP_Query works like so:
* If no post type
    * If search or tax query, default to `any`
    * Else default to `post`

`any` should result in all post types being searched EXCEPT revisions and types where `exclude_from_search` is set to true.

From what I remember we are doing this except the tax query part. If functionality isn't behaving this way, it's a bug otherwise maybe a documentation issue.

@eugene-manuilov based on that, is this a bug?

**Comment by eugene-manuilov** [comment]
@tlovett1, ok I think I have found where the issue comes from. EP_WP_Query_Integration class unsets `post_type` variable if it equals to `any` before passing query arguments to `ep_format_args` function. That function sees that `post_type` argument is empty and there is no `s` argument, and sets `post_type` to the default value which is just `post`. That's why it doesn't work. 

So, I think that we can remove that unset in the EP_WP_Query_Integration class to resolve this issue. I have updated my pull request to have it.

**Comment by eugene-manuilov** [comment]
Re-created pull request against develop branch. #1008

**Comment by tlovett1** [comment]
@eugene-manuilov your code would result in `any` being passed to the API which would definitely break things. Did you test?

@penguinpower80 - I think I figured this out. `any` defaults to all searchable post types IF the query is a search. Your queries above are not search queries. This is how WP_Query behaves. I think the current EP behavior is correct. Although the documentation might be a bit confusing.

**Comment by eugene-manuilov** [comment]
@tlovett1 yes, i tested it locally. Everything seemed to work properly. What do you mean by "definitely break things"? What exactly it may break?
